//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QDCommonViewController.h"

#import "BMKGeoCodeSearchDelegate-Protocol.h"
#import "BMKMapViewDelegate-Protocol.h"

@class BMKGeoCodeSearch, BMKMapView, NSString, RCLocationMessage;

@interface ActivityMapViewController : QDCommonViewController <BMKGeoCodeSearchDelegate, BMKMapViewDelegate>
{
    NSString *_city;
    NSString *_address;
    BMKMapView *_mapView;
    BMKGeoCodeSearch *_geocodesearch;
    RCLocationMessage *_locationMsg;
}

@property(retain, nonatomic) RCLocationMessage *locationMsg; // @synthesize locationMsg=_locationMsg;
@property(retain, nonatomic) BMKGeoCodeSearch *geocodesearch; // @synthesize geocodesearch=_geocodesearch;
@property(retain, nonatomic) BMKMapView *mapView; // @synthesize mapView=_mapView;
@property(retain, nonatomic) NSString *address; // @synthesize address=_address;
@property(retain, nonatomic) NSString *city; // @synthesize city=_city;
- (void).cxx_destruct;
- (id)_mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)showSelectAnnotation:(id)arg1;
- (void)onGetGeoCodeResult:(id)arg1 result:(id)arg2 errorCode:(int)arg3;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithRCLocationMsg:(id)arg1;
- (id)initWithAddress:(id)arg1 city:(id)arg2;
- (id)title;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

