//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SLCommonGroupListViewController.h"

@class LWCardTextView, LWLoginTextFieldView, QMUIModalPresentationViewController, QMUITextField, RETableViewManager;

@interface AddAlipayViewController : SLCommonGroupListViewController
{
    RETableViewManager *_manager;
    LWCardTextView *_userTxtView;
    LWCardTextView *_cardTxtView;
    LWCardTextView *_cardTypeTxtView;
    LWLoginTextFieldView *_vcodeTxtView;
    QMUITextField *_pwdTextField;
    QMUIModalPresentationViewController *_payModalViewController;
}

@property(retain, nonatomic) QMUIModalPresentationViewController *payModalViewController; // @synthesize payModalViewController=_payModalViewController;
@property(retain, nonatomic) QMUITextField *pwdTextField; // @synthesize pwdTextField=_pwdTextField;
@property(retain, nonatomic) LWLoginTextFieldView *vcodeTxtView; // @synthesize vcodeTxtView=_vcodeTxtView;
@property(retain, nonatomic) LWCardTextView *cardTypeTxtView; // @synthesize cardTypeTxtView=_cardTypeTxtView;
@property(retain, nonatomic) LWCardTextView *cardTxtView; // @synthesize cardTxtView=_cardTxtView;
@property(retain, nonatomic) LWCardTextView *userTxtView; // @synthesize userTxtView=_userTxtView;
@property(retain, nonatomic) RETableViewManager *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (void)cancelBtnClicked:(id)arg1;
- (void)handelPayPassword;
- (void)payBtnClicked:(id)arg1;
- (void)inputPayPwd:(id)arg1;
- (void)bindBtnClicked:(id)arg1;
- (void)getVcode;
- (void)addSubViews;
- (_Bool)shouldHideKeyboardWhenTouchInView:(id)arg1;
- (void)initSubviews;
- (id)title;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

@end

