//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ILoginUserModel, IRcToken, ISafeIndexModel, IUserInfoModel, NSMutableArray, NSMutableDictionary;

@interface AppConfigTool : NSObject
{
    ILoginUserModel *_loginUser;
    IUserInfoModel *_userInfoModel;
    IRcToken *_rcToken;
    ISafeIndexModel *_safeIdexModel;
    NSMutableArray *_provinceArray;
    NSMutableDictionary *_allCityDic;
}

+ (id)shareInstance;
@property(retain, nonatomic) NSMutableDictionary *allCityDic; // @synthesize allCityDic=_allCityDic;
@property(retain, nonatomic) NSMutableArray *provinceArray; // @synthesize provinceArray=_provinceArray;
@property(retain, nonatomic) ISafeIndexModel *safeIdexModel; // @synthesize safeIdexModel=_safeIdexModel;
@property(retain, nonatomic) IRcToken *rcToken; // @synthesize rcToken=_rcToken;
@property(retain, nonatomic) IUserInfoModel *userInfoModel; // @synthesize userInfoModel=_userInfoModel;
@property(retain, nonatomic) ILoginUserModel *loginUser; // @synthesize loginUser=_loginUser;
- (void).cxx_destruct;
- (id)getToken;
- (id)getLoginUserSexStr;
- (id)getLoginUserSex;
- (void)refreshLoginUserToken:(id)arg1;
- (void)initLoginUserInfo;
- (void)initLoginUser:(id)arg1;
- (id)init;

@end

