//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "BMKGeneralDelegate-Protocol.h"
#import "BuglyDelegate-Protocol.h"
#import "JPUSHRegisterDelegate-Protocol.h"
#import "RCIMConnectionStatusDelegate-Protocol.h"
#import "RCIMReceiveMessageDelegate-Protocol.h"
#import "UIApplicationDelegate-Protocol.h"

@class MainViewController, NSArray, NSString, NavViewController, UIWindow;

@interface AppDelegate : UIResponder <RCIMConnectionStatusDelegate, RCIMReceiveMessageDelegate, BMKGeneralDelegate, JPUSHRegisterDelegate, BuglyDelegate, UIApplicationDelegate>
{
    _Bool _isBack;
    _Bool _isFristIn;
    _Bool _isShowUpdateAlert;
    UIWindow *_window;
    NavViewController *_loginNav;
    MainViewController *_mainVc;
    NSArray *_noticeArray;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedAppDelegate;
@property(retain, nonatomic) NSArray *noticeArray; // @synthesize noticeArray=_noticeArray;
@property(nonatomic) _Bool isShowUpdateAlert; // @synthesize isShowUpdateAlert=_isShowUpdateAlert;
@property(nonatomic) _Bool isFristIn; // @synthesize isFristIn=_isFristIn;
@property(nonatomic) _Bool isBack; // @synthesize isBack=_isBack;
@property(retain, nonatomic) MainViewController *mainVc; // @synthesize mainVc=_mainVc;
@property(retain, nonatomic) NavViewController *loginNav; // @synthesize loginNav=_loginNav;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)checkTokenExpires2;
- (void)connectRCIMWithToken:(id)arg1;
- (void)connectRCIM;
- (void)getCityLocationInfo;
- (void)delete10MinuteMessageHistory:(id)arg1;
- (void)quitAllRcGroup:(id)arg1;
- (void)quitAllRCGameGroup;
- (void)loginSucceed;
- (void)logoutWithErrormsg:(id)arg1;
- (void)checkLoginStatus;
- (void)checkRefreshToken;
- (void)checkTokenExpires;
- (void)setupUIStyle;
- (void)setupNetworkingInfo;
- (void)initRongIM;
- (void)playSound;
- (_Bool)onRCIMCustomAlertSound:(id)arg1;
- (_Bool)onRCIMCustomLocalNotification:(id)arg1 withSenderName:(id)arg2;
- (void)delteOrQuitGameGroup:(id)arg1;
- (void)onRCIMReceiveMessage:(id)arg1 left:(int)arg2;
- (void)onRCIMConnectionStatusChanged:(long long)arg1;
- (id)getAliPayUserId:(id)arg1;
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)setIconBadgeNumber;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(CDUnknownBlockType)arg3;
- (void)jpushNotificationCenter:(id)arg1 didReceiveNotificationResponse:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)jpushNotificationCenter:(id)arg1 willPresentNotification:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)initJpushInfo:(id)arg1;
- (void)networkDidReceiveMessage:(id)arg1;
- (void)jpushAPNs;
- (id)attachmentForException:(id)arg1;
- (void)registBuglyHook;
- (void)checkVersionMessageAlert:(id)arg1;
- (void)checkVersion;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

