//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@class NSLayoutConstraint, NSString, UIView;

@interface AXBadgeView : UILabel
{
    NSString *_textStorage;
    _Bool _hideOnZero;
    _Bool _scaleContent;
    UIView *_attachedView;
    unsigned long long _style;
    unsigned long long _animation;
    NSLayoutConstraint *_horizontalLayout;
    NSLayoutConstraint *_verticalLayout;
    NSLayoutConstraint *_widthLayout;
    NSLayoutConstraint *_heightLayout;
    struct CGPoint _offsets;
    struct CGPoint _position;
    struct CGSize _minSize;
}

@property(retain, nonatomic) NSLayoutConstraint *heightLayout; // @synthesize heightLayout=_heightLayout;
@property(retain, nonatomic) NSLayoutConstraint *widthLayout; // @synthesize widthLayout=_widthLayout;
@property(retain, nonatomic) NSLayoutConstraint *verticalLayout; // @synthesize verticalLayout=_verticalLayout;
@property(retain, nonatomic) NSLayoutConstraint *horizontalLayout; // @synthesize horizontalLayout=_horizontalLayout;
@property(nonatomic, getter=isScaleContent) _Bool scaleContent; // @synthesize scaleContent=_scaleContent;
@property(nonatomic) struct CGSize minSize; // @synthesize minSize=_minSize;
@property(nonatomic) _Bool hideOnZero; // @synthesize hideOnZero=_hideOnZero;
@property(nonatomic) struct CGPoint position; // @synthesize position=_position;
@property(nonatomic) struct CGPoint offsets; // @synthesize offsets=_offsets;
@property(nonatomic) unsigned long long animation; // @synthesize animation=_animation;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(nonatomic) __weak UIView *attachedView; // @synthesize attachedView=_attachedView;
- (void).cxx_destruct;
- (id)bounceAnimationWithRepeat:(double)arg1 duration:(double)arg2 forLayer:(id)arg3;
- (id)shakeAnimationWithRepeat:(double)arg1 duration:(double)arg2 forLayer:(id)arg3;
- (id)scaleAnimationFrom:(double)arg1 toScale:(double)arg2 duration:(float)arg3 repeat:(float)arg4;
- (id)rotationAnimationWithDuration:(double)arg1 degree:(double)arg2 direction:(unsigned long long)arg3 repeatCount:(unsigned long long)arg4;
- (id)breathingAnimationWithRepeat:(double)arg1 duration:(double)arg2;
- (id)breathingAnimationWithDuration:(double)arg1;
- (void)updateConstraintsOfSelfIfNeeded;
- (void)updateTextIfNeededWithText:(id)arg1;
- (void)hideAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showInView:(id)arg1 animated:(_Bool)arg2;
- (void)showAnimated:(_Bool)arg1;
- (id)text;
@property(readonly, nonatomic, getter=isVisible) _Bool visible;
- (void)setText:(id)arg1;
- (void)didMoveToSuperview;
- (void)willMoveToSuperview:(id)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (void)initializer;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

