//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QDCommonViewController.h"

#import "NJKWebViewProgressDelegate-Protocol.h"
#import "SKStoreProductViewControllerDelegate-Protocol.h"
#import "WKNavigationDelegate-Protocol.h"
#import "WKUIDelegate-Protocol.h"

@class AXSecurityPolicy, NSBundle, NSCache, NSString, NSURL, NSURLRequest, UIBarButtonItem, UILabel, UIProgressView, UIView, WKNavigation, WKWebView, WKWebViewConfiguration;
@protocol AXWebViewControllerDelegate;

@interface AXWebViewController : QDCommonViewController <NJKWebViewProgressDelegate, SKStoreProductViewControllerDelegate, WKUIDelegate, WKNavigationDelegate>
{
    WKWebView *_webView;
    NSURL *_URL;
    _Bool _loading;
    UIBarButtonItem *_doneItem;
    NSString *_HTMLString;
    NSURL *_baseURL;
    WKWebViewConfiguration *_configuration;
    CDUnknownBlockType _challengeHandler;
    AXSecurityPolicy *_securityPolicy;
    NSURLRequest *_request;
    NSBundle *_resourceBundle;
    _Bool _automaticallyAdjustsScrollViewInsets;
    NSCache *_contentOffsetCache;
    _Bool _enabledWebViewUIDelegate;
    _Bool _reviewsAppInAppStore;
    _Bool _showsToolBar;
    _Bool _showsBackgroundLabel;
    _Bool _showsNavigationCloseBarButtonItem;
    _Bool _showsNavigationBackBarButtonItemTitle;
    _Bool _checkUrlCanOpen;
    id <AXWebViewControllerDelegate> _delegate;
    unsigned long long _maxAllowedTitleLength;
    double _timeoutInternal;
    unsigned long long _cachePolicy;
    long long _navigationType;
    WKNavigation *_navigation;
    UIProgressView *_progressView;
    UIBarButtonItem *_backBarButtonItem;
    UIBarButtonItem *_forwardBarButtonItem;
    UIBarButtonItem *_refreshBarButtonItem;
    UIBarButtonItem *_stopBarButtonItem;
    UIBarButtonItem *_actionBarButtonItem;
    UIBarButtonItem *_navigationBackBarButtonItem;
    UIBarButtonItem *_navigationCloseBarButtonItem;
    UILabel *_backgroundLabel;
}

+ (void)clearWebCacheCompletion:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) UILabel *backgroundLabel; // @synthesize backgroundLabel=_backgroundLabel;
@property(retain, nonatomic) UIBarButtonItem *navigationCloseBarButtonItem; // @synthesize navigationCloseBarButtonItem=_navigationCloseBarButtonItem;
@property(retain, nonatomic) UIBarButtonItem *navigationBackBarButtonItem; // @synthesize navigationBackBarButtonItem=_navigationBackBarButtonItem;
@property(retain, nonatomic) UIBarButtonItem *actionBarButtonItem; // @synthesize actionBarButtonItem=_actionBarButtonItem;
@property(retain, nonatomic) UIBarButtonItem *stopBarButtonItem; // @synthesize stopBarButtonItem=_stopBarButtonItem;
@property(retain, nonatomic) UIBarButtonItem *refreshBarButtonItem; // @synthesize refreshBarButtonItem=_refreshBarButtonItem;
@property(retain, nonatomic) UIBarButtonItem *forwardBarButtonItem; // @synthesize forwardBarButtonItem=_forwardBarButtonItem;
@property(retain, nonatomic) UIBarButtonItem *backBarButtonItem; // @synthesize backBarButtonItem=_backBarButtonItem;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) WKNavigation *navigation; // @synthesize navigation=_navigation;
@property(nonatomic) long long navigationType; // @synthesize navigationType=_navigationType;
@property(nonatomic) _Bool checkUrlCanOpen; // @synthesize checkUrlCanOpen=_checkUrlCanOpen;
@property(nonatomic) _Bool showsNavigationBackBarButtonItemTitle; // @synthesize showsNavigationBackBarButtonItemTitle=_showsNavigationBackBarButtonItemTitle;
@property(nonatomic) _Bool showsNavigationCloseBarButtonItem; // @synthesize showsNavigationCloseBarButtonItem=_showsNavigationCloseBarButtonItem;
@property(nonatomic) _Bool showsBackgroundLabel; // @synthesize showsBackgroundLabel=_showsBackgroundLabel;
@property(nonatomic) _Bool showsToolBar; // @synthesize showsToolBar=_showsToolBar;
@property(readonly, nonatomic) NSURL *URL; // @synthesize URL=_URL;
@property(nonatomic) unsigned long long cachePolicy; // @synthesize cachePolicy=_cachePolicy;
@property(nonatomic) double timeoutInternal; // @synthesize timeoutInternal=_timeoutInternal;
@property(nonatomic) unsigned long long maxAllowedTitleLength; // @synthesize maxAllowedTitleLength=_maxAllowedTitleLength;
@property(nonatomic) _Bool reviewsAppInAppStore; // @synthesize reviewsAppInAppStore=_reviewsAppInAppStore;
@property(nonatomic) _Bool enabledWebViewUIDelegate; // @synthesize enabledWebViewUIDelegate=_enabledWebViewUIDelegate;
@property(nonatomic) id <AXWebViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)orientationChanged:(id)arg1;
- (void)hookWebContentCommitPreviewHandler;
- (void)updateNavigationItems;
- (void)updateToolbarItems;
- (void)setupSubviews;
- (void)updateFrameOfProgressView;
- (void)_updateTitleOfWebVC;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)webViewProgress:(id)arg1 updateProgress:(float)arg2;
- (void)webViewWebContentProcessDidTerminate:(id)arg1;
- (void)webView:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didReceiveServerRedirectForProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationResponse:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 runJavaScriptTextInputPanelWithPrompt:(id)arg2 defaultText:(id)arg3 initiatedByFrame:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)webView:(id)arg1 runJavaScriptConfirmPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)webView:(id)arg1 runJavaScriptAlertPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)webViewDidClose:(id)arg1;
- (id)webView:(id)arg1 createWebViewWithConfiguration:(id)arg2 forNavigationAction:(id)arg3 windowFeatures:(id)arg4;
- (void)doneButtonClicked:(id)arg1;
- (void)navigationIemHandleClose:(id)arg1;
- (void)navigationItemHandleBack:(id)arg1;
- (void)actionButtonClicked:(id)arg1;
- (void)stopClicked:(id)arg1;
- (void)reloadClicked:(id)arg1;
- (void)goForwardClicked:(id)arg1;
- (void)goBackClicked:(id)arg1;
- (void)didFailLoadWithError:(id)arg1;
- (void)didFinishLoad;
- (void)_didStartLoadWithObj:(id)arg1;
- (void)didStartLoadWithNavigation:(id)arg1;
- (void)didStartLoad;
- (void)willStop;
- (void)willReload;
- (void)willGoForward;
- (void)willGoBack;
- (void)loadHTMLString:(id)arg1 baseURL:(id)arg2;
- (void)loadURLRequest:(id)arg1;
- (void)loadURL:(id)arg1;
@property(retain, nonatomic) UIBarButtonItem *navigationCloseItem;
- (id)descriptionLabel;
- (id)resourceBundle;
@property(readonly, nonatomic) UIView *containerView;
@property(readonly, nonatomic) WKWebView *webView;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)viewSafeAreaInsetsDidChange;
- (void)willMoveToParentViewController:(id)arg1;
- (void)setAutomaticallyAdjustsScrollViewInsets:(_Bool)arg1;
- (void)dealloc;
- (_Bool)navigationBar:(id)arg1 shouldPopItem:(id)arg2;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithHTMLString:(id)arg1 baseURL:(id)arg2;
- (id)initWithRequest:(id)arg1 configuration:(id)arg2;
- (id)initWithURL:(id)arg1 configuration:(id)arg2;
- (id)initWithRequest:(id)arg1;
- (id)initWithURL:(id)arg1;
- (id)initWithAddress:(id)arg1;
- (void)initializer;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)init;
@property(retain, nonatomic) AXSecurityPolicy *securityPolicy;
@property(copy, nonatomic) CDUnknownBlockType challengeHandler;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

