//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BaseModelClient : NSObject
{
}

+ (id)updateFileWithParams:(id)arg1 apiMethodName:(id)arg2 image:(id)arg3 Success:(CDUnknownBlockType)arg4 Failed:(CDUnknownBlockType)arg5;
+ (id)getWithParams:(id)arg1 apiMethodName:(id)arg2 ignoreUnifiedResponseProcess:(_Bool)arg3 checkToken:(_Bool)arg4 Success:(CDUnknownBlockType)arg5 Failed:(CDUnknownBlockType)arg6;
+ (id)postWithParams:(id)arg1 apiMethodName:(id)arg2 ignoreUnifiedResponseProcess:(_Bool)arg3 checkToken:(_Bool)arg4 Success:(CDUnknownBlockType)arg5 Failed:(CDUnknownBlockType)arg6;

@end

