//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QMUIKit/QMUITableViewCell.h>

@class UIView;

@interface BaseTableViewCell : QMUITableViewCell
{
    _Bool _showBottomLine;
    UIView *_lineView;
}

@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(nonatomic) _Bool showBottomLine; // @synthesize showBottomLine=_showBottomLine;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)addSubViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

