//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BMKGeoCodeSearch, BMKGeoCodeSearchResult, BMKReverseGeoCodeSearchResult;

@protocol BMKGeoCodeSearchDelegate <NSObject>

@optional
- (void)onGetReverseGeoCodeResult:(BMKGeoCodeSearch *)arg1 result:(BMKReverseGeoCodeSearchResult *)arg2 errorCode:(int)arg3;
- (void)onGetGeoCodeResult:(BMKGeoCodeSearch *)arg1 result:(BMKGeoCodeSearchResult *)arg2 errorCode:(int)arg3;
@end

