//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BMKPropertyType : NSObject
{
    _Bool _bmkIdType;
    _Bool _bmkNumberType;
    _Bool _bmkBoolType;
    _Bool _bmkFromFoundation;
    _Bool _bmkKVCDisabled;
    NSString *_bmkCode;
    Class _bmkTypeClass;
}

+ (id)bmk_cachedTypeWithCode:(id)arg1;
+ (void)initialize;
@property(readonly, nonatomic, getter=isKVCDisabled) _Bool bmkKVCDisabled; // @synthesize bmkKVCDisabled=_bmkKVCDisabled;
@property(readonly, nonatomic, getter=isFromFoundation) _Bool bmkFromFoundation; // @synthesize bmkFromFoundation=_bmkFromFoundation;
@property(readonly, nonatomic) Class bmkTypeClass; // @synthesize bmkTypeClass=_bmkTypeClass;
@property(readonly, nonatomic, getter=isBoolType) _Bool bmkBoolType; // @synthesize bmkBoolType=_bmkBoolType;
@property(readonly, nonatomic, getter=isNumberType) _Bool bmkNumberType; // @synthesize bmkNumberType=_bmkNumberType;
@property(readonly, nonatomic, getter=isIdType) _Bool bmkIdType; // @synthesize bmkIdType=_bmkIdType;
@property(copy, nonatomic) NSString *bmkCode; // @synthesize bmkCode=_bmkCode;
- (void).cxx_destruct;

@end

