//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BMKPropertyKey : NSObject
{
    int _bmkType;
    NSString *_bmkName;
}

@property(nonatomic) int bmkType; // @synthesize bmkType=_bmkType;
@property(copy, nonatomic) NSString *bmkName; // @synthesize bmkName=_bmkName;
- (void).cxx_destruct;
- (id)bmk_valueInObject:(id)arg1;

@end

