//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BMKPoiIndoorInfo : NSObject
{
    _Bool _grouponFlag;
    _Bool _takeoutFlag;
    _Bool _waitedFlag;
    NSString *_name;
    NSString *_UID;
    NSString *_indoorID;
    NSString *_floor;
    NSString *_address;
    NSString *_city;
    NSString *_phone;
    NSString *_tag;
    double _price;
    long long _starLevel;
    long long _grouponNum;
    long long _discount;
    struct CLLocationCoordinate2D _pt;
}

@property(nonatomic) long long discount; // @synthesize discount=_discount;
@property(nonatomic) long long grouponNum; // @synthesize grouponNum=_grouponNum;
@property(nonatomic) _Bool waitedFlag; // @synthesize waitedFlag=_waitedFlag;
@property(nonatomic) _Bool takeoutFlag; // @synthesize takeoutFlag=_takeoutFlag;
@property(nonatomic) _Bool grouponFlag; // @synthesize grouponFlag=_grouponFlag;
@property(nonatomic) long long starLevel; // @synthesize starLevel=_starLevel;
@property(nonatomic) double price; // @synthesize price=_price;
@property(copy, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(nonatomic) struct CLLocationCoordinate2D pt; // @synthesize pt=_pt;
@property(copy, nonatomic) NSString *phone; // @synthesize phone=_phone;
@property(copy, nonatomic) NSString *city; // @synthesize city=_city;
@property(copy, nonatomic) NSString *address; // @synthesize address=_address;
@property(copy, nonatomic) NSString *floor; // @synthesize floor=_floor;
@property(copy, nonatomic) NSString *indoorID; // @synthesize indoorID=_indoorID;
@property(copy, nonatomic) NSString *UID; // @synthesize UID=_UID;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;

@end

