//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BMKPOIDetailInfo : NSObject
{
    long long _distance;
    NSString *_type;
    NSString *_tag;
    NSString *_detailURL;
    double _price;
    NSString *_openingHours;
    double _overallRating;
    double _tasteRating;
    double _serviceRating;
    double _environmentRating;
    double _facilityRating;
    double _hygieneRating;
    double _technologyRating;
    long long _imageNumber;
    long long _grouponNumber;
    long long _discountNumber;
    long long _commentNumber;
    long long _favoriteNumber;
    long long _checkInNumber;
    struct CLLocationCoordinate2D _naviLocation;
}

@property(nonatomic) long long checkInNumber; // @synthesize checkInNumber=_checkInNumber;
@property(nonatomic) long long favoriteNumber; // @synthesize favoriteNumber=_favoriteNumber;
@property(nonatomic) long long commentNumber; // @synthesize commentNumber=_commentNumber;
@property(nonatomic) long long discountNumber; // @synthesize discountNumber=_discountNumber;
@property(nonatomic) long long grouponNumber; // @synthesize grouponNumber=_grouponNumber;
@property(nonatomic) long long imageNumber; // @synthesize imageNumber=_imageNumber;
@property(nonatomic) double technologyRating; // @synthesize technologyRating=_technologyRating;
@property(nonatomic) double hygieneRating; // @synthesize hygieneRating=_hygieneRating;
@property(nonatomic) double facilityRating; // @synthesize facilityRating=_facilityRating;
@property(nonatomic) double environmentRating; // @synthesize environmentRating=_environmentRating;
@property(nonatomic) double serviceRating; // @synthesize serviceRating=_serviceRating;
@property(nonatomic) double tasteRating; // @synthesize tasteRating=_tasteRating;
@property(nonatomic) double overallRating; // @synthesize overallRating=_overallRating;
@property(copy, nonatomic) NSString *openingHours; // @synthesize openingHours=_openingHours;
@property(nonatomic) double price; // @synthesize price=_price;
@property(copy, nonatomic) NSString *detailURL; // @synthesize detailURL=_detailURL;
@property(nonatomic) struct CLLocationCoordinate2D naviLocation; // @synthesize naviLocation=_naviLocation;
@property(copy, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(nonatomic) long long distance; // @synthesize distance=_distance;
- (void).cxx_destruct;

@end

