//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BMKPOISearchFilter, NSArray;

@interface BMKPOINearbySearchOption : NSObject
{
    _Bool _isRadiusLimit;
    NSArray *_keywords;
    NSArray *_tags;
    long long _radius;
    unsigned long long _scope;
    BMKPOISearchFilter *_filter;
    long long _pageIndex;
    long long _pageSize;
    struct CLLocationCoordinate2D _location;
}

@property(nonatomic) long long pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) long long pageIndex; // @synthesize pageIndex=_pageIndex;
@property(retain, nonatomic) BMKPOISearchFilter *filter; // @synthesize filter=_filter;
@property(nonatomic) unsigned long long scope; // @synthesize scope=_scope;
@property(nonatomic) _Bool isRadiusLimit; // @synthesize isRadiusLimit=_isRadiusLimit;
@property(nonatomic) long long radius; // @synthesize radius=_radius;
@property(nonatomic) struct CLLocationCoordinate2D location; // @synthesize location=_location;
@property(copy, nonatomic) NSArray *tags; // @synthesize tags=_tags;
@property(copy, nonatomic) NSArray *keywords; // @synthesize keywords=_keywords;
- (void).cxx_destruct;
- (id)init;

@end

