//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BMKSearchBase.h"

@protocol BMKPoiSearchDelegate;

@interface BMKPoiSearch : BMKSearchBase
{
    id <BMKPoiSearchDelegate> _delegate;
}

@property(nonatomic) __weak id <BMKPoiSearchDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)poiIndoorSearch:(id)arg1;
- (_Bool)poiDetailSearch:(id)arg1;
- (_Bool)poiSearchNearBy:(id)arg1;
- (_Bool)poiSearchInbounds:(id)arg1;
- (_Bool)poiSearchInCity:(id)arg1;
- (id)init;

@end

