//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface BMKPOIDetailSearchOption : NSObject
{
    NSArray *_poiUIDs;
    unsigned long long _scope;
}

@property(nonatomic) unsigned long long scope; // @synthesize scope=_scope;
@property(copy, nonatomic) NSArray *poiUIDs; // @synthesize poiUIDs=_poiUIDs;
- (void).cxx_destruct;
- (id)init;

@end

