//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BMKPOIIndoorSearchOption : NSObject
{
    NSString *_indoorID;
    NSString *_keyword;
    NSString *_floor;
    long long _pageIndex;
    long long _pageSize;
}

@property(nonatomic) long long pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) long long pageIndex; // @synthesize pageIndex=_pageIndex;
@property(copy, nonatomic) NSString *floor; // @synthesize floor=_floor;
@property(copy, nonatomic) NSString *keyword; // @synthesize keyword=_keyword;
@property(copy, nonatomic) NSString *indoorID; // @synthesize indoorID=_indoorID;
- (void).cxx_destruct;
- (id)init;

@end

