//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BMKPOIDetailInfo, NSString;

@interface BMKPoiInfo : NSObject
{
    _Bool _hasDetailInfo;
    NSString *_name;
    NSString *_address;
    NSString *_phone;
    NSString *_UID;
    NSString *_province;
    NSString *_city;
    NSString *_area;
    NSString *_streetID;
    BMKPOIDetailInfo *_detailInfo;
    struct CLLocationCoordinate2D _pt;
}

@property(retain, nonatomic) BMKPOIDetailInfo *detailInfo; // @synthesize detailInfo=_detailInfo;
@property(nonatomic) _Bool hasDetailInfo; // @synthesize hasDetailInfo=_hasDetailInfo;
@property(copy, nonatomic) NSString *streetID; // @synthesize streetID=_streetID;
@property(copy, nonatomic) NSString *area; // @synthesize area=_area;
@property(copy, nonatomic) NSString *city; // @synthesize city=_city;
@property(copy, nonatomic) NSString *province; // @synthesize province=_province;
@property(copy, nonatomic) NSString *UID; // @synthesize UID=_UID;
@property(copy, nonatomic) NSString *phone; // @synthesize phone=_phone;
@property(copy, nonatomic) NSString *address; // @synthesize address=_address;
@property(nonatomic) struct CLLocationCoordinate2D pt; // @synthesize pt=_pt;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;

@end

