//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BMKPOISearchFilter, NSArray;

@interface BMKPOIBoundSearchOption : NSObject
{
    NSArray *_keywords;
    NSArray *_tags;
    unsigned long long _scope;
    BMKPOISearchFilter *_filter;
    long long _pageIndex;
    long long _pageSize;
    struct CLLocationCoordinate2D _leftBottom;
    struct CLLocationCoordinate2D _rightTop;
}

@property(nonatomic) long long pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) long long pageIndex; // @synthesize pageIndex=_pageIndex;
@property(retain, nonatomic) BMKPOISearchFilter *filter; // @synthesize filter=_filter;
@property(nonatomic) unsigned long long scope; // @synthesize scope=_scope;
@property(nonatomic) struct CLLocationCoordinate2D rightTop; // @synthesize rightTop=_rightTop;
@property(nonatomic) struct CLLocationCoordinate2D leftBottom; // @synthesize leftBottom=_leftBottom;
@property(copy, nonatomic) NSArray *tags; // @synthesize tags=_tags;
@property(copy, nonatomic) NSArray *keywords; // @synthesize keywords=_keywords;
- (void).cxx_destruct;
- (id)init;

@end

