//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BMKSearchPOIIndoorRequest : NSObject
{
    CDUnknownBlockType _POIIndoorBlock;
}

@property(copy, nonatomic) CDUnknownBlockType POIIndoorBlock; // @synthesize POIIndoorBlock=_POIIndoorBlock;
- (void).cxx_destruct;
- (id)POIIndoorParameters:(id)arg1;
- (void)sendPOIIndoorRequest:(id)arg1;

@end

