//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BMKSearchGeoCodeContentInfoModel : NSObject
{
    NSObject *_coord;
    NSString *_wd;
}

@property(copy, nonatomic) NSString *wd; // @synthesize wd=_wd;
@property(retain, nonatomic) NSObject *coord; // @synthesize coord=_coord;
- (void).cxx_destruct;

@end

