//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BMKSearchPOIIndoorDataModel, NSString;

@interface BMKSearchPOIIndoorModel : NSObject
{
    long long _errNo;
    BMKSearchPOIIndoorDataModel *_data;
    NSString *_Msg;
}

+ (id)objectClassInArray;
@property(copy, nonatomic) NSString *Msg; // @synthesize Msg=_Msg;
@property(retain, nonatomic) BMKSearchPOIIndoorDataModel *data; // @synthesize data=_data;
@property(nonatomic) long long errNo; // @synthesize errNo=_errNo;
- (void).cxx_destruct;

@end

