//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BMKSearchReverseGeoCodeResultInfoModel;

@interface BMKSearchReverseGeoCodeModel : NSObject
{
    long long _status;
    BMKSearchReverseGeoCodeResultInfoModel *_result;
}

+ (id)objectClassInArray;
@property(retain, nonatomic) BMKSearchReverseGeoCodeResultInfoModel *result; // @synthesize result=_result;
@property(nonatomic) long long status; // @synthesize status=_status;
- (void).cxx_destruct;

@end

