//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BMKSearchPOIDetailInfoModel, NSString;

@interface BMKSearchPOIInfoModel : NSObject
{
    NSString *_name;
    NSObject *_location;
    NSString *_address;
    NSString *_province;
    NSString *_city;
    NSString *_area;
    NSString *_street_id;
    NSString *_telephone;
    NSString *_detail;
    NSString *_uid;
    BMKSearchPOIDetailInfoModel *_detail_info;
}

+ (id)objectClassInArray;
@property(retain, nonatomic) BMKSearchPOIDetailInfoModel *detail_info; // @synthesize detail_info=_detail_info;
@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(copy, nonatomic) NSString *detail; // @synthesize detail=_detail;
@property(copy, nonatomic) NSString *telephone; // @synthesize telephone=_telephone;
@property(copy, nonatomic) NSString *street_id; // @synthesize street_id=_street_id;
@property(copy, nonatomic) NSString *area; // @synthesize area=_area;
@property(copy, nonatomic) NSString *city; // @synthesize city=_city;
@property(copy, nonatomic) NSString *province; // @synthesize province=_province;
@property(copy, nonatomic) NSString *address; // @synthesize address=_address;
@property(retain, nonatomic) NSObject *location; // @synthesize location=_location;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;

@end

