//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BMKSearchPOINearbyRequest : NSObject
{
    CDUnknownBlockType _POINearbyBlock;
}

@property(copy, nonatomic) CDUnknownBlockType POINearbyBlock; // @synthesize POINearbyBlock=_POINearbyBlock;
- (void).cxx_destruct;
- (id)POINearbyParameters:(id)arg1;
- (void)sendPOINearbyRequest:(id)arg1;

@end

