//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BMKSearchAddressComponentInfoModel, NSArray, NSString;

@interface BMKSearchReverseGeoCodeResultInfoModel : NSObject
{
    BMKSearchAddressComponentInfoModel *_addressComponent;
    NSString *_formatted_address;
    NSString *_business;
    NSString *_sematic_description;
    NSString *_cityCode;
    NSArray *_pois;
    NSObject *_location;
}

+ (id)objectClassInArray;
@property(retain, nonatomic) NSObject *location; // @synthesize location=_location;
@property(copy, nonatomic) NSArray *pois; // @synthesize pois=_pois;
@property(copy, nonatomic) NSString *cityCode; // @synthesize cityCode=_cityCode;
@property(copy, nonatomic) NSString *sematic_description; // @synthesize sematic_description=_sematic_description;
@property(copy, nonatomic) NSString *business; // @synthesize business=_business;
@property(copy, nonatomic) NSString *formatted_address; // @synthesize formatted_address=_formatted_address;
@property(retain, nonatomic) BMKSearchAddressComponentInfoModel *addressComponent; // @synthesize addressComponent=_addressComponent;
- (void).cxx_destruct;

@end

