//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BMKSearchAddressComponentInfoModel : NSObject
{
    NSString *_street_number;
    NSString *_street;
    NSString *_district;
    NSString *_city;
    NSString *_province;
    NSString *_country;
    NSString *_country_code;
    NSString *_adcode;
    NSString *_town;
    NSString *_direction;
    NSString *_distance;
}

@property(copy, nonatomic) NSString *distance; // @synthesize distance=_distance;
@property(copy, nonatomic) NSString *direction; // @synthesize direction=_direction;
@property(copy, nonatomic) NSString *town; // @synthesize town=_town;
@property(copy, nonatomic) NSString *adcode; // @synthesize adcode=_adcode;
@property(copy, nonatomic) NSString *country_code; // @synthesize country_code=_country_code;
@property(copy, nonatomic) NSString *country; // @synthesize country=_country;
@property(copy, nonatomic) NSString *province; // @synthesize province=_province;
@property(copy, nonatomic) NSString *city; // @synthesize city=_city;
@property(copy, nonatomic) NSString *district; // @synthesize district=_district;
@property(copy, nonatomic) NSString *street; // @synthesize street=_street;
@property(copy, nonatomic) NSString *street_number; // @synthesize street_number=_street_number;
- (void).cxx_destruct;

@end

