//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BMKSearchPOIDetailRequest : NSObject
{
    CDUnknownBlockType _POIDetailBlock;
}

@property(copy, nonatomic) CDUnknownBlockType POIDetailBlock; // @synthesize POIDetailBlock=_POIDetailBlock;
- (void).cxx_destruct;
- (id)POIDetailParameters:(id)arg1;
- (void)sendPOIDetailRequest:(id)arg1;

@end

