//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BMKSearchReverseGeoCodePOIInfoModel : NSObject
{
    NSString *_name;
    NSString *_uid;
    NSString *_addr;
    NSString *_tel;
    NSString *_zip;
    NSObject *_point;
    NSString *_direction;
    long long _distance;
    NSString *_poiType;
    NSString *_parent_poi;
}

@property(copy, nonatomic) NSString *parent_poi; // @synthesize parent_poi=_parent_poi;
@property(copy, nonatomic) NSString *poiType; // @synthesize poiType=_poiType;
@property(nonatomic) long long distance; // @synthesize distance=_distance;
@property(copy, nonatomic) NSString *direction; // @synthesize direction=_direction;
@property(retain, nonatomic) NSObject *point; // @synthesize point=_point;
@property(copy, nonatomic) NSString *zip; // @synthesize zip=_zip;
@property(copy, nonatomic) NSString *tel; // @synthesize tel=_tel;
@property(copy, nonatomic) NSString *addr; // @synthesize addr=_addr;
@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;

@end

