//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@class NSString, UIColor;

@interface CALayer (WLBorderConfig)
- (void)wl_setRoundCornerRadius:(double)arg1 corners:(unsigned long long)arg2 borderWidth:(double)arg3 borderColor:(id)arg4 borderLineJoin:(int)arg5;
@property(nonatomic) struct UIEdgeInsets borderEdgeInsets; // @dynamic borderEdgeInsets;
@property(nonatomic) NSString *borderWidths;
@property(nonatomic) UIColor *shadowColorFromUIColor;
@property(nonatomic) UIColor *borderColorFromUIColor;
@end

