//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Function Pointers and Blocks

typedef void (*CDUnknownFunctionPointerType)(void); // return type and parameters are unknown

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct APTaskInfoData {
    unsigned char _field1[30];
};

struct BMKPoint {
    double x;
    double y;
};

struct BMKQuadrangle {
    struct BMKPoint lb;
    struct BMKPoint lt;
    struct BMKPoint rt;
    struct BMKPoint rb;
};

struct BMKRect {
    long long left;
    long long right;
    long long top;
    long long bottom;
};

struct BMMapMsgObserver {
    CDUnknownFunctionPointerType *_field1;
};

struct BMMapStatus {
    double fLevel;
    double fRotation;
    double fOverlooking;
    struct BMKPoint ptCenter;
    struct BMKQuadrangle mapRound;
    struct BMKRect winRound;
    double centerXoffset;
    double centerYoffset;
};

struct CAssoc;

struct CBGLProgramCache;

struct CGAffineTransform {
    double a;
    double b;
    double c;
    double d;
    double tx;
    double ty;
};

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct CLLocationCoordinate2D {
    double latitude;
    double longitude;
};

struct CMapGesture {
    CDUnknownFunctionPointerType *_vptr$CMapGesture;
    int m_bMouseDown;
    struct CVPoint m_ptMove;
    struct CVPoint m_ptUp;
    struct CVPoint m_ptDown;
    unsigned long long m_LastDownTime;
    float m_level;
    int m_retinaScreenScale;
    struct CVArray<_baidu_framework::tag_PaoPaoAttribute, _baidu_framework::tag_PaoPaoAttribute &> m_PaopaoAtt;
    struct IVMapbaseInterface *m_mapControl;
    float m_minZoomLevel;
    float m_maxZoomLevel;
};

struct CMapModeEngine {
    CDUnknownFunctionPointerType *_vptr$CMapModeEngine;
    struct IVMapbaseInterface *m_mapControl;
};

struct CMatrixStack;

struct CSearchInterface {
    CDUnknownFunctionPointerType *_field1;
};

struct CTextRenderer;

struct CVArray<_baidu_framework::tag_PaoPaoAttribute, _baidu_framework::tag_PaoPaoAttribute &> {
    CDUnknownFunctionPointerType *_vptr$CVArray;
    struct tag_PaoPaoAttribute *m_pData;
    int m_iSize;
    int m_iMaxSize;
    int m_iGrowBy;
    int m_iTemp;
};

struct CVArray<_baidu_vi::CVBundle, _baidu_vi::CVBundle &> {
    CDUnknownFunctionPointerType *_field1;
    struct CVBundle *_field2;
    int _field3;
    int _field4;
    int _field5;
    int _field6;
};

struct CVBGL {
    int _field1[4];
    float _field2[16];
    float _field3[16];
    struct CMatrixStack *_field4;
    struct CBGLProgramCache *_field5;
    struct CVThread _field6;
    CDUnknownFunctionPointerType _field7;
    int _field8;
    int _field9;
    int _field10;
    int _field11;
    float _field12;
    float _field13;
    float _field14;
    float _field15;
    float _field16;
    float _field17;
    float _field18;
    float _field19;
    float _field20;
    int _field21;
    int _field22;
    int _field23;
    int _field24;
    float _field25;
    struct _VColor _field26;
    struct CTextRenderer *_field27;
};

struct CVBundle {
    struct CVMapStringToPtr _field1;
};

struct CVGpsDetailInfo {
    int _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
    float _field7;
    unsigned short _field8;
    unsigned short _field9;
    struct tagVTime _field10;
    int _field11;
};

struct CVMapStringToPtr {
    CDUnknownFunctionPointerType *_field1;
    struct CAssoc **_field2;
    unsigned int _field3;
    int _field4;
    struct CAssoc *_field5;
    int _field6;
    struct CVPlex *_field7;
};

struct CVPlex;

struct CVPoint {
    int x;
    int y;
};

struct CVString {
    CDUnknownFunctionPointerType *_field1;
    unsigned short *_field2;
};

struct CVThread {
    CDUnknownFunctionPointerType *_field1;
    void *_field2;
    unsigned long long _field3;
    unsigned int _field4;
};

struct IVMapbaseInterface {
    CDUnknownFunctionPointerType *_field1;
};

struct RCConnectAckListener {
    CDUnknownFunctionPointerType *_field1;
    CDUnknownBlockType _field2;
    CDUnknownBlockType _field3;
    CDUnknownBlockType _field4;
    _Bool _field5;
};

struct RCConnectionCollectionListener {
    CDUnknownFunctionPointerType *_field1;
};

struct RCConnectionStatusChangeListener {
    CDUnknownFunctionPointerType *_field1;
    id _field2;
};

struct RCFilterListener {
    CDUnknownFunctionPointerType *_field1;
};

struct RCReceiveMessageListener {
    CDUnknownFunctionPointerType *_field1;
    id _field2;
    id _field3;
    id _field4;
};

struct UIEdgeInsets {
    double top;
    double left;
    double bottom;
    double right;
};

struct WLRadius {
    double _field1;
    double _field2;
    double _field3;
    double _field4;
};

struct _NSRange {
    unsigned long long location;
    unsigned long long length;
};

struct _VColor {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
};

struct _opaque_pthread_mutex_t {
    long long __sig;
    char __opaque[56];
};

struct _utils {
    CDUnknownFunctionPointerType _field1;
};

struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> {
    struct __compressed_pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__rep, std::__1::allocator<char>> {
        struct __rep {
            union {
                struct __long {
                    char *_field1;
                    unsigned long long _field2;
                    unsigned long long _field3;
                } _field1;
                struct __short {
                    char _field1[23];
                    struct {
                        unsigned char _field1;
                    } _field2;
                } _field2;
                struct __raw {
                    unsigned long long _field1[3];
                } _field3;
            } _field1;
        } _field1;
    } _field1;
};

struct in6_addr {
    union {
        unsigned char _field1[16];
        unsigned short _field2[8];
        unsigned int _field3[4];
    } _field1;
};

struct in_addr {
    unsigned int _field1;
};

struct sockaddr {
    unsigned char _field1;
    unsigned char _field2;
    char _field3[14];
};

struct sockaddr_in {
    unsigned char _field1;
    unsigned char _field2;
    unsigned short _field3;
    struct in_addr _field4;
    char _field5[8];
};

struct sockaddr_in6 {
    unsigned char _field1;
    unsigned char _field2;
    unsigned short _field3;
    unsigned int _field4;
    struct in6_addr _field5;
    unsigned int _field6;
};

struct sockaddr_un {
    unsigned char _field1;
    unsigned char _field2;
    char _field3[104];
};

struct tagVTime {
    union {
        struct {
            unsigned long long _field1;
            unsigned int :4;
            unsigned int :5;
            unsigned int :5;
            unsigned int :6;
            unsigned int :6;
            unsigned int :6;
        } _field1;
        unsigned long long _field2;
        unsigned long long _field3;
    } _field1;
};

struct tag_PaoPaoAttribute;

struct tm {
    int tm_sec;
    int tm_min;
    int tm_hour;
    int tm_mday;
    int tm_mon;
    int tm_year;
    int tm_wday;
    int tm_yday;
    int tm_isdst;
    long long tm_gmtoff;
    char *tm_zone;
};

#pragma mark Typedef'd Structures

typedef struct {
    int used;
    int alloc;
    int sign;
    unsigned long long *dp;
} CDStruct_c40cccb6;

typedef struct {
    long long version;
    void *info;
    CDUnknownFunctionPointerType retain;
    CDUnknownFunctionPointerType release;
    CDUnknownFunctionPointerType copyDescription;
} CDStruct_4210025a;

typedef struct {
    struct {
        double x;
        double y;
    } origin;
    struct {
        double width;
        double height;
    } size;
} CDStruct_02837cd9;

typedef struct {
    struct CLLocationCoordinate2D center;
    struct {
        double latitudeDelta;
        double longitudeDelta;
    } span;
} CDStruct_b7cb895d;

typedef struct {
    struct CLLocationCoordinate2D northEast;
    struct CLLocationCoordinate2D southWest;
} CDStruct_3ec1b870;

// Ambiguous groups
typedef struct {
    double _field1;
    double _field2;
} CDStruct_c3b9c2ee;

typedef struct CVArray<_baidu_vi::CVBundle, _baidu_vi::CVBundle &> {
    CDUnknownFunctionPointerType *_field1;
    struct CVBundle *_field2;
    int _field3;
    int _field4;
    int _field5;
    int _field6;
} CVArray_4812fe32;

typedef struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> {
    struct __compressed_pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__rep, std::__1::allocator<char>> {
        struct __rep {
            union {
                struct __long {
                    char *_field1;
                    unsigned long long _field2;
                    unsigned long long _field3;
                } _field1;
                struct __short {
                    char _field1[23];
                    struct {
                        unsigned char _field1;
                    } _field2;
                } _field2;
                struct __raw {
                    unsigned long long _field1[3];
                } _field3;
            } _field1;
        } _field1;
    } _field1;
} basic_string_7c0a1c0b;

