//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SLCommonGroupListViewController.h"

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class IFriendModel, NSString, REBoolItem, RETableViewItem, RETableViewManager, UICollectionView, UIView;

@interface ChatInfoViewController : SLCommonGroupListViewController <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout>
{
    NSString *_uid;
    IFriendModel *_friendModel;
    RETableViewManager *_manager;
    UIView *_headerView;
    UICollectionView *_mainCollectionView;
    REBoolItem *_notDisturbItem;
    REBoolItem *_topItem;
    RETableViewItem *_chatHistoryItem;
    RETableViewItem *_clearChatHistoryItem;
}

@property(retain, nonatomic) RETableViewItem *clearChatHistoryItem; // @synthesize clearChatHistoryItem=_clearChatHistoryItem;
@property(retain, nonatomic) RETableViewItem *chatHistoryItem; // @synthesize chatHistoryItem=_chatHistoryItem;
@property(retain, nonatomic) REBoolItem *topItem; // @synthesize topItem=_topItem;
@property(retain, nonatomic) REBoolItem *notDisturbItem; // @synthesize notDisturbItem=_notDisturbItem;
@property(retain, nonatomic) UICollectionView *mainCollectionView; // @synthesize mainCollectionView=_mainCollectionView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) RETableViewManager *manager; // @synthesize manager=_manager;
@property(retain, nonatomic) IFriendModel *friendModel; // @synthesize friendModel=_friendModel;
@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
- (void).cxx_destruct;
- (void)lookMoreUserBtn:(id)arg1;
- (void)quitBtn:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)changeNotDisurbInfo:(id)arg1;
- (void)changeNotDisturb:(id)arg1;
- (void)changeChatTopInfo:(id)arg1;
- (void)changeChatTop:(id)arg1;
- (void)changeChatReject:(id)arg1;
- (void)clearChatMessage;
- (void)clearChatMessageAlert;
- (void)searchChatHistory;
- (void)addTableViewCell;
- (void)addTableHeaderInfo;
- (void)updateUI;
- (void)loadData;
- (void)viewDidLoad;
- (void)initSubviews;
- (id)title;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

