//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCMessageCell.h"

@class QMUILabel, UIImageView, UIView;

@interface ChatRedPacketCell : RCMessageCell
{
    UIView *_backView;
    UIImageView *_backImageView;
    QMUILabel *_nameLabel;
    QMUILabel *_statusLabel;
    QMUILabel *_bottomLabel;
}

+ (struct CGSize)sizeForMessageModel:(id)arg1 withCollectionViewWidth:(double)arg2 referenceExtraHeight:(double)arg3;
@property(retain, nonatomic) QMUILabel *bottomLabel; // @synthesize bottomLabel=_bottomLabel;
@property(retain, nonatomic) QMUILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(retain, nonatomic) QMUILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *backImageView; // @synthesize backImageView=_backImageView;
@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
- (void).cxx_destruct;
- (void)setDataModel:(id)arg1;
- (void)didRedPacketTap;
- (id)initWithFrame:(struct CGRect)arg1;

@end

