//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseTableViewCell.h"

@class QMUILabel, RCMessage, UIImageView;

@interface ChatHistoryTableViewCell : BaseTableViewCell
{
    RCMessage *_message;
    QMUILabel *_infoLabel;
    UIImageView *_imgImageView;
}

+ (double)configureWithMessage:(id)arg1;
@property(retain, nonatomic) UIImageView *imgImageView; // @synthesize imgImageView=_imgImageView;
@property(retain, nonatomic) QMUILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(retain, nonatomic) RCMessage *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setup;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

