//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QDCommonViewController.h"

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class IGroupDetailInfo, NSMutableArray, NSString, UICollectionView, UIView;

@interface ChatGroupMoreUserViewController : QDCommonViewController <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout>
{
    _Bool _isIn;
    IGroupDetailInfo *_groupDetailInfo;
    UIView *_headerView;
    UICollectionView *_mainCollectionView;
    NSMutableArray *_datasource;
    long long _page;
}

@property(nonatomic) long long page; // @synthesize page=_page;
@property(retain, nonatomic) NSMutableArray *datasource; // @synthesize datasource=_datasource;
@property(nonatomic) _Bool isIn; // @synthesize isIn=_isIn;
@property(retain, nonatomic) UICollectionView *mainCollectionView; // @synthesize mainCollectionView=_mainCollectionView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) IGroupDetailInfo *groupDetailInfo; // @synthesize groupDetailInfo=_groupDetailInfo;
- (void).cxx_destruct;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)deleteUser:(id)arg1 index:(long long)arg2;
- (void)deleteUserAlert:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)addTableHeaderInfo;
- (void)loadData;
- (void)loadGroupUser;
- (void)beginPullUpRefreshingNew;
- (void)beginPullDownRefreshingNew;
- (void)viewDidLoad;
- (void)initSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (id)title;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

