//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QDCommonViewController.h"

@class IGroupDetailInfo, LWLoginTextFieldView;

@interface ChatGroupRemarkViewController : QDCommonViewController
{
    IGroupDetailInfo *_groupDetailInfo;
    LWLoginTextFieldView *_nameTxtView;
}

@property(retain, nonatomic) LWLoginTextFieldView *nameTxtView; // @synthesize nameTxtView=_nameTxtView;
@property(retain, nonatomic) IGroupDetailInfo *groupDetailInfo; // @synthesize groupDetailInfo=_groupDetailInfo;
- (void).cxx_destruct;
- (void)rightBarButtonItemClicked;
- (void)addConstrainsForSubviews;
- (_Bool)shouldHideKeyboardWhenTouchInView:(id)arg1;
- (void)addSubviews;
- (void)initSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)title;

@end

