//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QDCommonViewController.h"

#import "QMUITextViewDelegate-Protocol.h"

@class IGroupDetailInfo, NSString, QMUITextView;

@interface ChatGroupNoteInfoViewController : QDCommonViewController <QMUITextViewDelegate>
{
    IGroupDetailInfo *_groupDetailInfo;
    QMUITextView *_textView;
    double _textViewMinimumHeight;
}

@property(nonatomic) double textViewMinimumHeight; // @synthesize textViewMinimumHeight=_textViewMinimumHeight;
@property(retain, nonatomic) QMUITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) IGroupDetailInfo *groupDetailInfo; // @synthesize groupDetailInfo=_groupDetailInfo;
- (void).cxx_destruct;
- (void)rightBarButtonItemClicked;
- (_Bool)textViewShouldReturn:(id)arg1;
- (void)textView:(id)arg1 didPreventTextChangeInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textView:(id)arg1 newHeightAfterTextChanged:(double)arg2;
- (void)addConstrainsForSubviews;
- (_Bool)shouldHideKeyboardWhenTouchInView:(id)arg1;
- (void)addSubviews;
- (void)initSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)title;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

