//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCMessageBaseCell.h"

@class QMUIButton, QMUILabel, UIImageView, UIView;

@interface ChatGetRedPacketCell : RCMessageBaseCell
{
    UIView *_backView;
    UIImageView *_redIconImageView;
    QMUILabel *_titleLabel;
    QMUIButton *_redBtn;
}

+ (struct CGSize)sizeForMessageModel:(id)arg1 withCollectionViewWidth:(double)arg2 referenceExtraHeight:(double)arg3;
@property(retain, nonatomic) QMUIButton *redBtn; // @synthesize redBtn=_redBtn;
@property(retain, nonatomic) QMUILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *redIconImageView; // @synthesize redIconImageView=_redIconImageView;
@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setDataModel:(id)arg1;
- (void)redBtnClicked:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

