//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseTableViewCell.h"

@class IRedPacektMemberModel, QMUILabel, UIImageView;

@interface ChatRedPacketTableViewCell : BaseTableViewCell
{
    IRedPacektMemberModel *_redPacketMemberModel;
    QMUILabel *_moenyLabel;
    UIImageView *_leiImageView;
}

@property(retain, nonatomic) UIImageView *leiImageView; // @synthesize leiImageView=_leiImageView;
@property(retain, nonatomic) QMUILabel *moenyLabel; // @synthesize moenyLabel=_moenyLabel;
@property(retain, nonatomic) IRedPacektMemberModel *redPacketMemberModel; // @synthesize redPacketMemberModel=_redPacketMemberModel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setup;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

