//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SLCommonGroupListViewController.h"

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class IGroupDetailInfo, NSString, QMUIFillButton, REBoolItem, RETableViewItem, RETableViewManager, UIButton, UICollectionView, UIView;

@interface ChatGroupDetailViewController : SLCommonGroupListViewController <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout>
{
    _Bool _isIn;
    NSString *_groupId;
    IGroupDetailInfo *_groupDetailInfo;
    RETableViewManager *_manager;
    UIView *_headerView;
    UICollectionView *_mainCollectionView;
    UIButton *_lookMoreUserBtn;
    RETableViewItem *_nameItem;
    RETableViewItem *_noteItem;
    RETableViewItem *_cartItem;
    REBoolItem *_notDisturbItem;
    REBoolItem *_topItem;
    QMUIFillButton *_quitBtn;
}

@property(nonatomic) _Bool isIn; // @synthesize isIn=_isIn;
@property(retain, nonatomic) QMUIFillButton *quitBtn; // @synthesize quitBtn=_quitBtn;
@property(retain, nonatomic) REBoolItem *topItem; // @synthesize topItem=_topItem;
@property(retain, nonatomic) REBoolItem *notDisturbItem; // @synthesize notDisturbItem=_notDisturbItem;
@property(retain, nonatomic) RETableViewItem *cartItem; // @synthesize cartItem=_cartItem;
@property(retain, nonatomic) RETableViewItem *noteItem; // @synthesize noteItem=_noteItem;
@property(retain, nonatomic) RETableViewItem *nameItem; // @synthesize nameItem=_nameItem;
@property(retain, nonatomic) UIButton *lookMoreUserBtn; // @synthesize lookMoreUserBtn=_lookMoreUserBtn;
@property(retain, nonatomic) UICollectionView *mainCollectionView; // @synthesize mainCollectionView=_mainCollectionView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) RETableViewManager *manager; // @synthesize manager=_manager;
@property(retain, nonatomic) IGroupDetailInfo *groupDetailInfo; // @synthesize groupDetailInfo=_groupDetailInfo;
@property(copy, nonatomic) NSString *groupId; // @synthesize groupId=_groupId;
- (void).cxx_destruct;
- (void)lookMoreUserBtn:(id)arg1;
- (void)join;
- (void)quit;
- (void)quitBtnClicked:(id)arg1;
- (void)deleteUser:(id)arg1 index:(long long)arg2;
- (void)deleteUserAlert:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)changeMyCard:(id)arg1;
- (void)changeGroupNotice:(id)arg1;
- (void)changeGroupName:(id)arg1;
- (void)changeChatTopInfo:(id)arg1;
- (void)changeChatTop:(id)arg1;
- (void)changeNotDisurbInfo:(id)arg1;
- (void)changeMsgDisturb:(id)arg1;
- (void)clearChatMessage;
- (void)clearChatMessageAlert;
- (void)searchChatHistory;
- (void)addTableViewCell;
- (void)addTableHeaderInfo;
- (void)updateUI;
- (void)loadData;
- (void)viewDidLoad;
- (void)initSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (id)title;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

