//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WLChatBaseViewController.h"

@class IFriendModel, IGroupDetailInfo, QMUIModalPresentationViewController;

@interface ChatRoomViewController : WLChatBaseViewController
{
    _Bool _isGameGroup;
    _Bool _isGotoNextVC;
    _Bool _isFirstIn;
    QMUIModalPresentationViewController *_packetModalViewController;
    QMUIModalPresentationViewController *_payModalViewController;
    IGroupDetailInfo *_groupDetailInfo;
    IFriendModel *_friendModel;
}

@property(nonatomic) _Bool isFirstIn; // @synthesize isFirstIn=_isFirstIn;
@property(nonatomic) _Bool isGotoNextVC; // @synthesize isGotoNextVC=_isGotoNextVC;
@property(retain, nonatomic) IFriendModel *friendModel; // @synthesize friendModel=_friendModel;
@property(retain, nonatomic) IGroupDetailInfo *groupDetailInfo; // @synthesize groupDetailInfo=_groupDetailInfo;
@property(retain, nonatomic) QMUIModalPresentationViewController *payModalViewController; // @synthesize payModalViewController=_payModalViewController;
@property(retain, nonatomic) QMUIModalPresentationViewController *packetModalViewController; // @synthesize packetModalViewController=_packetModalViewController;
@property(nonatomic) _Bool isGameGroup; // @synthesize isGameGroup=_isGameGroup;
- (void).cxx_destruct;
- (void)lookRedPacketHistory:(id)arg1;
- (void)showOpenPacket:(id)arg1;
- (void)showPacketGrabEnd:(id)arg1 redpack_id:(id)arg2;
- (void)goToSendRedPacketView;
- (void)redPacketClicked:(id)arg1;
- (void)showAlertToSendRedPacket;
- (void)wallentBtnClicked:(id)arg1;
- (void)rightBtnItemClicked;
- (void)toUserChatDetailInfo;
- (void)toGroupDetailInfo;
- (void)didTapCellPortrait:(id)arg1;
- (void)sendGetRedPacketImMessage:(id)arg1 drawName:(id)arg2;
- (void)updateDataChangeUI;
- (void)turnToRechargeView;
- (void)rechargeBtnClicked;
- (void)openRedPacketClicked:(id)arg1;
- (void)didTapMessageCell:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)loadUI;
- (void)loadGroupInfo;
- (void)loadFriendData;
- (void)loadData;
- (void)getHistoryMessage;
- (void)joinGroup;
- (void)quitGroup;
- (void)delete10MinuteMessageHistory;
- (void)viewDidLoad;
- (void)clearRCMessagesWithRedPacket;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)title;

@end

