//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCConversationListViewController.h"

#import "RCDSearchViewDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, QMUINavigationController, QMUIPopupMenuView, QMUISearchBar, QMUISearchController, UIView;

@interface ChatListViewController : RCConversationListViewController <UISearchBarDelegate, RCDSearchViewDelegate>
{
    QMUINavigationController *_searchNavigationController;
    UIView *_headerView;
    QMUISearchBar *_searchBar;
    NSArray *_keywords;
    NSMutableArray *_searchResultsKeywords;
    QMUISearchController *_mySearchController;
    QMUIPopupMenuView *_popupByWindow;
}

@property(retain, nonatomic) QMUIPopupMenuView *popupByWindow; // @synthesize popupByWindow=_popupByWindow;
@property(retain, nonatomic) QMUISearchController *mySearchController; // @synthesize mySearchController=_mySearchController;
@property(retain, nonatomic) NSMutableArray *searchResultsKeywords; // @synthesize searchResultsKeywords=_searchResultsKeywords;
@property(retain, nonatomic) NSArray *keywords; // @synthesize keywords=_keywords;
@property(retain, nonatomic) QMUISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) QMUINavigationController *searchNavigationController; // @synthesize searchNavigationController=_searchNavigationController;
- (void).cxx_destruct;
- (void)createGroup;
- (void)searchFriendToAdd;
- (void)leftBtnItemClicked;
- (void)rightBtnItemClicked;
- (void)onSelectedTableRow:(unsigned long long)arg1 conversationModel:(id)arg2 atIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)willDisplayConversationTableCell:(id)arg1 atIndexPath:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)onSearchCancelClick;
- (void)didSelectChatModel:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (id)init;
- (id)title;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

