//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DaiDodgeKeyboard : NSObject
{
}

+ (void)removeRegisterTheViewNeedDodgeKeyboard;
+ (void)addRegisterTheViewNeedDodgeKeyboard:(id)arg1;
+ (void)removeObservers;
+ (void)addObservers;
+ (void)keyboardWillHide:(id)arg1;
+ (void)keyboardWillShow:(id)arg1;
+ (id)objects;
+ (struct CGRect)currentFirstResponderFrame:(id)arg1;
+ (struct CGRect)currentKeyboardFrame;
+ (void)dodgeNewView:(id)arg1;
+ (void)dodgeKeyboardAnimation;
+ (void)changeFirstResponder:(id)arg1;

@end

