//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class DCCycleScrollViewFlowLayout, NSArray, NSString, NSTimer, UICollectionView, UIImage, UIImageView, UIPageControl;
@protocol DCCycleScrollViewDelegate;

@interface DCCycleScrollView : UIView <UICollectionViewDataSource, UICollectionViewDelegate>
{
    float _oldPoint;
    long long _dragDirection;
    _Bool _infiniteLoop;
    _Bool _autoScroll;
    _Bool _isZoom;
    NSArray *_imageDataArray;
    double _autoScrollTimeInterval;
    double _itemWidth;
    double _itemSpace;
    double _imgCornerRadius;
    UIPageControl *_pageControl;
    UIImage *_placeholderImage;
    UIImage *_cellPlaceholderImage;
    long long _bannerImageViewContentMode;
    id <DCCycleScrollViewDelegate> _delegate;
    UIImageView *_backgroundImageView;
    DCCycleScrollViewFlowLayout *_flowLayout;
    UICollectionView *_collectionView;
    NSArray *_imgArr;
    long long _totalItems;
    NSTimer *_timer;
    unsigned long long _currentpage;
}

+ (id)cycleScrollViewWithFrame:(struct CGRect)arg1 shouldInfiniteLoop:(_Bool)arg2 imageGroups:(id)arg3;
@property(nonatomic) unsigned long long currentpage; // @synthesize currentpage=_currentpage;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) long long totalItems; // @synthesize totalItems=_totalItems;
@property(retain, nonatomic) NSArray *imgArr; // @synthesize imgArr=_imgArr;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) DCCycleScrollViewFlowLayout *flowLayout; // @synthesize flowLayout=_flowLayout;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(nonatomic) __weak id <DCCycleScrollViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long bannerImageViewContentMode; // @synthesize bannerImageViewContentMode=_bannerImageViewContentMode;
@property(retain, nonatomic) UIImage *cellPlaceholderImage; // @synthesize cellPlaceholderImage=_cellPlaceholderImage;
@property(retain, nonatomic) UIImage *placeholderImage; // @synthesize placeholderImage=_placeholderImage;
@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(nonatomic) double imgCornerRadius; // @synthesize imgCornerRadius=_imgCornerRadius;
@property(nonatomic) double itemSpace; // @synthesize itemSpace=_itemSpace;
@property(nonatomic) double itemWidth; // @synthesize itemWidth=_itemWidth;
@property(nonatomic) double autoScrollTimeInterval; // @synthesize autoScrollTimeInterval=_autoScrollTimeInterval;
@property(nonatomic) _Bool isZoom; // @synthesize isZoom=_isZoom;
@property(nonatomic) _Bool autoScroll; // @synthesize autoScroll=_autoScroll;
@property(nonatomic) _Bool infiniteLoop; // @synthesize infiniteLoop=_infiniteLoop;
@property(retain, nonatomic) NSArray *imageDataArray; // @synthesize imageDataArray=_imageDataArray;
- (void).cxx_destruct;
- (void)scrollToIndex:(long long)arg1;
- (long long)currentIndex;
- (void)automaticScroll;
- (void)invalidateTimer;
- (void)setupTimer;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (float)lastPointCurrentPoint:(int)arg1;
- (float)nextPointCurrentPoint:(int)arg1;
- (void)scrollViewWillBeginDecelerating:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)layoutSubviews;
- (double)defaultSpace;
- (void)initialization;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

