//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray;
@protocol DSectionIndexViewDataSource, DSectionIndexViewDelegate;

@interface DSectionIndexView : UIView
{
    double itemViewHeight;
    long long highlightedItemIndex;
    _Bool _isShowCallout;
    _Bool _calloutViewType;
    int _calloutDirection;
    id <DSectionIndexViewDataSource> _dataSource;
    id <DSectionIndexViewDelegate> _delegate;
    double _fixedItemHeight;
    double _calloutMargin;
    UIView *_backgroundView;
    UIView *_calloutView;
    NSMutableArray *_itemViewList;
}

@property(retain, nonatomic) NSMutableArray *itemViewList; // @synthesize itemViewList=_itemViewList;
@property(retain, nonatomic) UIView *calloutView; // @synthesize calloutView=_calloutView;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) double calloutMargin; // @synthesize calloutMargin=_calloutMargin;
@property(nonatomic) double fixedItemHeight; // @synthesize fixedItemHeight=_fixedItemHeight;
@property(nonatomic) _Bool calloutViewType; // @synthesize calloutViewType=_calloutViewType;
@property(nonatomic) _Bool isShowCallout; // @synthesize isShowCallout=_isShowCallout;
@property(nonatomic) int calloutDirection; // @synthesize calloutDirection=_calloutDirection;
@property(nonatomic) __weak id <DSectionIndexViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <DSectionIndexViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)unhighlightAllItems;
- (void)highlightItemForSection:(long long)arg1;
- (void)selectItemViewForSection:(long long)arg1;
- (void)reloadItemViews;
- (void)layoutItemViews;
- (void)layoutSubviews;
- (void)setBackgroundViewFrame;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

