//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface IFriendDetailInfoModel : NSObject
{
    NSString *_uid;
    NSNumber *_id_num;
    NSString *_nickname;
    NSString *_avatar;
    NSString *_remark;
    NSString *_gender;
    NSNumber *_is_friend;
    NSNumber *_is_me_add;
    NSString *_desc;
    NSString *_updates_image;
    NSString *_is_mute;
}

@property(copy, nonatomic) NSString *is_mute; // @synthesize is_mute=_is_mute;
@property(copy, nonatomic) NSString *updates_image; // @synthesize updates_image=_updates_image;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(copy, nonatomic) NSNumber *is_me_add; // @synthesize is_me_add=_is_me_add;
@property(copy, nonatomic) NSNumber *is_friend; // @synthesize is_friend=_is_friend;
@property(copy, nonatomic) NSString *gender; // @synthesize gender=_gender;
@property(copy, nonatomic) NSString *remark; // @synthesize remark=_remark;
@property(copy, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(copy, nonatomic) NSNumber *id_num; // @synthesize id_num=_id_num;
@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
- (void).cxx_destruct;
- (id)getLoginUserSex;
- (_Bool)modelCustomTransformFromDictionary:(id)arg1;

@end

