//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface IFriendModel : NSObject <NSCopying>
{
    NSString *_firstPinyin;
    NSString *_uid;
    NSString *_id_num;
    NSString *_mobile;
    NSString *_nickname;
    NSString *_avatar;
    NSString *_remark;
    NSString *_is_top;
    NSString *_not_disturb;
    NSString *_chat_image;
}

@property(copy, nonatomic) NSString *chat_image; // @synthesize chat_image=_chat_image;
@property(copy, nonatomic) NSString *not_disturb; // @synthesize not_disturb=_not_disturb;
@property(copy, nonatomic) NSString *is_top; // @synthesize is_top=_is_top;
@property(copy, nonatomic) NSString *remark; // @synthesize remark=_remark;
@property(copy, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(copy, nonatomic) NSString *mobile; // @synthesize mobile=_mobile;
@property(copy, nonatomic) NSString *id_num; // @synthesize id_num=_id_num;
@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(copy, nonatomic) NSString *firstPinyin; // @synthesize firstPinyin=_firstPinyin;
- (void).cxx_destruct;
- (_Bool)modelCustomTransformFromDictionary:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

