//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ITokenModel, NSString;

@interface ILoginUserModel : NSObject
{
    NSString *_uid;
    NSString *_username;
    NSString *_mobile;
    NSString *_password;
    NSString *_is_default_password;
    ITokenModel *_token;
}

+ (id)modelContainerPropertyGenericClass;
@property(retain, nonatomic) ITokenModel *token; // @synthesize token=_token;
@property(copy, nonatomic) NSString *is_default_password; // @synthesize is_default_password=_is_default_password;
@property(copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(copy, nonatomic) NSString *mobile; // @synthesize mobile=_mobile;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
- (void).cxx_destruct;
- (_Bool)modelCustomTransformFromDictionary:(id)arg1;

@end

