//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseModelClient.h"

@interface ImModelClient : BaseModelClient
{
}

+ (id)getMyImPacketGetMyRedpackRecordWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getMyImRedpackHistoryWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getImPacketGetRedpackWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getImRedpackHistoryWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)imPacketGrabPackWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)imGrabRedpackWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)imPacketSendPackWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)imSendRedpackWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)setImChatCancelIsTopWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)setImChatIsTopWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)setImChatCancelNotDisturbWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)setImChatNotDisturbWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getImChatInfoWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)deleteImFriendWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)saveImFriendRemarkWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getImFriendListWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)rejectImFriendRequestWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)acceptImFriendRequestWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getImFriendRequestListWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)sendImFriendRequestWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getImMemberInfoWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)searchAddFriendWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getImTokenWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;

@end

