//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMOBFDataModel-Protocol.h"

@class NSDate, NSString;
@protocol IMOBFDataModel;

@protocol IMOBFUser <IMOBFDataModel>
- (id <IMOBFDataModel>)customInfo;
- (NSString *)phoneZone;
- (NSString *)phone;
- (NSString *)resume;
- (long long)zipCode;
- (NSString *)address;
- (NSString *)email;
- (NSString *)signature;
- (id)city;
- (id)province;
- (id)country;
- (id)zodiac;
- (id)constellation;
- (long long)age;
- (NSDate *)birthday;
- (id)gender;
- (id <IMOBFDataModel>)avatars;
- (NSString *)nickname;
- (NSString *)avatar;
- (NSString *)uid;
- (NSString *)token;
@end

