//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface IMyRedPacketResultModel : NSObject
{
    NSString *_nickname;
    NSString *_avatar;
    NSString *_member_id;
    NSString *_total_num;
    NSString *_total_money;
    NSString *_pages;
    NSString *_count;
    NSArray *_list;
}

+ (id)modelContainerPropertyGenericClass;
@property(retain, nonatomic) NSArray *list; // @synthesize list=_list;
@property(copy, nonatomic) NSString *count; // @synthesize count=_count;
@property(copy, nonatomic) NSString *pages; // @synthesize pages=_pages;
@property(copy, nonatomic) NSString *total_money; // @synthesize total_money=_total_money;
@property(copy, nonatomic) NSString *total_num; // @synthesize total_num=_total_num;
@property(copy, nonatomic) NSString *member_id; // @synthesize member_id=_member_id;
@property(copy, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
- (void).cxx_destruct;

@end

