//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface IOfflineInfoModel : NSObject
{
    NSNumber *_infoId;
    NSString *_opening_bank;
    NSString *_payee;
    NSString *_bank_number;
}

@property(copy, nonatomic) NSString *bank_number; // @synthesize bank_number=_bank_number;
@property(copy, nonatomic) NSString *payee; // @synthesize payee=_payee;
@property(copy, nonatomic) NSString *opening_bank; // @synthesize opening_bank=_opening_bank;
@property(copy, nonatomic) NSNumber *infoId; // @synthesize infoId=_infoId;
- (void).cxx_destruct;
- (_Bool)modelCustomTransformFromDictionary:(id)arg1;

@end

