//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString;

@interface IPayChannelModel : NSObject
{
    NSNumber *_channelId;
    NSString *_title;
    NSArray *_money_list;
    long long _is_show;
}

+ (id)modelContainerPropertyGenericClass;
@property(nonatomic) long long is_show; // @synthesize is_show=_is_show;
@property(copy, nonatomic) NSArray *money_list; // @synthesize money_list=_money_list;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSNumber *channelId; // @synthesize channelId=_channelId;
- (void).cxx_destruct;
- (_Bool)modelCustomTransformFromDictionary:(id)arg1;

@end

