//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IPosterModel : NSObject
{
    NSString *_app_name;
    NSString *_app_qrcode;
    NSString *_app_logo;
}

@property(copy, nonatomic) NSString *app_logo; // @synthesize app_logo=_app_logo;
@property(copy, nonatomic) NSString *app_qrcode; // @synthesize app_qrcode=_app_qrcode;
@property(copy, nonatomic) NSString *app_name; // @synthesize app_name=_app_name;
- (void).cxx_destruct;

@end

