//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface IRechargeInfoModel : NSObject
{
    NSArray *_pay_list;
    NSArray *_pay_channel;
}

+ (id)modelContainerPropertyGenericClass;
@property(retain, nonatomic) NSArray *pay_channel; // @synthesize pay_channel=_pay_channel;
@property(retain, nonatomic) NSArray *pay_list; // @synthesize pay_list=_pay_list;
- (void).cxx_destruct;

@end

