//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString;

@interface IRecommendModel : NSObject
{
    NSString *_total_money;
    NSString *_today_total_money;
    NSString *_count;
    NSString *_page;
    NSNumber *_pages;
    NSArray *_list;
}

+ (id)modelContainerPropertyGenericClass;
@property(copy, nonatomic) NSArray *list; // @synthesize list=_list;
@property(copy, nonatomic) NSNumber *pages; // @synthesize pages=_pages;
@property(copy, nonatomic) NSString *page; // @synthesize page=_page;
@property(copy, nonatomic) NSString *count; // @synthesize count=_count;
@property(copy, nonatomic) NSString *today_total_money; // @synthesize today_total_money=_today_total_money;
@property(copy, nonatomic) NSString *total_money; // @synthesize total_money=_total_money;
- (void).cxx_destruct;
- (_Bool)modelCustomTransformFromDictionary:(id)arg1;

@end

