//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IRecommendInfoModel : NSObject
{
    NSString *_from_nickname;
    NSString *_total_money;
    NSString *_level;
    NSString *_add_time;
    NSString *_member_id;
    NSString *_member_pid;
    NSString *_nickname;
    NSString *_avatar;
    NSString *_distance;
    NSString *_num;
}

@property(copy, nonatomic) NSString *num; // @synthesize num=_num;
@property(copy, nonatomic) NSString *distance; // @synthesize distance=_distance;
@property(copy, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(copy, nonatomic) NSString *member_pid; // @synthesize member_pid=_member_pid;
@property(copy, nonatomic) NSString *member_id; // @synthesize member_id=_member_id;
@property(copy, nonatomic) NSString *add_time; // @synthesize add_time=_add_time;
@property(copy, nonatomic) NSString *level; // @synthesize level=_level;
@property(copy, nonatomic) NSString *total_money; // @synthesize total_money=_total_money;
@property(copy, nonatomic) NSString *from_nickname; // @synthesize from_nickname=_from_nickname;
- (void).cxx_destruct;

@end

