//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface IRedPacketModel : NSObject
{
    NSString *_redpack_id;
    NSString *_money;
    NSNumber *_is_thunder;
}

@property(copy, nonatomic) NSNumber *is_thunder; // @synthesize is_thunder=_is_thunder;
@property(copy, nonatomic) NSString *money; // @synthesize money=_money;
@property(copy, nonatomic) NSString *redpack_id; // @synthesize redpack_id=_redpack_id;
- (void).cxx_destruct;

@end

