//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IRedPacektMemberModel : NSObject
{
    NSString *_nickname;
    NSString *_avatar;
    NSString *_member_id;
    NSString *_money;
    NSString *_is_thunder;
    NSString *_is_ms;
    NSString *_is_optimum;
    NSString *_update_time;
}

@property(copy, nonatomic) NSString *update_time; // @synthesize update_time=_update_time;
@property(copy, nonatomic) NSString *is_optimum; // @synthesize is_optimum=_is_optimum;
@property(copy, nonatomic) NSString *is_ms; // @synthesize is_ms=_is_ms;
@property(copy, nonatomic) NSString *is_thunder; // @synthesize is_thunder=_is_thunder;
@property(copy, nonatomic) NSString *money; // @synthesize money=_money;
@property(copy, nonatomic) NSString *member_id; // @synthesize member_id=_member_id;
@property(copy, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
- (void).cxx_destruct;

@end

