//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ISignRecordModel : NSObject
{
    NSString *_total_money;
    NSString *_add_time;
}

@property(copy, nonatomic) NSString *add_time; // @synthesize add_time=_add_time;
@property(copy, nonatomic) NSString *total_money; // @synthesize total_money=_total_money;
- (void).cxx_destruct;

@end

