//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString;

@interface ISignInfoModel : NSObject
{
    NSNumber *_today_sign;
    NSNumber *_sign_num;
    NSString *_sign_reward_money;
    NSString *_money;
    NSArray *_sgin_list;
    NSArray *_sign_reward_record;
}

+ (id)modelContainerPropertyGenericClass;
@property(retain, nonatomic) NSArray *sign_reward_record; // @synthesize sign_reward_record=_sign_reward_record;
@property(retain, nonatomic) NSArray *sgin_list; // @synthesize sgin_list=_sgin_list;
@property(copy, nonatomic) NSString *money; // @synthesize money=_money;
@property(copy, nonatomic) NSString *sign_reward_money; // @synthesize sign_reward_money=_sign_reward_money;
@property(copy, nonatomic) NSNumber *sign_num; // @synthesize sign_num=_sign_num;
@property(copy, nonatomic) NSNumber *today_sign; // @synthesize today_sign=_today_sign;
- (void).cxx_destruct;

@end

