//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString;

@interface ISignRecordInfoModel : NSObject
{
    NSNumber *_list_rows;
    NSNumber *_pages;
    NSString *_page;
    NSString *_count;
    NSArray *_list;
}

+ (id)modelContainerPropertyGenericClass;
@property(retain, nonatomic) NSArray *list; // @synthesize list=_list;
@property(copy, nonatomic) NSString *count; // @synthesize count=_count;
@property(copy, nonatomic) NSString *page; // @synthesize page=_page;
@property(copy, nonatomic) NSNumber *pages; // @synthesize pages=_pages;
@property(copy, nonatomic) NSNumber *list_rows; // @synthesize list_rows=_list_rows;
- (void).cxx_destruct;

@end

