//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface IUserInfoModel : NSObject
{
    NSNumber *_uid;
    NSString *_userId;
    NSString *_mobile;
    NSString *_nickname;
    NSString *_realname;
    NSString *_avatar;
    NSString *_gender;
    NSString *_invite_code;
    NSString *_address;
    NSNumber *_is_enroller;
    NSString *_balance;
    NSNumber *_is_default_password;
    NSString *_is_secret_free;
    NSString *_customer_id;
    NSString *_customer_name;
    NSString *_customer_img;
    NSString *_total_commission;
    NSString *_video_url;
}

@property(copy, nonatomic) NSString *video_url; // @synthesize video_url=_video_url;
@property(copy, nonatomic) NSString *total_commission; // @synthesize total_commission=_total_commission;
@property(copy, nonatomic) NSString *customer_img; // @synthesize customer_img=_customer_img;
@property(copy, nonatomic) NSString *customer_name; // @synthesize customer_name=_customer_name;
@property(copy, nonatomic) NSString *customer_id; // @synthesize customer_id=_customer_id;
@property(copy, nonatomic) NSString *is_secret_free; // @synthesize is_secret_free=_is_secret_free;
@property(copy, nonatomic) NSNumber *is_default_password; // @synthesize is_default_password=_is_default_password;
@property(copy, nonatomic) NSString *balance; // @synthesize balance=_balance;
@property(copy, nonatomic) NSNumber *is_enroller; // @synthesize is_enroller=_is_enroller;
@property(copy, nonatomic) NSString *address; // @synthesize address=_address;
@property(copy, nonatomic) NSString *invite_code; // @synthesize invite_code=_invite_code;
@property(copy, nonatomic) NSString *gender; // @synthesize gender=_gender;
@property(copy, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(copy, nonatomic) NSString *realname; // @synthesize realname=_realname;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(copy, nonatomic) NSString *mobile; // @synthesize mobile=_mobile;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(copy, nonatomic) NSNumber *uid; // @synthesize uid=_uid;
- (void).cxx_destruct;
- (_Bool)modelCustomTransformFromDictionary:(id)arg1;

@end

