//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "CAAnimationDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSMutableArray, NSMutableSet, NSString, UIImageView, UILabel, UIPageControl, UIScrollView;
@protocol KSImageManager, KSPhotoBrowserDelegate;

@interface KSPhotoBrowser : UIViewController <UIScrollViewDelegate, UIViewControllerTransitioningDelegate, CAAnimationDelegate>
{
    struct CGPoint _startLocation;
    _Bool _isDidShow;
    _Bool _bounces;
    _Bool _presented;
    unsigned long long _dismissalStyle;
    unsigned long long _backgroundStyle;
    unsigned long long _pageindicatorStyle;
    unsigned long long _loadingStyle;
    id <KSPhotoBrowserDelegate> _delegate;
    UIScrollView *_scrollView;
    NSMutableArray *_photoItems;
    NSMutableSet *_reusableItemViews;
    NSMutableArray *_visibleItemViews;
    unsigned long long _currentPage;
    UIImageView *_backgroundView;
    UIPageControl *_pageControl;
    UILabel *_pageLabel;
    id <KSImageManager> _imageManager;
}

+ (void)setImageManagerClass:(Class)arg1;
+ (id)browserWithPhotoItems:(id)arg1 selectedIndex:(unsigned long long)arg2;
@property(retain, nonatomic) id <KSImageManager> imageManager; // @synthesize imageManager=_imageManager;
@property(nonatomic) _Bool presented; // @synthesize presented=_presented;
@property(retain, nonatomic) UILabel *pageLabel; // @synthesize pageLabel=_pageLabel;
@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) UIImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) unsigned long long currentPage; // @synthesize currentPage=_currentPage;
@property(retain, nonatomic) NSMutableArray *visibleItemViews; // @synthesize visibleItemViews=_visibleItemViews;
@property(retain, nonatomic) NSMutableSet *reusableItemViews; // @synthesize reusableItemViews=_reusableItemViews;
@property(retain, nonatomic) NSMutableArray *photoItems; // @synthesize photoItems=_photoItems;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak id <KSPhotoBrowserDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool bounces; // @synthesize bounces=_bounces;
@property(nonatomic) unsigned long long loadingStyle; // @synthesize loadingStyle=_loadingStyle;
@property(nonatomic) unsigned long long pageindicatorStyle; // @synthesize pageindicatorStyle=_pageindicatorStyle;
@property(nonatomic) unsigned long long backgroundStyle; // @synthesize backgroundStyle=_backgroundStyle;
@property(nonatomic) unsigned long long dismissalStyle; // @synthesize dismissalStyle=_dismissalStyle;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)showSlideCompletionAnimationFromPoint:(struct CGPoint)arg1;
- (void)showDismissalAnimation;
- (void)showRotationCompletionAnimationFromPoint:(struct CGPoint)arg1;
- (void)showCancellationAnimation;
- (void)didPan:(id)arg1;
- (void)didLongPress:(id)arg1;
- (void)didDoubleTap:(id)arg1;
- (void)didSingleTap:(id)arg1;
- (void)addGestureRecognizer;
- (void)handlePanBegin;
- (void)configPageLabelWithPage:(unsigned long long)arg1;
- (void)configPhotoView:(id)arg1 withItem:(id)arg2;
- (void)blurBackgroundWithImage:(id)arg1 animated:(_Bool)arg2;
- (id)screenshot;
- (void)performSlideWithPan:(id)arg1;
- (void)performScaleWithPan:(id)arg1;
- (void)performRotationWithPan:(id)arg1;
- (void)dismissAnimated:(_Bool)arg1;
- (void)configItemViews;
- (void)updateReusableItemViews;
- (id)dequeueReusableItemView;
- (id)photoViewForPage:(unsigned long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)setStatusBarHidden:(_Bool)arg1;
- (void)showFromCurrentViewController;
- (void)showFromViewController:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)updateSubviewsFrame;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;
- (id)initWithPhotoItems:(id)arg1 selectedIndex:(unsigned long long)arg2;
- (id)init;
- (_Bool)prefersHomeIndicatorAutoHidden;
- (void)saveToPhotosAlbumImage:(id)arg1;
- (void)extractQRcodeResultJump:(id)arg1;
- (void)sendFriendImage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

