//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class LGAlertView;

@interface LGAlertViewController : UIViewController
{
    LGAlertView *_alertView;
}

@property(retain, nonatomic) LGAlertView *alertView; // @synthesize alertView=_alertView;
- (void).cxx_destruct;
- (long long)preferredStatusBarStyle;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (id)initWithAlertView:(id)arg1 view:(id)arg2;

@end

