//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface LocalCityInfo : NSObject
{
    int _cityId;
    NSString *_cityName;
    struct BMKPoint _center;
    struct BMKRect _bound;
    long long _dataSize;
    int _cityType;
    NSMutableArray *_childCity;
}

@property(retain, nonatomic) NSMutableArray *childCity; // @synthesize childCity=_childCity;
@property(retain, nonatomic) NSString *cityName; // @synthesize cityName=_cityName;
@property(nonatomic) struct BMKRect bound; // @synthesize bound=_bound;
@property(nonatomic) struct BMKPoint center; // @synthesize center=_center;
@property(nonatomic) int cityType; // @synthesize cityType=_cityType;
@property(nonatomic) long long dataSize; // @synthesize dataSize=_dataSize;
@property(nonatomic) int cityId; // @synthesize cityId=_cityId;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

