//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseModelClient.h"

@interface LoginModuleClient : BaseModelClient
{
}

+ (id)saveForgetPwdWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getForgetPwdVcodeWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)loginByPwdWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)loginByVcodeWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getLoginVcodeWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)registWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getRegistVcodeWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getImageVcodeWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getUserTokenWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)refreshTokenWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;

@end

