//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QDCommonViewController.h"

@class LWLoginTextFieldView, UIButton, UIImageView;

@interface LoginViewController : QDCommonViewController
{
    UIImageView *_logoImageView;
    LWLoginTextFieldView *_phoneTxtView;
    LWLoginTextFieldView *_pwdTxtView;
    UIButton *_loginBtn;
    UIButton *_smsLoginBtn;
    UIButton *_forgetBtn;
}

@property(retain, nonatomic) UIButton *forgetBtn; // @synthesize forgetBtn=_forgetBtn;
@property(retain, nonatomic) UIButton *smsLoginBtn; // @synthesize smsLoginBtn=_smsLoginBtn;
@property(retain, nonatomic) UIButton *loginBtn; // @synthesize loginBtn=_loginBtn;
@property(retain, nonatomic) LWLoginTextFieldView *pwdTxtView; // @synthesize pwdTxtView=_pwdTxtView;
@property(retain, nonatomic) LWLoginTextFieldView *phoneTxtView; // @synthesize phoneTxtView=_phoneTxtView;
@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
- (void).cxx_destruct;
- (void)rightBarButtonItemClicked;
- (void)didForgetBtn:(id)arg1;
- (void)didSmsLoginBtn:(id)arg1;
- (void)didClickLoginBtn:(id)arg1;
- (void)addConstrainsForSubviews;
- (_Bool)shouldHideKeyboardWhenTouchInView:(id)arg1;
- (void)addSubviews;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)initSubviews;
- (id)titleViewTintColor;
- (id)navigationBarTintColor;
- (id)navigationBarShadowImage;
- (id)navigationBarBackgroundImage;
- (_Bool)shouldSetStatusBarStyleLight;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)title;

@end

