//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSString, QMUILabel, UITextField;

@interface LWCardTextView : UIView <UITextFieldDelegate>
{
    UITextField *_textField;
    NSString *_number;
    QMUILabel *_titleLabel;
    NSString *_currentFormattedText;
    NSString *_format;
    long long _type;
}

@property(nonatomic) long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *format; // @synthesize format=_format;
@property(copy, nonatomic) NSString *currentFormattedText; // @synthesize currentFormattedText=_currentFormattedText;
@property(retain, nonatomic) QMUILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSString *number; // @synthesize number=_number;
@property(retain, nonatomic) UITextField *textField; // @synthesize textField=_textField;
- (void).cxx_destruct;
- (void)setPlaceholder:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
@property(readonly, copy, nonatomic) NSString *unformattedText;
- (void)formatInput:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithType:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

