//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextField.h>

@class NSString, UIButton, UIColor, UIView;

@interface LWLoginTextField : UITextField
{
    _Bool _isChangeBorder;
    int _maxTextLength;
    NSString *_leftIconNameStr;
    NSString *_leftHighlightedIconNameStr;
    UIView *_rightIconView;
    UIColor *_defaultBorderColor;
    double _defaultBorderWidth;
    UIColor *_selectBorderColor;
    UIColor *_placeholderColor;
    UIButton *_leftIconBtn;
    UIView *_customLeftView;
    UIView *_customRightView;
}

@property(retain, nonatomic) UIView *customRightView; // @synthesize customRightView=_customRightView;
@property(retain, nonatomic) UIView *customLeftView; // @synthesize customLeftView=_customLeftView;
@property(retain, nonatomic) UIButton *leftIconBtn; // @synthesize leftIconBtn=_leftIconBtn;
@property(nonatomic) int maxTextLength; // @synthesize maxTextLength=_maxTextLength;
@property(copy, nonatomic) UIColor *placeholderColor; // @synthesize placeholderColor=_placeholderColor;
@property(copy, nonatomic) UIColor *selectBorderColor; // @synthesize selectBorderColor=_selectBorderColor;
@property(nonatomic) double defaultBorderWidth; // @synthesize defaultBorderWidth=_defaultBorderWidth;
@property(copy, nonatomic) UIColor *defaultBorderColor; // @synthesize defaultBorderColor=_defaultBorderColor;
@property(nonatomic) _Bool isChangeBorder; // @synthesize isChangeBorder=_isChangeBorder;
@property(retain, nonatomic) UIView *rightIconView; // @synthesize rightIconView=_rightIconView;
@property(copy, nonatomic) NSString *leftHighlightedIconNameStr; // @synthesize leftHighlightedIconNameStr=_leftHighlightedIconNameStr;
@property(copy, nonatomic) NSString *leftIconNameStr; // @synthesize leftIconNameStr=_leftIconNameStr;
- (void).cxx_destruct;
- (void)dealloc;
- (void)addShakeAnimation;
- (void)judemaxText;
- (void)changBorderwithNote:(id)arg1;
- (void)setPlaceholder:(id)arg1;
- (void)textDidChange:(id)arg1;
- (void)textDidEndEditing:(id)arg1;
- (void)textBeginEditing:(id)arg1;
- (void)settingLeftIcon;
- (id)initWithFrame:(struct CGRect)arg1;

@end

