//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QMUIKit/QMUITabBarViewController.h>

@class UITabBarItem;

@interface MainViewController : QMUITabBarViewController
{
    UITabBarItem *_normalItem;
    UITabBarItem *_homeItem;
    UITabBarItem *_chatItem;
    UITabBarItem *_FriendItem;
    UITabBarItem *_meItem;
}

@property(nonatomic) __weak UITabBarItem *meItem; // @synthesize meItem=_meItem;
@property(nonatomic) __weak UITabBarItem *FriendItem; // @synthesize FriendItem=_FriendItem;
@property(nonatomic) __weak UITabBarItem *chatItem; // @synthesize chatItem=_chatItem;
@property(nonatomic) __weak UITabBarItem *homeItem; // @synthesize homeItem=_homeItem;
@property(nonatomic) __weak UITabBarItem *normalItem; // @synthesize normalItem=_normalItem;
- (void).cxx_destruct;
- (id)tabBarChildController:(Class)arg1 title:(id)arg2 imageName:(id)arg3 tag:(long long)arg4;
- (void)updataItembadge;
- (void)setupMainUI;
- (void)setupUIInfo;
- (void)updateNewFriendBadge;
- (void)upChatMessageBarItemBadge;
- (void)didReceiveMemoryWarning;
- (void)userLogout;
- (void)friendChat;
- (void)viewDidLoad;

@end

