//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SLCommonTableViewController.h"

#import "QMUITextViewDelegate-Protocol.h"
#import "YYTextViewDelegate-Protocol.h"

@class INoticeModel, NSArray, NSString, YYTextView;

@interface MessageNotifiDetailViewController : SLCommonTableViewController <QMUITextViewDelegate, YYTextViewDelegate>
{
    INoticeModel *_noticeModel;
    YYTextView *_textView;
    double _textViewMinimumHeight;
    NSArray *_datasource;
}

@property(retain, nonatomic) NSArray *datasource; // @synthesize datasource=_datasource;
@property(nonatomic) double textViewMinimumHeight; // @synthesize textViewMinimumHeight=_textViewMinimumHeight;
@property(retain, nonatomic) YYTextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) INoticeModel *noticeModel; // @synthesize noticeModel=_noticeModel;
- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (_Bool)textViewShouldReturn:(id)arg1;
- (void)textView:(id)arg1 didPreventTextChangeInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textView:(id)arg1 newHeightAfterTextChanged:(double)arg2;
- (void)updateInfo:(id)arg1;
- (void)intData;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)addViews;
- (void)initSubviews;
- (id)title;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

