//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SLCommonTableViewController.h"

@class INoticeInfoModel, NSArray;

@interface MessageNotifiListViewController : SLCommonTableViewController
{
    INoticeInfoModel *_noticeInfoModel;
    NSArray *_datasource;
}

@property(retain, nonatomic) NSArray *datasource; // @synthesize datasource=_datasource;
@property(retain, nonatomic) INoticeInfoModel *noticeInfoModel; // @synthesize noticeInfoModel=_noticeInfoModel;
- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)initData;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)initSubviews;
- (id)title;

@end

