//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SLCommonGroupListViewController.h"

#import "WKScriptMessageHandler-Protocol.h"

@class IPosterModel, IUserQrCodeModel, NSString, QMUIButton, QMUILabel, QMUIModalPresentationViewController, RETableViewItem, RETableViewManager, UIImage, UIImageView, UILabel, UIView, WKUserContentController, WKWebViewConfiguration;

@interface MeViewController : SLCommonGroupListViewController <WKScriptMessageHandler>
{
    QMUIModalPresentationViewController *modalViewController;
    RETableViewManager *_manager;
    UIView *_headerView;
    UIImageView *_logoImageView;
    QMUIButton *_nameBtn;
    UILabel *_idLabel;
    QMUILabel *_momeyLabel;
    QMUILabel *_commissionMomeyLabel;
    UIView *_qrUserCodeView;
    UIImage *_codeImage;
    UIImageView *_qrImageView;
    QMUILabel *_qrNameLabel;
    QMUILabel *_nickNameLabel;
    QMUILabel *_qrIdLabel;
    IUserQrCodeModel *_userQrCodeModel;
    IPosterModel *_posterModel;
    RETableViewItem *_commendItem;
    RETableViewItem *_cardItem;
    WKWebViewConfiguration *_configuration;
    WKUserContentController *_userContentController;
}

@property(retain, nonatomic) WKUserContentController *userContentController; // @synthesize userContentController=_userContentController;
@property(retain, nonatomic) WKWebViewConfiguration *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) RETableViewItem *cardItem; // @synthesize cardItem=_cardItem;
@property(retain, nonatomic) RETableViewItem *commendItem; // @synthesize commendItem=_commendItem;
@property(retain, nonatomic) IPosterModel *posterModel; // @synthesize posterModel=_posterModel;
@property(retain, nonatomic) IUserQrCodeModel *userQrCodeModel; // @synthesize userQrCodeModel=_userQrCodeModel;
@property(retain, nonatomic) QMUILabel *qrIdLabel; // @synthesize qrIdLabel=_qrIdLabel;
@property(retain, nonatomic) QMUILabel *nickNameLabel; // @synthesize nickNameLabel=_nickNameLabel;
@property(retain, nonatomic) QMUILabel *qrNameLabel; // @synthesize qrNameLabel=_qrNameLabel;
@property(retain, nonatomic) UIImageView *qrImageView; // @synthesize qrImageView=_qrImageView;
@property(retain, nonatomic) UIImage *codeImage; // @synthesize codeImage=_codeImage;
@property(retain, nonatomic) UIView *qrUserCodeView; // @synthesize qrUserCodeView=_qrUserCodeView;
@property(retain, nonatomic) QMUILabel *commissionMomeyLabel; // @synthesize commissionMomeyLabel=_commissionMomeyLabel;
@property(retain, nonatomic) QMUILabel *momeyLabel; // @synthesize momeyLabel=_momeyLabel;
@property(retain, nonatomic) UILabel *idLabel; // @synthesize idLabel=_idLabel;
@property(retain, nonatomic) QMUIButton *nameBtn; // @synthesize nameBtn=_nameBtn;
@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) RETableViewManager *manager; // @synthesize manager=_manager;
@property(retain, nonatomic) QMUIModalPresentationViewController *modalViewController; // @synthesize modalViewController;
- (void).cxx_destruct;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)saveImageToAlbum;
- (void)handleSaveButtonClick;
- (void)toUserInfoView:(id)arg1;
- (void)scanQrCodeBtnClickedBtn:(id)arg1;
- (void)saveImageBtnClickedBtn:(id)arg1;
- (void)updateVcodeUI;
- (void)getUserVcode;
- (void)nameBtnClicked:(id)arg1;
- (void)cashBtnClicked:(id)arg1;
- (void)rechargeBtnClicked:(id)arg1;
- (void)transferBtnClicked:(id)arg1;
- (void)turnToMyRecommendView;
- (void)infoBtnClicked:(id)arg1;
- (void)wallentClicked:(id)arg1;
- (void)beginPullDownRefreshingNew;
- (void)rightBarButtonItemClicked;
- (void)leftBarButtonItemClicked;
- (void)loadCityData;
- (id)titleViewTintColor;
- (id)navigationBarTintColor;
- (id)navigationBarShadowImage;
- (id)navigationBarBackgroundImage;
- (_Bool)shouldSetStatusBarStyleLight;
- (void)showSuccessAlert:(id)arg1;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (void)lottery:(id)arg1;
- (void)toPosterView;
- (void)poster:(id)arg1;
- (void)customerService;
- (void)addTableViewCell;
- (void)addNavBarItem;
- (void)addHeaderView;
- (void)reloadUI;
- (void)commissionTransfer;
- (void)getLoginUserInfo;
- (void)userLoginSuccess;
- (void)initSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)title;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

