//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;
@protocol MOBFLogServiceDelegate, OS_dispatch_queue;

@interface MOBFLogService : NSObject
{
    _Bool _sending;
    id <MOBFLogServiceDelegate> _delegate;
    NSString *_name;
    NSMutableArray *_logs;
    NSMutableArray *_tmpLogs;
    NSObject<OS_dispatch_queue> *_operationQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *operationQueue; // @synthesize operationQueue=_operationQueue;
@property _Bool sending; // @synthesize sending=_sending;
@property(retain, nonatomic) NSMutableArray *tmpLogs; // @synthesize tmpLogs=_tmpLogs;
@property(retain, nonatomic) NSMutableArray *logs; // @synthesize logs=_logs;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) __weak id <MOBFLogServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)_mergeEvents;
- (void)_checkNeedsSend;
- (void)needsSendLog;
- (void)writeData:(id)arg1;
- (id)initWithName:(id)arg1;

@end

