//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MOBFDataModel.h"

#import "IMOBFUser-Protocol.h"

@class NSString;

@interface MOBFUser : MOBFDataModel <IMOBFUser>
{
    NSString *_uid;
    NSString *_avatar;
    NSString *_nickname;
}

+ (id)anonymousUser;
+ (id)userWithUid:(id)arg1 avatar:(id)arg2 nickname:(id)arg3;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(copy, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
- (void).cxx_destruct;
- (id)customInfo;
- (id)phoneZone;
- (id)phone;
- (id)resume;
- (long long)zipCode;
- (id)address;
- (id)email;
- (id)signature;
- (id)city;
- (id)province;
- (id)country;
- (id)zodiac;
- (id)constellation;
- (long long)age;
- (id)birthday;
- (id)gender;
- (id)avatars;
- (id)token;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

