//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SLCommonGroupListViewController.h"

@class RETableViewItem, RETableViewManager, UIImage;

@interface MyInfoViewController : SLCommonGroupListViewController
{
    RETableViewManager *_manager;
    UIImage *_selectedAvatarImage;
    RETableViewItem *_nickNameItem;
    RETableViewItem *_realNameItem;
}

@property(retain, nonatomic) RETableViewItem *realNameItem; // @synthesize realNameItem=_realNameItem;
@property(retain, nonatomic) RETableViewItem *nickNameItem; // @synthesize nickNameItem=_nickNameItem;
@property(retain, nonatomic) UIImage *selectedAvatarImage; // @synthesize selectedAvatarImage=_selectedAvatarImage;
@property(retain, nonatomic) RETableViewManager *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (void)realNameChanged;
- (void)nickNameChanged;
- (void)changeSex:(id)arg1 sex:(id)arg2;
- (void)selectSex:(id)arg1;
- (void)changeAddress:(id)arg1 province:(id)arg2 city:(id)arg3;
- (void)selectAddress:(id)arg1;
- (void)loadCityData;
- (void)changeUserRealName:(id)arg1;
- (void)changeUserNickName:(id)arg1;
- (void)addTableViewCell;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)initSubviews;
- (id)title;

@end

