//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (WLAdd)
+ (id)wl_dataNamed:(id)arg1;
+ (id)wl_systemdataWithBase64EncodedString:(id)arg1;
+ (id)wl_dataWithBase64EncodedString:(id)arg1;
+ (id)wl_dataWithHexString:(id)arg1;
- (id)wl_zlibDeflate;
- (id)wl_zlibInflate;
- (id)wl_gzipDeflate;
- (id)wl_gzipInflate;
- (id)wl_jsonValueDecoded;
- (id)wl_base64EncodedString;
- (id)wl_hexString;
- (id)wl_utf8String;
- (id)wl_base64DcodedString;
- (id)wl_decryptAES256Withkey:(id)arg1;
- (id)wl_encryptAESWithkey:(id)arg1;
- (id)wl_decryptAES256Value;
@end

