//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDecimalNumber.h>

@interface NSDecimalNumber (WLAdd)
- (id)stringFormatterDecimalNumberMultiplyingByPowerOf10:(short)arg1 fractionDigits:(unsigned long long)arg2;
- (id)stringFormatterDecimalNumberMultiplyingByPowerOf10:(short)arg1;
- (id)stringFormatterDecimalNumber;
- (id)stringIntegerFormmatter;
- (id)roundToScale:(short)arg1 mode:(unsigned long long)arg2;
@end

