//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (WLAdd)
+ (id)wl_dictionaryWithXML:(id)arg1;
+ (id)wl_dictionaryWithPlistString:(id)arg1;
+ (id)wl_dictionaryWithPlistData:(id)arg1;
- (id)wl_stringValueForKey:(id)arg1 default:(id)arg2;
- (id)wl_numverValueForKey:(id)arg1 default:(id)arg2;
- (unsigned long long)wl_unsignedIntegerValueForKey:(id)arg1 default:(unsigned long long)arg2;
- (long long)wl_integerValueForKey:(id)arg1 default:(long long)arg2;
- (double)wl_doubleValueForKey:(id)arg1 default:(double)arg2;
- (float)wl_floatValueForKey:(id)arg1 default:(float)arg2;
- (unsigned long long)wl_unsignedLongLongValueForKey:(id)arg1 default:(unsigned long long)arg2;
- (long long)wl_longLongValueForKey:(id)arg1 default:(long long)arg2;
- (unsigned long long)wl_unsignedLongValueForKey:(id)arg1 default:(unsigned long long)arg2;
- (long long)wl_longValueForKey:(id)arg1 default:(long long)arg2;
- (unsigned int)wl_unsignedIntValueForKey:(id)arg1 default:(unsigned int)arg2;
- (int)wl_intValueForKey:(id)arg1 default:(int)arg2;
- (unsigned short)wl_unsignedShortValueForKey:(id)arg1 default:(unsigned short)arg2;
- (short)wl_shortValueForKey:(id)arg1 default:(short)arg2;
- (unsigned char)wl_unsignedCharValueForKey:(id)arg1 default:(unsigned char)arg2;
- (BOOL)wl_charValueForKey:(id)arg1 default:(BOOL)arg2;
- (_Bool)wl_boolValueForKey:(id)arg1 default:(_Bool)arg2;
- (id)wl_jsonPrettyStringEncoded;
- (id)wl_jsonStringEncoded;
- (id)wl_entriesForKeys:(id)arg1;
- (_Bool)wl_containsObjectForKey:(id)arg1;
- (id)wl_allValuesSortedByKeys;
- (id)wl_allKeysSorted;
- (id)wl_plistString;
- (id)wl_plistData;
@end

