//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSFileManager.h>

@interface NSFileManager (WLAdd)
+ (double)wl_availableDiskSpace;
+ (_Bool)wl_addSkipBackupAttributeToFile:(id)arg1;
+ (id)wl_cachesPath;
+ (id)wl_cachesURL;
+ (id)wl_libraryPath;
+ (id)wl_libraryURL;
+ (id)wl_documentsPath;
+ (id)wl_documentsURL;
+ (id)wl_applicationSupportDirectory;
+ (id)wl_tempFolderPath;
+ (id)pathForDirectory:(unsigned long long)arg1;
+ (id)urlForDirectory:(unsigned long long)arg1;
@end

