//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableArray.h>

@interface NSMutableArray (WLAdd)
+ (id)wl_arrayWithPlistString:(id)arg1;
+ (id)wl_arrayWithPlistData:(id)arg1;
- (void)wl_shuffle;
- (void)wl_reverse;
- (void)wl_insertObjects:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)wl_prependObjects:(id)arg1;
- (void)wl_appendObjects:(id)arg1;
- (void)wl_prependObject:(id)arg1;
- (void)wl_appendObject:(id)arg1;
- (id)wl_popLastObject;
- (id)wl_popFirstObject;
- (void)wl_removeLastObject;
- (void)wl_removeFirstObject;
@end

