//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSObject (WLAddForKVO)
- (id)wl_allNSObjectObserverBlocks;
- (void)wl_removeObserverBlocks;
- (void)wl_removeObserverBlocksForKeyPath:(id)arg1;
- (void)wl_addObserverBlockForKeyPath:(id)arg1 block:(CDUnknownBlockType)arg2;
@end

