//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BMKKeyValue-Protocol.h"

@class NSString;

@interface NSObject (BMKKeyValue) <BMKKeyValue>
+ (id)bmk_keyValuesArrayWithObjectArray:(id)arg1 keys:(id)arg2 ignoredKeys:(id)arg3;
+ (id)bmk_objectArrayWithKeyValuesArray:(id)arg1;
+ (id)bmk_objectWithKeyValues:(id)arg1;
+ (void)load;
+ (_Bool)bmk_isReferenceReplacedKeyWhenCreatingKeyValues;
+ (void)bmk_referenceReplacedKeyWhenCreatingKeyValues:(_Bool)arg1;
+ (void)setBMK_error:(id)arg1;
+ (id)bmk_error;
- (id)bmk_JSONObject;
- (id)bmk_keyValuesWithKeys:(id)arg1 ignoredKeys:(id)arg2;
- (id)bmk_keyValues;
- (id)bmk_setKeyValues:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

