//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (WLAddForSize)
+ (id)wl_reverseString:(id)arg1;
- (struct CGSize)wl_sizeWithCustomFont:(id)arg1;
- (struct CGSize)wl_sizeWithFont:(id)arg1 constrainedToHeight:(double)arg2 lineSpacing:(double)arg3;
- (struct CGSize)wl_sizeWithFont:(id)arg1 constrainedToHeight:(double)arg2;
- (struct CGSize)wl_sizeWithFont:(id)arg1 constrainedToWidth:(double)arg2 lineSpacing:(double)arg3;
- (struct CGSize)wl_sizeWithFont:(id)arg1 constrainedToWidth:(double)arg2;
- (double)wl_widthWithFont:(id)arg1 constrainedToHeight:(double)arg2 lineSpacing:(double)arg3;
- (double)wl_widthWithFont:(id)arg1 constrainedToHeight:(double)arg2;
- (double)wl_heightWithFont:(id)arg1 constrainedToWidth:(double)arg2 lineSpacing:(double)arg3;
- (double)wl_heightWithFont:(id)arg1 constrainedToWidth:(double)arg2;
@end

