//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (WLAddForRegex)
+ (_Bool)wl_accurateVerifyIDCardNumber:(id)arg1;
+ (id)chineseWithArabString:(id)arg1;
- (id)wl_stringByReplacingRegex:(id)arg1 options:(unsigned long long)arg2 withString:(id)arg3;
- (void)wl_enumerateRegexMatches:(id)arg1 options:(unsigned long long)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (_Bool)wl_matchesRegex:(id)arg1 options:(unsigned long long)arg2;
- (_Bool)wl_bankCardluhmCheck;
- (_Bool)wl_simpleVerifyIdentityCardNum;
- (_Bool)wl_isValidWithMinLenth:(long long)arg1 maxLenth:(long long)arg2 containChinese:(_Bool)arg3 containDigtal:(_Bool)arg4 containLetter:(_Bool)arg5 containOtherCharacter:(id)arg6 firstCannotBeDigtal:(_Bool)arg7;
- (_Bool)wl_isValidWithMinLenth:(long long)arg1 maxLenth:(long long)arg2 containChinese:(_Bool)arg3 firstCannotBeDigtal:(_Bool)arg4;
- (_Bool)wl_isValidTaxNo;
- (_Bool)wl_isValidPostalcode;
- (_Bool)wl_isValidChinese;
- (_Bool)wl_isMacAddress;
- (_Bool)wl_isIPAddress;
- (_Bool)wl_isCarNumber;
- (_Bool)wl_isValidUrl;
- (_Bool)wl_isEmailAddress;
- (_Bool)wl_isValidPassword;
- (_Bool)wl_isValidPhoneNumber;
- (_Bool)wl_isMobileNumber;
- (_Bool)wl_isMobileNumberClassification;
- (_Bool)wl_isValidateByRegex:(id)arg1;
@end

