//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SLCommonGroupListViewController.h"

@class IOfflineInfoModel, RETableViewItem, RETableViewManager, UITextField;

@interface OfflineRechargeViewController : SLCommonGroupListViewController
{
    _Bool _isHaveDian;
    RETableViewManager *_manager;
    UITextField *_nameTxtField;
    UITextField *_moneyTxtField;
    UITextField *_remarkTxtField;
    RETableViewItem *_payAmountItem;
    RETableViewItem *_titleItem;
    RETableViewItem *_bankNumItem;
    IOfflineInfoModel *_offlineInfoModel;
    long long _selectType;
}

@property(nonatomic) _Bool isHaveDian; // @synthesize isHaveDian=_isHaveDian;
@property(nonatomic) long long selectType; // @synthesize selectType=_selectType;
@property(retain, nonatomic) IOfflineInfoModel *offlineInfoModel; // @synthesize offlineInfoModel=_offlineInfoModel;
@property(retain, nonatomic) RETableViewItem *bankNumItem; // @synthesize bankNumItem=_bankNumItem;
@property(retain, nonatomic) RETableViewItem *titleItem; // @synthesize titleItem=_titleItem;
@property(retain, nonatomic) RETableViewItem *payAmountItem; // @synthesize payAmountItem=_payAmountItem;
@property(retain, nonatomic) UITextField *remarkTxtField; // @synthesize remarkTxtField=_remarkTxtField;
@property(retain, nonatomic) UITextField *moneyTxtField; // @synthesize moneyTxtField=_moneyTxtField;
@property(retain, nonatomic) UITextField *nameTxtField; // @synthesize nameTxtField=_nameTxtField;
@property(retain, nonatomic) RETableViewManager *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (void)bankNumBtnClicked:(id)arg1;
- (void)payAmountBtnClicked:(id)arg1;
- (void)confirmBtnClicked:(id)arg1;
- (void)loadGetMoenyInfoUi;
- (void)initData;
- (void)addViews;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)shouldHideKeyboardWhenTouchInView:(id)arg1;
- (void)initSubviews;
- (id)title;
- (id)initWithStyle:(long long)arg1 selectType:(long long)arg2 offlineInfoModel:(id)arg3;

@end

