//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QDCommonViewController.h"

@class IPosterModel, QMUILabel, UIImageView;

@interface PosterViewController : QDCommonViewController
{
    IPosterModel *_posterModel;
    QMUILabel *_titleLabel;
    UIImageView *_logoImageView;
    UIImageView *_codeImageView;
}

@property(retain, nonatomic) UIImageView *codeImageView; // @synthesize codeImageView=_codeImageView;
@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
@property(retain, nonatomic) QMUILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) IPosterModel *posterModel; // @synthesize posterModel=_posterModel;
- (void).cxx_destruct;
- (void)updateUi;
- (void)getUserVcode;
- (void)addSubViews;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)initSubviews;
- (id)title;

@end

