//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface QDUIHelper : NSObject
{
}

+ (void)forceInterfaceOrientationPortrait;
+ (void)customMoreOperationAppearance;
+ (void)customAlertControllerAppearance;
+ (void)customDialogViewControllerAppearance;
+ (void)customEmotionViewAppearance;
+ (void)customImagePickerAppearance;
+ (id)tabBarItemWithTitle:(id)arg1 image:(id)arg2 selectedImage:(id)arg3 tag:(long long)arg4;
+ (id)generateLightBorderedButton;
+ (id)generateDarkFilledButton;
+ (void)updateEmotionImages;
+ (void)asyncLoadImages:(id)arg1;
+ (id)qmuiEmotions;
+ (void)showAlertWhenSavedPhotoFailureByPermissionDenied;
+ (id)humanReadableFileSize:(long long)arg1;
+ (id)navigationBarBackgroundImageWithThemeColor:(id)arg1;

@end

