//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCCustomIOSAlertView.h"

#import "RCCustomIOSAlertViewDelegate-Protocol.h"

@class NSArray, NSString, UILabel;
@protocol RCAdminEvaluationViewDelegate;

@interface RCAdminEvaluationView : RCCustomIOSAlertView <RCCustomIOSAlertViewDelegate>
{
    _Bool _quitAfterEvaluation;
    int _starValue;
    NSString *_dialogId;
    id <RCAdminEvaluationViewDelegate> _adminEvaluationViewDelegate;
    NSArray *_starButtonArray;
    UILabel *_titleLabel;
}

@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSArray *starButtonArray; // @synthesize starButtonArray=_starButtonArray;
@property(nonatomic) int starValue; // @synthesize starValue=_starValue;
@property(nonatomic) __weak id <RCAdminEvaluationViewDelegate> adminEvaluationViewDelegate; // @synthesize adminEvaluationViewDelegate=_adminEvaluationViewDelegate;
@property(retain, nonatomic) NSString *dialogId; // @synthesize dialogId=_dialogId;
@property(nonatomic) _Bool quitAfterEvaluation; // @synthesize quitAfterEvaluation=_quitAfterEvaluation;
- (void).cxx_destruct;
- (void)customIOS7dialogButtonTouchUpInside:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)createDemoView;
- (void)onStarButton:(id)arg1;
- (id)starAtIndex:(int)arg1;
- (id)initWithDelegate:(id)arg1;

@end

