//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PHPhotoLibraryChangeObserver-Protocol.h"

@class ALAssetsLibrary, NSMutableArray, NSString;

@interface RCAssetHelper : NSObject <PHPhotoLibraryChangeObserver>
{
    ALAssetsLibrary *_assetLibrary;
    NSMutableArray *_assetsGroups;
}

+ (id)shareAssetHelper;
@property(retain, nonatomic) NSMutableArray *assetsGroups; // @synthesize assetsGroups=_assetsGroups;
@property(retain, nonatomic) ALAssetsLibrary *assetLibrary; // @synthesize assetLibrary=_assetLibrary;
- (void).cxx_destruct;
- (void)dealloc;
- (id)exchangeImageDataType:(id)arg1 imageData:(id)arg2;
- (id)getAssetIdentifier:(id)arg1;
- (void)photoLibraryDidChange:(id)arg1;
- (int)getAssetDataSizeWithAsset:(id)arg1 result:(CDUnknownBlockType)arg2;
- (int)getOriginImageDataWithAsset:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)getPreviewWithAsset:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)getThumbnailWithAsset:(id)arg1 size:(struct CGSize)arg2 result:(CDUnknownBlockType)arg3;
- (void)getPhotosOfGroup:(id)arg1 results:(CDUnknownBlockType)arg2;
- (id)getCachePhotoGroups;
- (void)getGroupsWithALAssetsGroupType:(unsigned long long)arg1 resultCompletion:(CDUnknownBlockType)arg2;
- (void)getAlbumsFromSystem:(CDUnknownBlockType)arg1 groupType:(unsigned long long)arg2;
- (_Bool)hasAuthorizationStatusAuthorized;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

