//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, UIImage;

@interface RCAssetModel : NSObject
{
    _Bool _isSelect;
    int _imageRequestID;
    id _asset;
    UIImage *_thumbnailImage;
    UIImage *_previewImage;
    NSData *_originImageData;
    double _imageSize;
    long long _imageOrientation;
    long long _index;
}

+ (id)modelWithAsset:(id)arg1;
@property(nonatomic) int imageRequestID; // @synthesize imageRequestID=_imageRequestID;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(nonatomic) _Bool isSelect; // @synthesize isSelect=_isSelect;
@property(nonatomic) long long imageOrientation; // @synthesize imageOrientation=_imageOrientation;
@property(nonatomic) double imageSize; // @synthesize imageSize=_imageSize;
@property(retain, nonatomic) NSData *originImageData; // @synthesize originImageData=_originImageData;
@property(retain, nonatomic) UIImage *previewImage; // @synthesize previewImage=_previewImage;
@property(retain, nonatomic) UIImage *thumbnailImage; // @synthesize thumbnailImage=_thumbnailImage;
@property(retain, nonatomic) id asset; // @synthesize asset=_asset;
- (void).cxx_destruct;
- (int)fetchBigImage;
- (void)setValue:(id)arg1 forKey:(id)arg2;

@end

