//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "RCConversationSettingTableViewHeaderDelegate-Protocol.h"

@class NSArray, NSString, RCConversationSettingTableViewCell, RCConversationSettingTableViewHeader, UIView;

@interface RCConversationSettingTableViewController : UITableViewController <RCConversationSettingTableViewHeaderDelegate>
{
    _Bool _headerHidden;
    _Bool _switch_isTop;
    _Bool _switch_newMessageNotify;
    NSArray *_users;
    RCConversationSettingTableViewHeader *_header;
    UIView *_headerView;
    RCConversationSettingTableViewCell *_cell_isTop;
    RCConversationSettingTableViewCell *_cell_newMessageNotify;
}

@property(retain, nonatomic) RCConversationSettingTableViewCell *cell_newMessageNotify; // @synthesize cell_newMessageNotify=_cell_newMessageNotify;
@property(retain, nonatomic) RCConversationSettingTableViewCell *cell_isTop; // @synthesize cell_isTop=_cell_isTop;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) RCConversationSettingTableViewHeader *header; // @synthesize header=_header;
@property(retain, nonatomic) NSArray *users; // @synthesize users=_users;
@property(nonatomic) _Bool switch_newMessageNotify; // @synthesize switch_newMessageNotify=_switch_newMessageNotify;
@property(nonatomic) _Bool switch_isTop; // @synthesize switch_isTop=_switch_isTop;
@property(nonatomic) _Bool headerHidden; // @synthesize headerHidden=_headerHidden;
- (void).cxx_destruct;
- (void)dealloc;
- (void)didTipHeaderClicked:(id)arg1;
- (void)deleteTipButtonClicked:(id)arg1;
- (void)settingTableViewHeader:(id)arg1 indexPathOfSelectedItem:(id)arg2 allTheSeletedUsers:(id)arg3;
- (void)onClickClearMessageHistory:(id)arg1;
- (void)onClickNewMessageNotificationSwitch:(id)arg1;
- (void)onClickIsTopSwitch:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)orientChange:(id)arg1;
@property(readonly, nonatomic) NSArray *defaultCells;
- (void)disableInviteMemberEvent:(_Bool)arg1;
- (void)disableDeleteMemberEvent:(_Bool)arg1;
- (void)inviteRemoteUsers:(id)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

