//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class RCMessageBubbleTipView, RCloudImageView;

@interface RCConversationHeaderView : UIView
{
    RCloudImageView *_headerImageView;
    long long _headerImageStyle;
    RCMessageBubbleTipView *_bubbleView;
    UIView *_backgroundView;
}

@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) RCMessageBubbleTipView *bubbleView; // @synthesize bubbleView=_bubbleView;
@property(nonatomic) long long headerImageStyle; // @synthesize headerImageStyle=_headerImageStyle;
@property(retain, nonatomic) RCloudImageView *headerImageView; // @synthesize headerImageView=_headerImageView;
- (void).cxx_destruct;
- (void)resetDefaultLayout:(id)arg1;
- (void)updateBubbleUnreadNumber:(int)arg1;
- (void)initSubviewsLayout;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

