//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSString, UIImageView, UILabel;

@interface RCConversationDetailContentView : UIView
{
    UILabel *_hightlineLabel;
    UIImageView *_sentStatusView;
    UILabel *_messageContentLabel;
    NSArray *_constraints;
    NSString *_prefixName;
}

@property(retain, nonatomic) NSString *prefixName; // @synthesize prefixName=_prefixName;
@property(retain, nonatomic) NSArray *constraints; // @synthesize constraints=_constraints;
@property(retain, nonatomic) UILabel *messageContentLabel; // @synthesize messageContentLabel=_messageContentLabel;
@property(retain, nonatomic) UIImageView *sentStatusView; // @synthesize sentStatusView=_sentStatusView;
@property(retain, nonatomic) UILabel *hightlineLabel; // @synthesize hightlineLabel=_hightlineLabel;
- (void).cxx_destruct;
- (double)getLeftViewWidth;
- (void)resetDefaultLayout:(id)arg1;
- (id)getOneLineString:(id)arg1;
- (id)formatMessageContent:(id)arg1;
- (void)updateLayout;
- (void)updateContent:(id)arg1;
- (void)updateContent:(id)arg1 prefixName:(id)arg2;
- (void)initSubviewsLayout;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

