//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UILabel, UISwitch;

@interface RCConversationSettingTableViewCell : UITableViewCell
{
    UISwitch *_swich;
    UILabel *_label;
}

@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UISwitch *swich; // @synthesize swich=_swich;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

