//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class NSString, RCloudImageView, UIButton, UILabel;
@protocol RCConversationSettingTableViewHeaderItemDelegate;

@interface RCConversationSettingTableViewHeaderItem : UICollectionViewCell
{
    RCloudImageView *_ivAva;
    UILabel *_titleLabel;
    UIButton *_btnImg;
    NSString *_userId;
    id <RCConversationSettingTableViewHeaderItemDelegate> _delegate;
}

@property(nonatomic) __weak id <RCConversationSettingTableViewHeaderItemDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(retain, nonatomic) UIButton *btnImg; // @synthesize btnImg=_btnImg;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) RCloudImageView *ivAva; // @synthesize ivAva=_ivAva;
- (void).cxx_destruct;
- (void)deleteItem:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

