//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIImage;

@interface RCCSStarView : UIView
{
    int _starValue;
    CDUnknownBlockType _starEvaluateBlock;
    UIImage *_defaultImage;
    UIImage *_lightImage;
    NSArray *_starButtonArray;
}

@property(retain, nonatomic) NSArray *starButtonArray; // @synthesize starButtonArray=_starButtonArray;
@property(nonatomic) int starValue; // @synthesize starValue=_starValue;
@property(retain, nonatomic) UIImage *lightImage; // @synthesize lightImage=_lightImage;
@property(retain, nonatomic) UIImage *defaultImage; // @synthesize defaultImage=_defaultImage;
@property(copy, nonatomic) CDUnknownBlockType starEvaluateBlock; // @synthesize starEvaluateBlock=_starEvaluateBlock;
- (void).cxx_destruct;
- (void)starTapBtn:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 starIndex:(long long)arg2 starWidth:(double)arg3 space:(double)arg4 defaultImage:(id)arg5 lightImage:(id)arg6 isCanTap:(_Bool)arg7;

@end

