//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCCustomIOSAlertView.h"

#import "RCCustomIOSAlertViewDelegate-Protocol.h"

@class UILabel;
@protocol RCCSAlertViewDelegate;

@interface RCCSAlertView : RCCustomIOSAlertView <RCCustomIOSAlertViewDelegate>
{
    id <RCCSAlertViewDelegate> _csAlertViewDelegate;
    UILabel *_titleLabel;
    UILabel *_contentLabel;
}

@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <RCCSAlertViewDelegate> csAlertViewDelegate; // @synthesize csAlertViewDelegate=_csAlertViewDelegate;
- (void).cxx_destruct;
- (void)customIOS7dialogButtonTouchUpInside:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)createDemoView;
- (id)initWithTitle:(id)arg1 warning:(id)arg2 delegate:(id)arg3;

@end

