//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class NSArray, NSMutableDictionary, NSString;

@interface RCCSLeaveMessageController : UITableViewController
{
    NSArray *_leaveMessageConfig;
    NSString *_targetId;
    unsigned long long _conversationType;
    CDUnknownBlockType _leaveMessageSuccess;
    NSMutableDictionary *_leaveMessageInfoDic;
}

@property(retain, nonatomic) NSMutableDictionary *leaveMessageInfoDic; // @synthesize leaveMessageInfoDic=_leaveMessageInfoDic;
@property(copy, nonatomic) CDUnknownBlockType leaveMessageSuccess; // @synthesize leaveMessageSuccess=_leaveMessageSuccess;
@property(nonatomic) unsigned long long conversationType; // @synthesize conversationType=_conversationType;
@property(retain, nonatomic) NSString *targetId; // @synthesize targetId=_targetId;
@property(retain, nonatomic) NSArray *leaveMessageConfig; // @synthesize leaveMessageConfig=_leaveMessageConfig;
- (void).cxx_destruct;
- (void)showAlertView:(id)arg1;
- (void)submitSuggestAction;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)setupTableFooterView;
- (void)setupTableHeaderView;
- (void)cancelAction;
- (void)setBackAction;
- (void)viewDidLoad;

@end

