//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCMessageContent.h"

@class NSDictionary, NSString;

@interface RCCSEvaluateMessage : RCMessageContent
{
    int _source;
    int _resolveStatus;
    int _type;
    NSString *_uid;
    NSString *_cid;
    NSString *_pid;
    NSString *_suggest;
    NSString *_tagText;
    NSDictionary *_extra;
}

+ (id)getObjectName;
+ (unsigned long long)persistentFlag;
@property(retain, nonatomic) NSDictionary *extra; // @synthesize extra=_extra;
@property(copy, nonatomic) NSString *tagText; // @synthesize tagText=_tagText;
@property(nonatomic) int type; // @synthesize type=_type;
@property(nonatomic) int resolveStatus; // @synthesize resolveStatus=_resolveStatus;
@property(retain, nonatomic) NSString *suggest; // @synthesize suggest=_suggest;
@property(nonatomic) int source; // @synthesize source=_source;
@property(retain, nonatomic) NSString *pid; // @synthesize pid=_pid;
@property(retain, nonatomic) NSString *cid; // @synthesize cid=_cid;
@property(retain, nonatomic) NSString *uid; // @synthesize uid=_uid;
- (void).cxx_destruct;
- (void)decodeWithData:(id)arg1;
- (id)encode;

@end

