//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface RCCustomerServiceSession : NSObject
{
    _Bool _isQuited;
    _Bool _suspendWhenQuit;
    _Bool _reportResolveStatus;
    int _type;
    NSString *_uid;
    NSString *_cid;
    NSString *_pid;
    NSArray *_groupList;
    NSString *_robotName;
    NSString *_robotLogo;
    NSString *_robotHelloWord;
    CDUnknownBlockType _modeTypeBlock;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _errorBlock;
    CDUnknownBlockType _pullEvaluationBlock;
    CDUnknownBlockType _selectGroupBlock;
    CDUnknownBlockType _quitBlock;
    CDUnknownBlockType _evaConfigBlock;
}

@property(copy, nonatomic) CDUnknownBlockType evaConfigBlock; // @synthesize evaConfigBlock=_evaConfigBlock;
@property(copy, nonatomic) CDUnknownBlockType quitBlock; // @synthesize quitBlock=_quitBlock;
@property(copy, nonatomic) CDUnknownBlockType selectGroupBlock; // @synthesize selectGroupBlock=_selectGroupBlock;
@property(copy, nonatomic) CDUnknownBlockType pullEvaluationBlock; // @synthesize pullEvaluationBlock=_pullEvaluationBlock;
@property(copy, nonatomic) CDUnknownBlockType errorBlock; // @synthesize errorBlock=_errorBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(copy, nonatomic) CDUnknownBlockType modeTypeBlock; // @synthesize modeTypeBlock=_modeTypeBlock;
@property(retain, nonatomic) NSString *robotHelloWord; // @synthesize robotHelloWord=_robotHelloWord;
@property(retain, nonatomic) NSString *robotLogo; // @synthesize robotLogo=_robotLogo;
@property(retain, nonatomic) NSString *robotName; // @synthesize robotName=_robotName;
@property(nonatomic) int type; // @synthesize type=_type;
@property(nonatomic) _Bool reportResolveStatus; // @synthesize reportResolveStatus=_reportResolveStatus;
@property(retain, nonatomic) NSArray *groupList; // @synthesize groupList=_groupList;
@property(nonatomic) _Bool suspendWhenQuit; // @synthesize suspendWhenQuit=_suspendWhenQuit;
@property(nonatomic) _Bool isQuited; // @synthesize isQuited=_isQuited;
@property(retain, nonatomic) NSString *pid; // @synthesize pid=_pid;
@property(retain, nonatomic) NSString *cid; // @synthesize cid=_cid;
@property(retain, nonatomic) NSString *uid; // @synthesize uid=_uid;
- (void).cxx_destruct;

@end

