//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface RCCustomerServiceConfig : NSObject
{
    _Bool _isBlack;
    _Bool _robotSessionNoEva;
    _Bool _humanSessionNoEva;
    int _adminTipTime;
    int _userTipTime;
    int _reportResolveStatus;
    int _disableLocation;
    NSString *_companyName;
    NSString *_companyUrl;
    NSArray *_humanEvaluateItems;
    NSString *_adminTipWord;
    NSString *_userTipWord;
    unsigned long long _evaEntryPoint;
    unsigned long long _evaType;
    unsigned long long _leaveMessageType;
    NSString *_leaveMessageWebUrl;
    NSArray *_leaveMessageNativeInfo;
    NSString *_announceMsg;
    NSString *_announceClickUrl;
}

@property(copy, nonatomic) NSString *announceClickUrl; // @synthesize announceClickUrl=_announceClickUrl;
@property(copy, nonatomic) NSString *announceMsg; // @synthesize announceMsg=_announceMsg;
@property(copy, nonatomic) NSArray *leaveMessageNativeInfo; // @synthesize leaveMessageNativeInfo=_leaveMessageNativeInfo;
@property(copy, nonatomic) NSString *leaveMessageWebUrl; // @synthesize leaveMessageWebUrl=_leaveMessageWebUrl;
@property(nonatomic) int disableLocation; // @synthesize disableLocation=_disableLocation;
@property(nonatomic) unsigned long long leaveMessageType; // @synthesize leaveMessageType=_leaveMessageType;
@property(nonatomic) int reportResolveStatus; // @synthesize reportResolveStatus=_reportResolveStatus;
@property(nonatomic) unsigned long long evaType; // @synthesize evaType=_evaType;
@property(nonatomic) unsigned long long evaEntryPoint; // @synthesize evaEntryPoint=_evaEntryPoint;
@property(retain, nonatomic) NSString *userTipWord; // @synthesize userTipWord=_userTipWord;
@property(nonatomic) int userTipTime; // @synthesize userTipTime=_userTipTime;
@property(retain, nonatomic) NSString *adminTipWord; // @synthesize adminTipWord=_adminTipWord;
@property(nonatomic) int adminTipTime; // @synthesize adminTipTime=_adminTipTime;
@property(retain, nonatomic) NSArray *humanEvaluateItems; // @synthesize humanEvaluateItems=_humanEvaluateItems;
@property(nonatomic) _Bool humanSessionNoEva; // @synthesize humanSessionNoEva=_humanSessionNoEva;
@property(nonatomic) _Bool robotSessionNoEva; // @synthesize robotSessionNoEva=_robotSessionNoEva;
@property(retain, nonatomic) NSString *companyUrl; // @synthesize companyUrl=_companyUrl;
@property(retain, nonatomic) NSString *companyName; // @synthesize companyName=_companyName;
@property(nonatomic) _Bool isBlack; // @synthesize isBlack=_isBlack;
- (void).cxx_destruct;

@end

