//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QDCommonViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSDate, NSMutableArray, NSMutableDictionary, NSString, QMUILabel, QMUISearchBar, UIButton, UITableView, UIView;
@protocol RCDSearchViewDelegate;

@interface RCDSearchViewController : QDCommonViewController <UISearchBarDelegate, UITableViewDelegate, UITableViewDataSource, UIGestureRecognizerDelegate, UINavigationControllerDelegate>
{
    id <RCDSearchViewDelegate> _delegate;
    NSMutableDictionary *_resultDictionary;
    NSMutableArray *_groupTypeArray;
    QMUISearchBar *_searchBars;
    UIButton *_cancelButton;
    UIView *_searchView;
    UITableView *_resultTableView;
    QMUILabel *_emptyLabel;
    UIView *_searchBackgroundView;
    NSDate *_searchDate;
    NSArray *_datasource;
}

@property(retain, nonatomic) NSArray *datasource; // @synthesize datasource=_datasource;
@property(retain, nonatomic) NSDate *searchDate; // @synthesize searchDate=_searchDate;
@property(retain, nonatomic) UIView *searchBackgroundView; // @synthesize searchBackgroundView=_searchBackgroundView;
@property(retain, nonatomic) QMUILabel *emptyLabel; // @synthesize emptyLabel=_emptyLabel;
@property(retain, nonatomic) UITableView *resultTableView; // @synthesize resultTableView=_resultTableView;
@property(retain, nonatomic) UIView *searchView; // @synthesize searchView=_searchView;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) QMUISearchBar *searchBars; // @synthesize searchBars=_searchBars;
@property(retain, nonatomic) NSMutableArray *groupTypeArray; // @synthesize groupTypeArray=_groupTypeArray;
@property(retain, nonatomic) NSMutableDictionary *resultDictionary; // @synthesize resultDictionary=_resultDictionary;
@property(nonatomic) __weak id <RCDSearchViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)hideSerchBarWhenTapBackground:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)cancelButtonClicked;
- (id)changeString:(id)arg1 appendStr:(id)arg2;
- (double)labelAdaptive:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)refreshSearchView:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)loadSearchView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

