//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface RCExtensionUtility : NSObject
{
}

+ (id)getColorDic;
+ (id)transformColor:(id)arg1;
+ (id)getColor:(id)arg1 file:(id)arg2;
+ (id)color:(id)arg1 originalColor:(id)arg2;
+ (_Bool)hideProgressViewFor:(id)arg1 animated:(_Bool)arg2;
+ (_Bool)showProgressViewFor:(id)arg1 text:(id)arg2 animated:(_Bool)arg3;
+ (id)getPinYinUpperFirstLetters:(id)arg1;
+ (id)getFileTypeIcon:(id)arg1;
+ (struct CGSize)getTextDrawingSize:(id)arg1 font:(id)arg2 constrainedSize:(struct CGSize)arg3;
+ (id)imageNamed:(id)arg1 ofBundle:(id)arg2;

@end

