//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class NSMutableArray, NSString, UIBarButtonItem, UILabel;
@protocol RCFileSelectorViewControllerDelegate;

@interface RCFileSelectorViewController : UITableViewController
{
    _Bool _isSubDirectory;
    int _maxSelectedNumber;
    id <RCFileSelectorViewControllerDelegate> _delegate;
    NSString *_rootPath;
    NSMutableArray *_dataSource;
    UIBarButtonItem *_rightItem;
    UILabel *_doneTitleLabel;
}

@property(retain, nonatomic) UILabel *doneTitleLabel; // @synthesize doneTitleLabel=_doneTitleLabel;
@property(retain, nonatomic) UIBarButtonItem *rightItem; // @synthesize rightItem=_rightItem;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) int maxSelectedNumber; // @synthesize maxSelectedNumber=_maxSelectedNumber;
@property(retain, nonatomic) NSString *rootPath; // @synthesize rootPath=_rootPath;
@property(nonatomic) _Bool isSubDirectory; // @synthesize isSubDirectory=_isSubDirectory;
@property(nonatomic) __weak id <RCFileSelectorViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)presentOverMaximumAlert;
- (_Bool)isOverMaximum:(id)arg1;
- (void)updateRightButtonLayout;
- (void)getDataSourceList;
- (void)clickDoneBtn:(id)arg1;
- (void)clickCancelBtn:(id)arg1;
- (void)clickBackBtn:(id)arg1;
- (void)selecteDirectory:(id)arg1;
- (void)selecteFile:(id)arg1;
- (id)getSelectDirectoryTableViewCell:(id)arg1 source:(id)arg2 row:(long long)arg3;
- (id)getSelectFilesTableViewCell:(id)arg1 source:(id)arg2 row:(long long)arg3;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithRootPath:(id)arg1;

@end

