//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIActionSheetDelegate-Protocol.h"

@class NSString, RCFileMessage, RCMessageModel, UIButton, UIImageView, UILabel, UIProgressView, UIWebView;

@interface RCFilePreviewViewController : UIViewController <UIActionSheetDelegate>
{
    int _extentLayoutForY;
    RCMessageModel *_messageModel;
    RCFileMessage *_fileMessage;
    UIWebView *_webView;
    UILabel *_nameLabel;
    UILabel *_sizeLabel;
    UILabel *_progressLabel;
    UIImageView *_typeIconView;
    UIProgressView *_progressView;
    UIButton *_downloadButton;
    UIButton *_openInOtherAppButton;
    UIButton *_cancelButton;
}

@property(nonatomic) int extentLayoutForY; // @synthesize extentLayoutForY=_extentLayoutForY;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIButton *openInOtherAppButton; // @synthesize openInOtherAppButton=_openInOtherAppButton;
@property(retain, nonatomic) UIButton *downloadButton; // @synthesize downloadButton=_downloadButton;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UIImageView *typeIconView; // @synthesize typeIconView=_typeIconView;
@property(retain, nonatomic) UILabel *progressLabel; // @synthesize progressLabel=_progressLabel;
@property(retain, nonatomic) UILabel *sizeLabel; // @synthesize sizeLabel=_sizeLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) RCFileMessage *fileMessage; // @synthesize fileMessage=_fileMessage;
@property(retain, nonatomic) RCMessageModel *messageModel; // @synthesize messageModel=_messageModel;
- (void).cxx_destruct;
- (void)dealloc;
- (void)transformEncodingFromFilePath:(id)arg1;
- (id)examineTheFilePathStr:(id)arg1;
- (_Bool)isFileSupported;
- (_Bool)isFileDownloaded;
- (_Bool)isFileDownloading;
- (void)downloading:(float)arg1;
- (void)updateDownloadMediaStatus:(id)arg1;
- (void)cancelFileDownload;
- (void)startFileDownLoad;
- (void)openCurrentFileInOtherApp;
- (void)openInOtherApp:(id)arg1;
- (void)clickBackBtn:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)moreAction;
- (void)layoutAndPreviewFile;
- (void)layoutForDownloading;
- (void)layoutForShowFileInfo;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

