//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCMessageContent.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface RCFileMessage : RCMessageContent <NSCoding>
{
    NSString *_name;
    long long _size;
    NSString *_type;
    NSString *_fileUrl;
    NSString *_localPath;
    NSString *_extra;
}

+ (id)getObjectName;
+ (unsigned long long)persistentFlag;
+ (id)messageWithFile:(id)arg1;
@property(retain, nonatomic) NSString *extra; // @synthesize extra=_extra;
@property(retain, nonatomic) NSString *localPath; // @synthesize localPath=_localPath;
@property(retain, nonatomic) NSString *fileUrl; // @synthesize fileUrl=_fileUrl;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(nonatomic) long long size; // @synthesize size=_size;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)getSearchableWords;
- (id)getFileName:(id)arg1;
- (long long)getFileSize:(id)arg1;
- (id)conversationDigest;
- (void)decodeWithData:(id)arg1;
- (id)encode;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

