//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCMessageCell.h"

@class NSMutableArray, UIButton, UIImageView, UILabel, UIProgressView;

@interface RCFileMessageCell : RCMessageCell
{
    UILabel *_nameLabel;
    UILabel *_sizeLabel;
    UIImageView *_typeIconView;
    UIProgressView *_progressView;
    UIImageView *_bubbleBackgroundView;
    UIButton *_cancelSendButton;
    UILabel *_cancelLabel;
    NSMutableArray *_messageContentConstraint;
}

+ (struct CGSize)sizeForMessageModel:(id)arg1 withCollectionViewWidth:(double)arg2 referenceExtraHeight:(double)arg3;
@property(retain, nonatomic) NSMutableArray *messageContentConstraint; // @synthesize messageContentConstraint=_messageContentConstraint;
@property(retain, nonatomic) UILabel *cancelLabel; // @synthesize cancelLabel=_cancelLabel;
@property(retain, nonatomic) UIButton *cancelSendButton; // @synthesize cancelSendButton=_cancelSendButton;
@property(retain, nonatomic) UIImageView *bubbleBackgroundView; // @synthesize bubbleBackgroundView=_bubbleBackgroundView;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UIImageView *typeIconView; // @synthesize typeIconView=_typeIconView;
@property(retain, nonatomic) UILabel *sizeLabel; // @synthesize sizeLabel=_sizeLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void).cxx_destruct;
- (void)updateDownloadMediaStatus:(id)arg1;
- (void)displayCancelButton;
- (void)displayCancelLabel;
- (void)cancelSend;
- (void)updateProgressView:(unsigned long long)arg1;
- (void)messageCellUpdateSendingStatusEvent:(id)arg1;
- (void)setAutoLayout;
- (void)setDataModel:(id)arg1;
- (void)longPressed:(id)arg1;
- (void)tapMessage:(id)arg1;
- (void)initialize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

