//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface RCFwLog : NSObject
{
}

+ (id)getIpWithHost:(id)arg1;
+ (void)setLogListener:(CDUnknownBlockType)arg1;
+ (void)setConsoleLogLevel:(unsigned long long)arg1;
+ (void)setUserId:(id)arg1;
+ (void)setToken:(id)arg1;
+ (void)setLogMonitor:(long long)arg1;
+ (id)getInstance;
+ (void)init:(id)arg1 sdkVer:(id)arg2;
- (void)write:(unsigned long long)arg1 type:(unsigned long long)arg2 tag:(id)arg3 keys:(id)arg4;

@end

