//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCBaseViewController.h"

#import "RCloudImageViewDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString, RCImageMessageProgressView, RCMessageModel, RCloudImageView, UIScrollView;

@interface RCImageSlideController : RCBaseViewController <UIScrollViewDelegate, RCloudImageViewDelegate, UIActionSheetDelegate>
{
    _Bool _statusBarHidden;
    RCMessageModel *_messageModel;
    RCImageMessageProgressView *_rcImageProressView;
    UIScrollView *_scrollView;
    NSMutableArray *_imageArray;
    long long _currentIndex;
    RCloudImageView *_currentImageView;
    double _newContentOffsetX;
    double _offsettest;
    double _ContentOffset;
    long long _preSelectIndex;
    NSMutableArray *_imageViewList;
    NSMutableArray *_imagemessageList;
    NSMutableDictionary *_imageProgressList;
}

@property(retain, nonatomic) NSMutableDictionary *imageProgressList; // @synthesize imageProgressList=_imageProgressList;
@property(retain, nonatomic) NSMutableArray *imagemessageList; // @synthesize imagemessageList=_imagemessageList;
@property(retain, nonatomic) NSMutableArray *imageViewList; // @synthesize imageViewList=_imageViewList;
@property(nonatomic) long long preSelectIndex; // @synthesize preSelectIndex=_preSelectIndex;
@property(nonatomic) double ContentOffset; // @synthesize ContentOffset=_ContentOffset;
@property(nonatomic) double offsettest; // @synthesize offsettest=_offsettest;
@property(nonatomic) double newContentOffsetX; // @synthesize newContentOffsetX=_newContentOffsetX;
@property(retain, nonatomic) RCloudImageView *currentImageView; // @synthesize currentImageView=_currentImageView;
@property(nonatomic) long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(retain, nonatomic) NSMutableArray *imageArray; // @synthesize imageArray=_imageArray;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) RCImageMessageProgressView *rcImageProressView; // @synthesize rcImageProressView=_rcImageProressView;
@property(retain, nonatomic) RCMessageModel *messageModel; // @synthesize messageModel=_messageModel;
- (void).cxx_destruct;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)backButtonAction;
- (void)setImageCenter:(id)arg1;
- (void)scrollViewDidZoom:(id)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)action:(id)arg1;
- (void)imageViewFailedToLoadImage:(id)arg1 error:(id)arg2;
- (void)imageViewLoadedImage:(id)arg1;
- (void)refreshScrollView:(id)arg1;
- (void)refreshimage:(id)arg1;
- (void)resizeSubviews:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)longPressed:(id)arg1;
- (void)doubleTap:(id)arg1;
- (void)singleTap:(id)arg1;
- (void)getMessageFromModel:(id)arg1;
- (_Bool)prefersStatusBarHidden;
- (void)setStatusBarHidden:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

