//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCMessageContent.h"

#import "NSCoding-Protocol.h"

@class NSData, NSString, UIImage;

@interface RCImageMessage : RCMessageContent <NSCoding>
{
    _Bool _full;
    NSString *_imageUrl;
    NSString *_localPath;
    UIImage *_thumbnailImage;
    NSString *_extra;
    UIImage *_originalImage;
    NSString *_thumbnailBase64String;
    NSData *_originalData;
}

+ (id)getObjectName;
+ (unsigned long long)persistentFlag;
+ (id)messageWithImageURI:(id)arg1;
+ (id)messageWithImageData:(id)arg1;
+ (id)messageWithImage:(id)arg1;
@property(retain, nonatomic) NSData *originalData; // @synthesize originalData=_originalData;
@property(retain, nonatomic) NSString *thumbnailBase64String; // @synthesize thumbnailBase64String=_thumbnailBase64String;
@property(retain, nonatomic) UIImage *originalImage; // @synthesize originalImage=_originalImage;
@property(retain, nonatomic) NSString *extra; // @synthesize extra=_extra;
@property(nonatomic, getter=isFull) _Bool full; // @synthesize full=_full;
@property(retain, nonatomic) UIImage *thumbnailImage; // @synthesize thumbnailImage=_thumbnailImage;
@property(retain, nonatomic) NSString *localPath; // @synthesize localPath=_localPath;
@property(retain, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSData *originalImageData;
- (void)decodeWithData:(id)arg1;
- (id)encode;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

