//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol RCChatRoomStatusDelegate;

@interface RCIMInternalClient : NSObject
{
    id <RCChatRoomStatusDelegate> _chatRoomStatusDelegate;
}

+ (id)sharedRCIMInternalClient;
@property(nonatomic) __weak id <RCChatRoomStatusDelegate> chatRoomStatusDelegate; // @synthesize chatRoomStatusDelegate=_chatRoomStatusDelegate;
- (void).cxx_destruct;
- (id)getPushSetting:(unsigned long long)arg1;
- (void)setPushSetting:(unsigned long long)arg1 value:(id)arg2 success:(CDUnknownBlockType)arg3 error:(CDUnknownBlockType)arg4;
- (void)uploadVoIPDeviceToken:(CDUnknownBlockType)arg1 error:(CDUnknownBlockType)arg2;
- (void)setVoIPDeviceToken:(id)arg1;
- (void)getVoIPMediaChannelInfo:(long long)arg1 channelId:(id)arg2 channelExtra:(id)arg3 success:(CDUnknownBlockType)arg4 error:(CDUnknownBlockType)arg5;
- (long long)getDeltaTime;
- (id)insertIncomingMessage:(unsigned long long)arg1 targetId:(id)arg2 senderUserId:(id)arg3 receivedStatus:(unsigned long long)arg4 content:(id)arg5 sentTime:(long long)arg6;
- (id)insertIncomingMessage:(unsigned long long)arg1 targetId:(id)arg2 senderUserId:(id)arg3 receivedStatus:(unsigned long long)arg4 content:(id)arg5;
- (id)insertOutgoingMessage:(unsigned long long)arg1 targetId:(id)arg2 sentStatus:(unsigned long long)arg3 content:(id)arg4 sentTime:(long long)arg5;
- (id)insertOutgoingMessage:(unsigned long long)arg1 targetId:(id)arg2 sentStatus:(unsigned long long)arg3 content:(id)arg4;
- (id)getReceiveMsgDelegate;
- (void)receiveFakeMessage:(id)arg1;
- (id)sendDirectionalMessage:(unsigned long long)arg1 targetId:(id)arg2 toUserIdList:(id)arg3 content:(id)arg4 pushContent:(id)arg5 pushData:(id)arg6 successBlock:(CDUnknownBlockType)arg7 errorBlock:(CDUnknownBlockType)arg8;
- (id)sendMessage:(unsigned long long)arg1 targetId:(id)arg2 content:(id)arg3 pushContent:(id)arg4 pushData:(id)arg5 successBlock:(CDUnknownBlockType)arg6 errorBlock:(CDUnknownBlockType)arg7;
- (void)updateConnectingUserInfo:(id)arg1;
- (id)getUserIdByCurrentToken;
- (id)getCurrentUserId;
- (void)clearCurrentToken;
- (void)clearConnectTimer;
- (void)resetCacheChatRoomForFailed;
- (void)updateCmp:(_Bool)arg1 retry:(_Bool)arg2;
- (void)stopRetry;
- (void)startRetry;
- (id)generatePublicServiceMenuItems:(id)arg1;

@end

