//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSFileHandle, NSString;

@interface RCLogWriter : NSObject
{
    NSString *_logFilePath;
    NSFileHandle *_logFileHandle;
}

+ (id)getInstance;
- (void).cxx_destruct;
- (void)closeLogFile;
- (void)openLogFile;
- (void)flush:(id)arg1 appKey:(id)arg2 userId:(id)arg3 token:(id)arg4;
- (void)flush;
- (void)write:(id)arg1;

@end

