//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCMessageCell.h"

@class UIImageView, UILabel;

@interface RCLocationMessageCell : RCMessageCell
{
    UIImageView *_bubbleBackgroundView;
    UIImageView *_pictureView;
    UILabel *_locationNameLabel;
    UIImageView *_maskView;
    UIImageView *_shadowMaskView;
}

+ (struct CGSize)sizeForMessageModel:(id)arg1 withCollectionViewWidth:(double)arg2 referenceExtraHeight:(double)arg3;
@property(retain, nonatomic) UIImageView *shadowMaskView; // @synthesize shadowMaskView=_shadowMaskView;
@property(retain, nonatomic) UIImageView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) UILabel *locationNameLabel; // @synthesize locationNameLabel=_locationNameLabel;
@property(retain, nonatomic) UIImageView *pictureView; // @synthesize pictureView=_pictureView;
@property(retain, nonatomic) UIImageView *bubbleBackgroundView; // @synthesize bubbleBackgroundView=_bubbleBackgroundView;
- (void).cxx_destruct;
- (void)longPressed:(id)arg1;
- (void)msgStatusViewTapEventHandler:(id)arg1;
- (void)setAutoLayout;
- (id)getImageFromImage:(id)arg1 withMessageDirection:(unsigned long long)arg2;
- (void)setDataModel:(id)arg1;
- (void)tapPicture:(id)arg1;
- (void)setMaskImage:(id)arg1;
- (void)initialize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

