//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface RCLogUploader : NSObject
{
}

+ (id)getInstance;
- (void)updateExistZipFile;
- (id)getBodyData:(id)arg1;
- (void)uploadFile:(id)arg1 startTime:(id)arg2 endTime:(id)arg3 sdkVer:(id)arg4 appKey:(id)arg5 userId:(id)arg6 token:(id)arg7;
- (void)upload;

@end

