//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface RCLogEntity : NSObject
{
    NSString *_logDir;
    NSString *_sdkVer;
    NSString *_appKey;
    NSString *_userId;
    NSString *_token;
    long long _startLogTime;
    long long _monitorLevel;
    long long _monitorType;
    NSString *_uploadCacheList;
    long long _logConsoleLevel;
    CDUnknownBlockType _logListenerBlock;
    unsigned long long _logMode;
    NSString *_uploadUrl;
    double _uploadTimeInterval;
    long long _outDateTime;
    long long _fileMaxSize;
    long long _startTimePconnectT;
}

+ (id)getInstance;
@property(nonatomic) long long startTimePconnectT; // @synthesize startTimePconnectT=_startTimePconnectT;
@property(nonatomic) long long fileMaxSize; // @synthesize fileMaxSize=_fileMaxSize;
@property(nonatomic) long long outDateTime; // @synthesize outDateTime=_outDateTime;
@property(nonatomic) double uploadTimeInterval; // @synthesize uploadTimeInterval=_uploadTimeInterval;
@property(copy, nonatomic) NSString *uploadUrl; // @synthesize uploadUrl=_uploadUrl;
@property(nonatomic) unsigned long long logMode; // @synthesize logMode=_logMode;
@property(copy, nonatomic) CDUnknownBlockType logListenerBlock; // @synthesize logListenerBlock=_logListenerBlock;
@property(nonatomic) long long logConsoleLevel; // @synthesize logConsoleLevel=_logConsoleLevel;
- (void).cxx_destruct;
- (void)handleUploadCacheList:(CDUnknownBlockType)arg1;
- (void)setUploadCacheArray:(id)arg1;
- (id)getUploadCacheArray;
@property(copy, nonatomic) NSString *uploadCacheList; // @synthesize uploadCacheList=_uploadCacheList;
@property(nonatomic) long long monitorType; // @synthesize monitorType=_monitorType;
@property(nonatomic) long long monitorLevel; // @synthesize monitorLevel=_monitorLevel;
@property(nonatomic) long long startLogTime; // @synthesize startLogTime=_startLogTime;
@property(copy, nonatomic) NSString *token; // @synthesize token=_token;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(copy, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
@property(copy, nonatomic) NSString *sdkVer; // @synthesize sdkVer=_sdkVer;
@property(readonly, copy, nonatomic) NSString *logDir; // @synthesize logDir=_logDir;

@end

