//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class RCMessageModel, RCTipLabel, UIButton, UITapGestureRecognizer, UIView;
@protocol RCMessageCellDelegate;

@interface RCMessageBaseCell : UICollectionViewCell
{
    _Bool _isDisplayMessageTime;
    _Bool _isDisplayReadStatus;
    _Bool _allowsSelection;
    id <RCMessageCellDelegate> _delegate;
    RCTipLabel *_messageTimeLabel;
    RCMessageModel *_model;
    UIView *_baseContentView;
    unsigned long long _messageDirection;
    UITapGestureRecognizer *_multiSelectTap;
    UIButton *_selectButton;
}

+ (struct CGSize)sizeForMessageModel:(id)arg1 withCollectionViewWidth:(double)arg2 referenceExtraHeight:(double)arg3;
@property(retain, nonatomic) UIButton *selectButton; // @synthesize selectButton=_selectButton;
@property(retain, nonatomic) UITapGestureRecognizer *multiSelectTap; // @synthesize multiSelectTap=_multiSelectTap;
@property(nonatomic) _Bool allowsSelection; // @synthesize allowsSelection=_allowsSelection;
@property(nonatomic) _Bool isDisplayReadStatus; // @synthesize isDisplayReadStatus=_isDisplayReadStatus;
@property(readonly, nonatomic) _Bool isDisplayMessageTime; // @synthesize isDisplayMessageTime=_isDisplayMessageTime;
@property(nonatomic) unsigned long long messageDirection; // @synthesize messageDirection=_messageDirection;
@property(retain, nonatomic) UIView *baseContentView; // @synthesize baseContentView=_baseContentView;
@property(retain, nonatomic) RCMessageModel *model; // @synthesize model=_model;
@property(retain, nonatomic) RCTipLabel *messageTimeLabel; // @synthesize messageTimeLabel=_messageTimeLabel;
@property(nonatomic) __weak id <RCMessageCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)updateSelectButtonStatus;
- (void)onSelectMessageEvent;
- (void)updateUIForMultiSelect;
- (void)onChangedMessageMultiSelectStatus:(id)arg1;
- (void)messageCellUpdateSendingStatusEvent:(id)arg1;
- (void)setBaseAutoLayout;
- (void)setDataModel:(id)arg1;
- (void)setupMessageBaseCellView;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

