//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface RCMessageSelectionUtility : NSObject
{
    _Bool _multiSelect;
    NSMutableArray *_messages;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSMutableArray *messages; // @synthesize messages=_messages;
@property(nonatomic) _Bool multiSelect; // @synthesize multiSelect=_multiSelect;
- (void).cxx_destruct;
- (void)clear;
- (void)removeAllMessages;
- (id)selectedMessages;
- (_Bool)isContainMessage:(id)arg1;
- (void)removeMessageModel:(id)arg1;
- (void)addMessageModel:(id)arg1;

@end

