//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "RCGetDownloadURLDelegate-Protocol.h"
#import "RCGetUploadTokenDelegate-Protocol.h"

@class NSData, NSString, RCUpload, RCUploadImageStatusListener;

@interface RCMediaUploader : NSObject <RCGetUploadTokenDelegate, RCGetDownloadURLDelegate>
{
    _Bool _userCanceled;
    CDUnknownBlockType _progressBlock;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _errorBlock;
    CDUnknownBlockType _cancelBlock;
    CDUnknownBlockType _pauseBlock;
    NSData *_uploadContent;
    unsigned long long _mediaType;
    NSString *_originalFileName;
    RCUpload *_uploader;
    RCUploadImageStatusListener *_uploadListener;
}

@property(nonatomic) _Bool userCanceled; // @synthesize userCanceled=_userCanceled;
@property(retain, nonatomic) RCUploadImageStatusListener *uploadListener; // @synthesize uploadListener=_uploadListener;
@property(retain, nonatomic) RCUpload *uploader; // @synthesize uploader=_uploader;
@property(copy, nonatomic) NSString *originalFileName; // @synthesize originalFileName=_originalFileName;
@property(nonatomic) unsigned long long mediaType; // @synthesize mediaType=_mediaType;
@property(retain, nonatomic) NSData *uploadContent; // @synthesize uploadContent=_uploadContent;
@property(copy, nonatomic) CDUnknownBlockType pauseBlock; // @synthesize pauseBlock=_pauseBlock;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
@property(copy, nonatomic) CDUnknownBlockType errorBlock; // @synthesize errorBlock=_errorBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(copy, nonatomic) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
- (void).cxx_destruct;
- (void)getDownloadUrl:(id)arg1;
- (void)onGetDownloadURLCode:(int)arg1 description:(id)arg2;
- (void)onGetUploadTokenCode:(int)arg1 description:(id)arg2;
- (void)resume;
- (void)pause;
- (void)cancel;
- (void)start;
- (id)initWithMediaType:(unsigned long long)arg1 uploadContent:(id)arg2 fileName:(id)arg3 progress:(CDUnknownBlockType)arg4 success:(CDUnknownBlockType)arg5 error:(CDUnknownBlockType)arg6 cancel:(CDUnknownBlockType)arg7 pause:(CDUnknownBlockType)arg8;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

