//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface RCNaviDataInfo : NSObject
{
    _Bool _isSuccess;
    _Bool _isOpenLocation;
    _Bool _isPublicServiceEnabled;
    _Bool _isUserSettingEnabled;
    _Bool _isHistoryMessageStoreEnabled;
    _Bool _isChatroomMessageStoreEnabled;
    _Bool _isMutliChatroomEnabled;
    _Bool _isPrivateCloud;
    _Bool _connectionStrategy;
    long long _responseCode;
    NSString *_voipServer;
    NSArray *_voipCallInfoList;
    NSString *_uploadServer;
    NSString *_cmpServer;
    NSArray *_subCmpServerList;
    NSArray *_locationSupportConversationTypes;
    long long _locationMaxParticipant;
    long long _locationRefreshInterval;
    long long _locationDistanceFilter;
    NSArray *_messageReceiptSupportConversationTypes;
    NSString *_userId;
}

+ (void)parserVoIPConfig:(id)arg1 toNaviInfo:(id)arg2;
+ (void)parserLocation:(id)arg1 toNaviInfo:(id)arg2;
+ (id)decodeWithXmlString:(id)arg1;
+ (_Bool)isValidCMPServer:(id)arg1;
@property(nonatomic) _Bool connectionStrategy; // @synthesize connectionStrategy=_connectionStrategy;
@property(nonatomic) _Bool isPrivateCloud; // @synthesize isPrivateCloud=_isPrivateCloud;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(nonatomic) _Bool isMutliChatroomEnabled; // @synthesize isMutliChatroomEnabled=_isMutliChatroomEnabled;
@property(nonatomic) _Bool isChatroomMessageStoreEnabled; // @synthesize isChatroomMessageStoreEnabled=_isChatroomMessageStoreEnabled;
@property(nonatomic) _Bool isHistoryMessageStoreEnabled; // @synthesize isHistoryMessageStoreEnabled=_isHistoryMessageStoreEnabled;
@property(nonatomic) _Bool isUserSettingEnabled; // @synthesize isUserSettingEnabled=_isUserSettingEnabled;
@property(nonatomic) _Bool isPublicServiceEnabled; // @synthesize isPublicServiceEnabled=_isPublicServiceEnabled;
@property(retain, nonatomic) NSArray *messageReceiptSupportConversationTypes; // @synthesize messageReceiptSupportConversationTypes=_messageReceiptSupportConversationTypes;
@property(nonatomic) long long locationDistanceFilter; // @synthesize locationDistanceFilter=_locationDistanceFilter;
@property(nonatomic) long long locationRefreshInterval; // @synthesize locationRefreshInterval=_locationRefreshInterval;
@property(nonatomic) long long locationMaxParticipant; // @synthesize locationMaxParticipant=_locationMaxParticipant;
@property(retain, nonatomic) NSArray *locationSupportConversationTypes; // @synthesize locationSupportConversationTypes=_locationSupportConversationTypes;
@property(nonatomic) _Bool isOpenLocation; // @synthesize isOpenLocation=_isOpenLocation;
@property(retain, nonatomic) NSArray *subCmpServerList; // @synthesize subCmpServerList=_subCmpServerList;
@property(retain, nonatomic) NSString *cmpServer; // @synthesize cmpServer=_cmpServer;
@property(retain, nonatomic) NSString *uploadServer; // @synthesize uploadServer=_uploadServer;
@property(retain, nonatomic) NSArray *voipCallInfoList; // @synthesize voipCallInfoList=_voipCallInfoList;
@property(copy, nonatomic) NSString *voipServer; // @synthesize voipServer=_voipServer;
@property(nonatomic) long long responseCode; // @synthesize responseCode=_responseCode;
@property(nonatomic) _Bool isSuccess; // @synthesize isSuccess=_isSuccess;
- (void).cxx_destruct;
- (id)init;

@end

