//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewController.h>

@class NSArray, NSMutableArray, NSString, UIActivityIndicatorView, UIButton, UIImageView, UIView;

@interface RCPhotoPreviewCollectionViewController : UICollectionViewController
{
    _Bool _isFull;
    int _imageRequestID;
    CDUnknownBlockType _finishPreviewAndBackPhotosPicker;
    CDUnknownBlockType _finishiPreviewAndSendImage;
    UIActivityIndicatorView *_indicatorView;
    UIView *_topView;
    UIButton *_selectedButton;
    UIView *_bottomView;
    UIButton *_fullButton;
    UIButton *_sendButton;
    UIButton *_selectedImageCount;
    UIImageView *_FullImageView;
    NSArray *_previewPhotosArr;
    NSArray *_allPhotosArr;
    NSMutableArray *_selectedArr;
    long long _currentIndex;
    NSString *_currentAssetIdentifier;
}

+ (id)imagePickerViewController;
@property(nonatomic) int imageRequestID; // @synthesize imageRequestID=_imageRequestID;
@property(copy, nonatomic) NSString *currentAssetIdentifier; // @synthesize currentAssetIdentifier=_currentAssetIdentifier;
@property(nonatomic) long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(retain, nonatomic) NSMutableArray *selectedArr; // @synthesize selectedArr=_selectedArr;
@property(retain, nonatomic) NSArray *allPhotosArr; // @synthesize allPhotosArr=_allPhotosArr;
@property(retain, nonatomic) NSArray *previewPhotosArr; // @synthesize previewPhotosArr=_previewPhotosArr;
@property(retain, nonatomic) UIImageView *FullImageView; // @synthesize FullImageView=_FullImageView;
@property(retain, nonatomic) UIButton *selectedImageCount; // @synthesize selectedImageCount=_selectedImageCount;
@property(retain, nonatomic) UIButton *sendButton; // @synthesize sendButton=_sendButton;
@property(retain, nonatomic) UIButton *fullButton; // @synthesize fullButton=_fullButton;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIButton *selectedButton; // @synthesize selectedButton=_selectedButton;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(nonatomic) _Bool isFull; // @synthesize isFull=_isFull;
@property(copy, nonatomic) CDUnknownBlockType finishiPreviewAndSendImage; // @synthesize finishiPreviewAndSendImage=_finishiPreviewAndSendImage;
@property(copy, nonatomic) CDUnknownBlockType finishPreviewAndBackPhotosPicker; // @synthesize finishPreviewAndBackPhotosPicker=_finishPreviewAndBackPhotosPicker;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)getImageSize:(double)arg1;
- (void)updateImageSize;
- (void)animationWithLayer:(id)arg1;
- (void)showAlertWithMessage:(id)arg1;
- (void)_updateBottomSendImageCountButton;
- (void)_updateTopBarStatus;
- (void)sendImageMessageButton:(id)arg1;
- (void)fullBtnCliced:(id)arg1;
- (void)cancelAlert:(id)arg1;
- (void)isSelectedButtonAction:(id)arg1;
- (void)backButtonAction;
- (void)createBottomView;
- (void)creatTopView;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidLoad;
- (void)previewPhotosWithSelectArr:(id)arg1 allPhotosArr:(id)arg2 currentIndex:(long long)arg3 accordToIsSelect:(_Bool)arg4;
- (id)initWithCollectionViewLayout:(id)arg1;

@end

