//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewController.h>

#import "PHPhotoLibraryChangeObserver-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSMutableArray, NSString, PHCachingImageManager, UIButton, UIView;

@interface RCPhotosPickerController : UICollectionViewController <UICollectionViewDelegateFlowLayout, PHPhotoLibraryChangeObserver>
{
    _Bool _isFull;
    _Bool _disableFirstAppear;
    _Bool _isLoad;
    NSMutableArray *_assetArray;
    long long _count;
    id _currentAsset;
    CDUnknownBlockType _sendPhotosBlock;
    NSMutableArray *_selectedAssets;
    UIView *_toolBar;
    UIButton *_previewBtn;
    UIButton *_btnSend;
    UIButton *_selectedImageCount;
    PHCachingImageManager *_cachingImageManager;
    struct CGSize _thumbnailSize;
    struct CGRect _previousPreheatRect;
}

+ (id)imagePickerViewController;
@property(nonatomic) struct CGSize thumbnailSize; // @synthesize thumbnailSize=_thumbnailSize;
@property(nonatomic) struct CGRect previousPreheatRect; // @synthesize previousPreheatRect=_previousPreheatRect;
@property(retain, nonatomic) PHCachingImageManager *cachingImageManager; // @synthesize cachingImageManager=_cachingImageManager;
@property(nonatomic) _Bool isLoad; // @synthesize isLoad=_isLoad;
@property(nonatomic) _Bool disableFirstAppear; // @synthesize disableFirstAppear=_disableFirstAppear;
@property(nonatomic) _Bool isFull; // @synthesize isFull=_isFull;
@property(retain, nonatomic) UIButton *selectedImageCount; // @synthesize selectedImageCount=_selectedImageCount;
@property(retain, nonatomic) UIButton *btnSend; // @synthesize btnSend=_btnSend;
@property(retain, nonatomic) UIButton *previewBtn; // @synthesize previewBtn=_previewBtn;
@property(retain, nonatomic) UIView *toolBar; // @synthesize toolBar=_toolBar;
@property(retain, nonatomic) NSMutableArray *selectedAssets; // @synthesize selectedAssets=_selectedAssets;
@property(copy, nonatomic) CDUnknownBlockType sendPhotosBlock; // @synthesize sendPhotosBlock=_sendPhotosBlock;
@property(retain, nonatomic) id currentAsset; // @synthesize currentAsset=_currentAsset;
@property(nonatomic) long long count; // @synthesize count=_count;
@property(retain, nonatomic) NSMutableArray *assetArray; // @synthesize assetArray=_assetArray;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (id)removedRectsBetween:(struct CGRect)arg1 and:(struct CGRect)arg2;
- (id)addedRectsBetween:(struct CGRect)arg1 and:(struct CGRect)arg2;
- (id)assetsInRects:(id)arg1;
- (void)updateCachedAssets;
- (void)dealloc;
- (float)getIPhonexExtraBottomHeight;
- (void)photoLibraryDidChange:(id)arg1;
- (void)_updateBottomSendImageCountButton;
- (void)showAlertWithMessage:(id)arg1;
- (void)setButtonEnable;
- (void)createTopView;
- (void)cancelAlert:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)previewBtnCliced:(id)arg1;
- (void)btnSendCliced:(id)arg1;
- (void)dismissCurrentModelViewController;
- (void)backButtonAction;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithCollectionViewLayout:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

