//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCMessageContent.h"

#import "NSCoding-Protocol.h"

@class NSString, RCRichContentItem;

@interface RCPublicServiceRichContentMessage : RCMessageContent <NSCoding>
{
    RCRichContentItem *_richContent;
    NSString *_extra;
}

+ (id)getObjectName;
@property(retain, nonatomic) NSString *extra; // @synthesize extra=_extra;
@property(retain, nonatomic) RCRichContentItem *richContent; // @synthesize richContent=_richContent;
- (void).cxx_destruct;
- (void)decodeWithData:(id)arg1;
- (id)encode;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

