//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIButton;

@interface RCPublicServiceProfileActionCell : UITableViewCell
{
    CDUnknownBlockType _onClickEvent;
    UIButton *_button;
}

@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
@property(copy, nonatomic) CDUnknownBlockType onClickEvent; // @synthesize onClickEvent=_onClickEvent;
- (void).cxx_destruct;
- (void)updateFrame;
- (void)setTitleText:(id)arg1 andBackgroundColor:(id)arg2;
- (void)onButtonPushDown:(id)arg1;
- (void)setup;
- (id)init;

@end

