//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCConversationListViewController.h"

@interface RCPublicServiceChatListViewController : RCConversationListViewController
{
}

- (void)addPublicService:(id)arg1;
- (void)onSelectedTableRow:(unsigned long long)arg1 conversationModel:(id)arg2 atIndexPath:(id)arg3;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)setup;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)init;
- (id)initWithCoder:(id)arg1;

@end

