//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class RCPublicServiceProfile, UILabel, UISwitch;

@interface RCPublicServiceProfileRcvdMsgCell : UITableViewCell
{
    RCPublicServiceProfile *_serviceProfile;
    UILabel *_title;
    UISwitch *_switcher;
}

@property(retain, nonatomic) UISwitch *switcher; // @synthesize switcher=_switcher;
@property(retain, nonatomic) UILabel *title; // @synthesize title=_title;
@property(retain, nonatomic) RCPublicServiceProfile *serviceProfile; // @synthesize serviceProfile=_serviceProfile;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateFrame;
- (void)setOn:(_Bool)arg1;
- (void)switchAction:(id)arg1;
- (void)setTitleText:(id)arg1;
- (void)setup;
- (id)init;

@end

