//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, UIImageView;
@protocol RCPublicServicePopupMenuItemSelectedDelegate;

@interface RCPublicServicePopupMenuView : UIView <UIGestureRecognizerDelegate>
{
    id <RCPublicServicePopupMenuItemSelectedDelegate> _delegate;
    NSArray *_menuItems;
    NSMutableArray *_itemViews;
    UIImageView *_backgroundImageView;
}

@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(retain, nonatomic) NSMutableArray *itemViews; // @synthesize itemViews=_itemViews;
@property(retain, nonatomic) NSArray *menuItems; // @synthesize menuItems=_menuItems;
@property(nonatomic) __weak id <RCPublicServicePopupMenuItemSelectedDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)drawPopoverImage:(struct CGSize)arg1 arrowOffset:(unsigned long long)arg2;
- (void)tapAction:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)newLine;
- (void)onMenuButtonPressed:(id)arg1;
- (_Bool)resignFirstResponder;
- (void)displayMenuItems:(id)arg1 atPoint:(struct CGPoint)arg2 withWidth:(double)arg3;
- (void)removeAllSubItems;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)arg1;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

