//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCMessageContent.h"

#import "NSCoding-Protocol.h"

@class NSArray, NSString;

@interface RCPublicServiceMultiRichContentMessage : RCMessageContent <NSCoding>
{
    NSArray *_richContents;
    NSString *_extra;
    long long _selectedItemIndex;
}

+ (id)getObjectName;
+ (unsigned long long)persistentFlag;
@property(nonatomic) long long selectedItemIndex; // @synthesize selectedItemIndex=_selectedItemIndex;
@property(retain, nonatomic) NSString *extra; // @synthesize extra=_extra;
@property(retain, nonatomic) NSArray *richContents; // @synthesize richContents=_richContents;
- (void).cxx_destruct;
- (void)decodeWithData:(id)arg1;
- (id)encode;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;

@end

