//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString, RCloudImageView, UILabel;

@interface RCPublicServiceListViewCell : UITableViewCell
{
    RCloudImageView *_headerImageView;
    long long _portraitStyle;
    NSString *_searchKey;
    UILabel *_nameLabel;
    UILabel *_describeLabel;
}

@property(retain, nonatomic) UILabel *describeLabel; // @synthesize describeLabel=_describeLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) NSString *searchKey; // @synthesize searchKey=_searchKey;
@property(nonatomic) long long portraitStyle; // @synthesize portraitStyle=_portraitStyle;
@property(retain, nonatomic) RCloudImageView *headerImageView; // @synthesize headerImageView=_headerImageView;
- (void).cxx_destruct;
- (void)updateConstraints;
- (void)setup;
- (id)getAttributedStringWith:(id)arg1;
- (void)setDescription:(id)arg1;
- (void)setName:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

