//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCMessageContent.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface RCRecallCommandMessage : RCMessageContent <NSCoding>
{
    NSString *_messageUId;
    unsigned long long _conversationType;
    NSString *_targetId;
    long long _sentTime;
    NSString *_extra;
}

+ (id)getObjectName;
+ (unsigned long long)persistentFlag;
@property(retain, nonatomic) NSString *extra; // @synthesize extra=_extra;
@property(nonatomic) long long sentTime; // @synthesize sentTime=_sentTime;
@property(retain, nonatomic) NSString *targetId; // @synthesize targetId=_targetId;
@property(nonatomic) unsigned long long conversationType; // @synthesize conversationType=_conversationType;
@property(retain, nonatomic) NSString *messageUId; // @synthesize messageUId=_messageUId;
- (void).cxx_destruct;
- (id)encode;
- (void)decodeWithData:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

