//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLSessionDelegate-Protocol.h"

@class NSMutableDictionary, NSString, NSURLSession;
@protocol RCResumeableDownloaderDelegate;

@interface RCResumeableDownloader : NSObject <NSURLSessionDelegate>
{
    id <RCResumeableDownloaderDelegate> _delegate;
    NSURLSession *_urlSession;
    NSMutableDictionary *_items;
    NSString *_archivePath;
    NSString *_archiveFileFullPath;
}

+ (void)updateMessageContentWithMessageId:(long long)arg1 localPath:(id)arg2;
+ (id)taskIdentifyWithMessageId:(long long)arg1;
+ (id)copy;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (void)free;
+ (id)defaultInstance;
@property(copy, nonatomic) NSString *archiveFileFullPath; // @synthesize archiveFileFullPath=_archiveFileFullPath;
@property(copy, nonatomic) NSString *archivePath; // @synthesize archivePath=_archivePath;
@property(retain, nonatomic) NSMutableDictionary *items; // @synthesize items=_items;
@property(retain, nonatomic) NSURLSession *urlSession; // @synthesize urlSession=_urlSession;
@property(nonatomic) __weak id <RCResumeableDownloaderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)archiveItems;
- (void)createDirectoryIfNeed;
- (void)dealloc;
- (id)itemWithIdentify:(id)arg1 url:(id)arg2 fileName:(id)arg3;
- (id)itemWithMessageId:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

