//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface RCReadReceiptInfo : NSObject
{
    _Bool _isReceiptRequestMessage;
    _Bool _hasRespond;
    NSMutableDictionary *_userIdList;
}

@property(retain, nonatomic) NSMutableDictionary *userIdList; // @synthesize userIdList=_userIdList;
@property(nonatomic) _Bool hasRespond; // @synthesize hasRespond=_hasRespond;
@property(nonatomic) _Bool isReceiptRequestMessage; // @synthesize isReceiptRequestMessage=_isReceiptRequestMessage;
- (void).cxx_destruct;

@end

