//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCMessageCell.h"

@class RCAttributedLabel, RCloudImageView, UIImageView;

@interface RCRichContentMessageCell : RCMessageCell
{
    UIImageView *_bubbleBackgroundView;
    RCloudImageView *_richContentImageView;
    RCAttributedLabel *_digestLabel;
    RCAttributedLabel *_titleLabel;
}

+ (struct CGSize)sizeForMessageModel:(id)arg1 withCollectionViewWidth:(double)arg2 referenceExtraHeight:(double)arg3;
@property(retain, nonatomic) RCAttributedLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) RCAttributedLabel *digestLabel; // @synthesize digestLabel=_digestLabel;
@property(retain, nonatomic) RCloudImageView *richContentImageView; // @synthesize richContentImageView=_richContentImageView;
@property(retain, nonatomic) UIImageView *bubbleBackgroundView; // @synthesize bubbleBackgroundView=_bubbleBackgroundView;
- (void).cxx_destruct;
- (void)longPressed:(id)arg1;
- (void)tapBubbleBackgroundViewEvent:(id)arg1;
- (void)setDataModel:(id)arg1;
- (void)tapMessage:(id)arg1;
- (void)initialize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

