//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCCustomIOSAlertView.h"

#import "RCCustomIOSAlertViewDelegate-Protocol.h"

@class NSString, UIButton, UILabel;
@protocol RCRobotEvaluationViewDelegate;

@interface RCRobotEvaluationView : RCCustomIOSAlertView <RCCustomIOSAlertViewDelegate>
{
    _Bool _quitAfterEvaluation;
    _Bool _isResolved;
    NSString *_knownledgeId;
    id <RCRobotEvaluationViewDelegate> _robotEvaluationViewDelegate;
    UIButton *_yesButton;
    UIButton *_noButton;
    UILabel *_titleLabel;
}

@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIButton *noButton; // @synthesize noButton=_noButton;
@property(retain, nonatomic) UIButton *yesButton; // @synthesize yesButton=_yesButton;
@property(nonatomic) _Bool isResolved; // @synthesize isResolved=_isResolved;
@property(nonatomic) __weak id <RCRobotEvaluationViewDelegate> robotEvaluationViewDelegate; // @synthesize robotEvaluationViewDelegate=_robotEvaluationViewDelegate;
@property(retain, nonatomic) NSString *knownledgeId; // @synthesize knownledgeId=_knownledgeId;
@property(nonatomic) _Bool quitAfterEvaluation; // @synthesize quitAfterEvaluation=_quitAfterEvaluation;
- (void).cxx_destruct;
- (void)customIOS7dialogButtonTouchUpInside:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)createDemoView;
- (void)onNoButton:(id)arg1;
- (void)onYesButton:(id)arg1;
- (id)initWithDelegate:(id)arg1;

@end

