//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCConversationSettingTableViewController.h"

#import "UIActionSheetDelegate-Protocol.h"

@class NSString, UIActionSheet;

@interface RCSettingViewController : RCConversationSettingTableViewController <UIActionSheetDelegate>
{
    NSString *_targetId;
    unsigned long long _conversationType;
    CDUnknownBlockType _clearHistoryCompletion;
    UIActionSheet *_clearMsgHistoryActionSheet;
}

@property(readonly, nonatomic) UIActionSheet *clearMsgHistoryActionSheet; // @synthesize clearMsgHistoryActionSheet=_clearMsgHistoryActionSheet;
@property(copy, nonatomic) CDUnknownBlockType clearHistoryCompletion; // @synthesize clearHistoryCompletion=_clearHistoryCompletion;
@property(nonatomic) unsigned long long conversationType; // @synthesize conversationType=_conversationType;
@property(copy, nonatomic) NSString *targetId; // @synthesize targetId=_targetId;
- (void).cxx_destruct;
- (void)deleteTipButtonClicked:(id)arg1;
- (void)settingTableViewHeader:(id)arg1 indexPathOfSelectedItem:(id)arg2 allTheSeletedUsers:(id)arg3;
- (void)onClickIsTopSwitch:(id)arg1;
- (void)clearHistoryMessage;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onClickClearMessageHistory:(id)arg1;
- (void)onClickNewMessageNotificationSwitch:(id)arg1;
- (void)setSwitchState;
- (void)backBarButtonItemClicked:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

