//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel;

@interface RCSelectDirectoryTableViewCell : UITableViewCell
{
    UIImageView *_directoryImageView;
    UILabel *_directoryNameLabel;
}

@property(retain, nonatomic) UILabel *directoryNameLabel; // @synthesize directoryNameLabel=_directoryNameLabel;
@property(retain, nonatomic) UIImageView *directoryImageView; // @synthesize directoryImageView=_directoryImageView;
- (void).cxx_destruct;
- (void)setupSelectDirectoryCellView;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

