//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCMessageCell.h"

@class RCSightMessageProgressViw, UIImageView, UILabel, UIView;

@interface RCSightMessageCell : RCMessageCell
{
    UIImageView *_thumbnailView;
    RCSightMessageProgressViw *_progressView;
    UIImageView *_maskView;
    UIImageView *_shadowMaskView;
    UIView *_shadowView;
    UIView *_playButtonView;
    UILabel *_durationLabel;
    UIImageView *_playImage;
}

+ (struct CGSize)sizeForMessageModel:(id)arg1 withCollectionViewWidth:(double)arg2 referenceExtraHeight:(double)arg3;
@property(retain, nonatomic) UIImageView *playImage; // @synthesize playImage=_playImage;
@property(retain, nonatomic) UILabel *durationLabel; // @synthesize durationLabel=_durationLabel;
@property(retain, nonatomic) UIView *playButtonView; // @synthesize playButtonView=_playButtonView;
@property(retain, nonatomic) UIView *shadowView; // @synthesize shadowView=_shadowView;
@property(retain, nonatomic) UIImageView *shadowMaskView; // @synthesize shadowMaskView=_shadowMaskView;
@property(retain, nonatomic) UIImageView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) RCSightMessageProgressViw *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UIImageView *thumbnailView; // @synthesize thumbnailView=_thumbnailView;
- (void).cxx_destruct;
- (void)longPressed:(id)arg1;
- (void)tapSight:(id)arg1;
- (void)messageCellUpdateSendingStatusEvent:(id)arg1;
- (void)setDataModel:(id)arg1;
- (void)setMaskImage:(id)arg1;
- (void)updateDownloadMediaStatus:(id)arg1;
- (void)dealloc;
- (void)initialize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

