//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class NSMutableArray, RCMessageModel;

@interface RCSightFileBrowserViewController : UITableViewController
{
    RCMessageModel *_messageModel;
    NSMutableArray *_messageModelArray;
}

@property(retain, nonatomic) NSMutableArray *messageModelArray; // @synthesize messageModelArray=_messageModelArray;
@property(retain, nonatomic) RCMessageModel *messageModel; // @synthesize messageModel=_messageModel;
- (void).cxx_destruct;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)getMessageFromModel:(id)arg1;
- (id)getOlderMessagesThanModel:(id)arg1 count:(long long)arg2;
- (id)getLaterMessagesThanModel:(id)arg1 count:(long long)arg2;
- (void)refreshAction:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithMessageModel:(id)arg1;

@end

