//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class CAShapeLayer, RCMessageProgressViewBackgroundLayer, UIColor;

@interface RCSightMessageProgressViw : UIControl
{
    UIColor *_progressTintColor;
    _Bool _startAnimation;
    float _progress;
    RCMessageProgressViewBackgroundLayer *_backgroundLayer;
    CAShapeLayer *_shapeLayer;
}

@property(nonatomic) _Bool startAnimation; // @synthesize startAnimation=_startAnimation;
@property(retain, nonatomic) CAShapeLayer *shapeLayer; // @synthesize shapeLayer=_shapeLayer;
@property(retain, nonatomic) RCMessageProgressViewBackgroundLayer *backgroundLayer; // @synthesize backgroundLayer=_backgroundLayer;
@property(nonatomic) float progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
- (void)reset;
- (void)stopIndeterminateAnimation;
- (void)startIndeterminateAnimation;
- (void)tintColorDidChange;
- (void)sendAction:(SEL)arg1 to:(id)arg2 forEvent:(id)arg3;
@property(retain, nonatomic) UIColor *progressTintColor;
- (void)setProgress:(float)arg1 animated:(_Bool)arg2;
- (void)setup;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

