//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class RCMessageModel, RCSightPlayerController, UIActivityIndicatorView, UIButton, UIImageView, UILabel;
@protocol RCSightCollectionViewCellDelegate;

@interface RCSightCollectionViewCell : UICollectionViewCell
{
    _Bool _autoPlay;
    UILabel *_label;
    id <RCSightCollectionViewCellDelegate> _delegate;
    UIImageView *_thumbnailView;
    UIButton *_playBtn;
    RCSightPlayerController *_playerController;
    RCMessageModel *_messageModel;
    UIActivityIndicatorView *_indicatorView;
}

@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) RCMessageModel *messageModel; // @synthesize messageModel=_messageModel;
@property(retain, nonatomic) RCSightPlayerController *playerController; // @synthesize playerController=_playerController;
@property(retain, nonatomic) UIButton *playBtn; // @synthesize playBtn=_playBtn;
@property(retain, nonatomic) UIImageView *thumbnailView; // @synthesize thumbnailView=_thumbnailView;
@property(nonatomic, getter=isAutoPlay) _Bool autoPlay; // @synthesize autoPlay=_autoPlay;
@property(nonatomic) __weak id <RCSightCollectionViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (void)closeSightPlayer;
- (void)stopPlay;
- (void)setDataModel:(id)arg1;
- (void)constrainView:(id)arg1 toSize:(struct CGSize)arg2;
- (void)constraintCenterInSuperview:(id)arg1;
- (void)strechToSuperview:(id)arg1;
- (void)setUp;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

