//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSMutableData, NSString, NSURLConnection;

@interface RCUpload : NSObject
{
    NSMutableData *_receivedData;
    long long _responseCode;
    NSData *_contentData;
    CDUnknownBlockType _progressBlock;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _failureBlock;
    CDUnknownBlockType _cancelBlock;
    CDUnknownBlockType _pauseBlock;
    NSString *_originalFileName;
    NSURLConnection *_urlConnection;
}

@property(retain, nonatomic) NSURLConnection *urlConnection; // @synthesize urlConnection=_urlConnection;
@property(copy, nonatomic) NSString *originalFileName; // @synthesize originalFileName=_originalFileName;
@property(copy, nonatomic) CDUnknownBlockType pauseBlock; // @synthesize pauseBlock=_pauseBlock;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
@property(copy, nonatomic) CDUnknownBlockType failureBlock; // @synthesize failureBlock=_failureBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(copy, nonatomic) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
@property(retain, nonatomic) NSData *contentData; // @synthesize contentData=_contentData;
@property(nonatomic) long long responseCode; // @synthesize responseCode=_responseCode;
@property(retain, nonatomic) NSMutableData *receivedData; // @synthesize receivedData=_receivedData;
- (void).cxx_destruct;
- (id)generateQiniuContentData:(id)arg1 uploadToken:(id)arg2 fileName:(id)arg3 mimeType:(id)arg4;
- (id)getUploadUrl;
- (void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;
- (void)resume;
- (void)pause;
- (void)cancel;
- (void)start;
- (id)initWithUploadToken:(id)arg1 fileName:(id)arg2 originalFileName:(id)arg3 mimeType:(id)arg4 data:(id)arg5 progress:(CDUnknownBlockType)arg6 success:(CDUnknownBlockType)arg7 failure:(CDUnknownBlockType)arg8 cancel:(CDUnknownBlockType)arg9 pause:(CDUnknownBlockType)arg10;

@end

