//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class RCMessage;

@interface RCUploadMediaStatusListener : NSObject
{
    RCMessage *_currentMessage;
    CDUnknownBlockType _updateBlock;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _errorBlock;
    CDUnknownBlockType _cancelBlock;
}

@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
@property(copy, nonatomic) CDUnknownBlockType errorBlock; // @synthesize errorBlock=_errorBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(copy, nonatomic) CDUnknownBlockType updateBlock; // @synthesize updateBlock=_updateBlock;
@property(retain, nonatomic) RCMessage *currentMessage; // @synthesize currentMessage=_currentMessage;
- (void).cxx_destruct;
- (void)cancelUpload;
- (id)initWithMessage:(id)arg1 uploadProgress:(CDUnknownBlockType)arg2 uploadSuccess:(CDUnknownBlockType)arg3 uploadError:(CDUnknownBlockType)arg4 uploadCancel:(CDUnknownBlockType)arg5;

@end

