//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface RCUtilities : NSObject
{
}

+ (_Bool)isOpaque:(id)arg1;
+ (unsigned long long)getMediaType:(id)arg1;
+ (id)getMediaTypeString:(unsigned long long)arg1;
+ (id)getNowrapString:(id)arg1;
+ (id)currentDeviceModel;
+ (id)currentSystemVersion;
+ (id)currentNetworkType;
+ (id)currentNetWork;
+ (id)currentCarrier;
+ (id)getDateFormatter;
+ (id)currentSystemTime;
+ (id)applicationDocumentsDirectory;
+ (id)rongImageCacheDirectory;
+ (id)rongDocumentsDirectory;
+ (_Bool)excludeBackupKeyForURL:(id)arg1;
+ (id)getFileStoragePath;
+ (id)getCorrectedFilePath:(id)arg1;
+ (_Bool)isRemoteUrl:(id)arg1;
+ (_Bool)isLocalPath:(id)arg1;
+ (struct CGSize)getTextDrawingSize:(id)arg1 font:(id)arg2 constrainedSize:(struct CGSize)arg3;
+ (id)compressedImage:(id)arg1 percent:(double)arg2;
+ (id)compressedImageAndScalingSize:(id)arg1 targetSize:(struct CGSize)arg2 percent:(double)arg3;
+ (id)compressedImageAndScalingSize:(id)arg1 targetSize:(struct CGSize)arg2 maxDataLen:(double)arg3;
+ (id)compressedImageWithMaxDataLength:(id)arg1 maxDataLength:(double)arg2;
+ (id)scaleToSize:(struct CGSize)arg1 original:(id)arg2;
+ (id)imageByScalingAndCropSize:(id)arg1 targetSize:(struct CGSize)arg2;
+ (id)generateThumbnail:(id)arg1 targetSize:(struct CGSize)arg2;
+ (id)scaleImage:(id)arg1 toScale:(float)arg2;
+ (id)base64EncodedStringFrom:(id)arg1;
+ (id)dataWithBase64EncodedString:(id)arg1;

@end

