//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SLCommonGroupListViewController.h"

@class NSMutableArray;

@interface RecommendListViewController : SLCommonGroupListViewController
{
    NSMutableArray *_datasource;
    long long _distance;
    long long _memberId;
    long long _page;
}

@property(nonatomic) long long page; // @synthesize page=_page;
@property(nonatomic) long long memberId; // @synthesize memberId=_memberId;
@property(nonatomic) long long distance; // @synthesize distance=_distance;
@property(retain, nonatomic) NSMutableArray *datasource; // @synthesize datasource=_datasource;
- (void).cxx_destruct;
- (void)beginPullUpRefreshingNew;
- (void)beginPullDownRefreshingNew;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)loadUI:(id)arg1;
- (void)loadData;
- (void)initSubviews;
- (id)title;
- (id)initWithDistance:(long long)arg1 memberId:(long long)arg2;

@end

