//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SSDKContext.h"

@interface SSDKContext (XML)
+ (void)hasGetAppKey:(id)arg1;
+ (void)load;
- (id)getMapPlistPath;
- (id)getShareSDKXMLPath;
- (void)checkPlatformConnectorWithType:(unsigned long long)arg1;
- (id)filtAppInfo:(id)arg1;
- (id)getAppInfoMapping;
- (id)getXMLString;
- (id)getAppInfoFromXML;
- (id)getAppKeyFromXML;
- (void)loadXMLAppSettings:(id)arg1;
- (void)setPlatformXMLConfig;
@end

