//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SWQRCodeManager : NSObject
{
}

+ (void)sw_FlashlightOn:(_Bool)arg1;
+ (id)sw_navigationItemTitleWithType:(long long)arg1;
+ (id)sw_metadataObjectTypesWithType:(long long)arg1;
+ (void)sw_checkAlbumAuthorizationStatusWithGrand:(CDUnknownBlockType)arg1;
+ (void)sw_checkCameraAuthorizationStatusWithGrand:(CDUnknownBlockType)arg1;

@end

