//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QDCommonViewController.h"

#import "AVCaptureMetadataOutputObjectsDelegate-Protocol.h"
#import "AVCaptureVideoDataOutputSampleBufferDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class AVCaptureSession, NSString, SWQRCodeConfig, SWScannerView;

@interface SWQRCodeViewController : QDCommonViewController <AVCaptureMetadataOutputObjectsDelegate, AVCaptureVideoDataOutputSampleBufferDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate>
{
    SWQRCodeConfig *_codeConfig;
    SWScannerView *_scannerView;
    AVCaptureSession *_session;
    CDUnknownBlockType _scanBlock;
}

@property(copy, nonatomic) CDUnknownBlockType scanBlock; // @synthesize scanBlock=_scanBlock;
@property(retain, nonatomic) AVCaptureSession *session; // @synthesize session=_session;
@property(retain, nonatomic) SWScannerView *scannerView; // @synthesize scannerView=_scannerView;
@property(retain, nonatomic) SWQRCodeConfig *codeConfig; // @synthesize codeConfig=_codeConfig;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)sw_didReadFromAlbumFailed;
- (void)sw_handleWithValue:(id)arg1;
- (void)pauseScanning;
- (void)resumeScanning;
- (void)appWillResignActive:(id)arg1;
- (void)appDidBecomeActive:(id)arg1;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)showAlbum;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)captureOutput:(id)arg1 didOutputMetadataObjects:(id)arg2 fromConnection:(id)arg3;
- (void)imagePicker;
- (void)_setupScanner;
- (void)_setupUI;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)initSubviews;
- (id)title;
- (void)dealloc;
- (id)initWithScanBlock:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

