//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIApplication.h>

@class NSString, NSURL;

@interface UIApplication (WLAdd)
+ (id)wl_sharedExtensionApplication;
+ (_Bool)wl_isAppExtension;
- (void)wl_decrementNetworkActivityCount;
- (void)wl_incrementNetworkActivityCount;
@property(readonly, nonatomic) float wl_cpuUsage;
@property(readonly, nonatomic) long long wl_memoryUsage;
@property(readonly, nonatomic) _Bool wl_isBeingDebugged;
@property(readonly, nonatomic) NSString *wl_appBuildVersion;
@property(readonly, nonatomic) NSString *wl_appVersion;
@property(readonly, nonatomic) NSString *wl_appBundleID;
@property(readonly, nonatomic) NSString *wl_appBundleName;
@property(readonly, nonatomic) _Bool wl_isPirated;
@property(readonly, nonatomic) NSString *wl_libraryPath;
@property(readonly, nonatomic) NSURL *wl_libraryURL;
@property(readonly, nonatomic) NSString *wl_cachesPath;
@property(readonly, nonatomic) NSURL *wl_cachesURL;
@property(readonly, nonatomic) NSString *wl_documentsPath;
@property(readonly, nonatomic) NSURL *wl_documentsURL;
@end

