//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class CALayer;

@interface UIControl (WLAdd)
+ (void)adean_UIControlHook;
+ (void)load;
- (void)adean_setHighlighted:(_Bool)arg1;
- (void)adean_setEnabled:(_Bool)arg1;
- (void)setGradientBackgroundWithColors:(id)arg1 locations:(id)arg2 startPoint:(struct CGPoint)arg3 endPoint:(struct CGPoint)arg4;
- (void)setGradientBackgroundWithColors:(id)arg1 gradientType:(long long)arg2;
@property(copy) CALayer *highligLayer;
@end

