//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIDevice.h>

@class NSArray, NSDate, NSString;

@interface UIDevice (WLAddForInfo)
+ (void)wl_checkDeviceOrientationPortrait;
+ (double)wl_systemVersion;
+ (id)wl_description;
@property(readonly, nonatomic) NSArray *wl_cpuUsagePerProcessor;
@property(readonly, nonatomic) float wl_cpuUsage;
@property(readonly, nonatomic) unsigned long long wl_cpuCount;
@property(readonly, nonatomic) long long wl_memoryPurgable;
@property(readonly, nonatomic) long long wl_memoryWired;
@property(readonly, nonatomic) long long wl_memoryInactive;
@property(readonly, nonatomic) long long wl_memoryActive;
@property(readonly, nonatomic) long long wl_memoryFree;
@property(readonly, nonatomic) long long wl_memoryUsed;
@property(readonly, nonatomic) long long wl_memoryTotal;
@property(readonly, nonatomic) long long wl_diskSpaceUsed;
@property(readonly, nonatomic) long long wl_diskSpaceFree;
@property(readonly, nonatomic) long long wl_diskSpace;
- (unsigned long long)wl_getNetworkTrafficBytes:(unsigned long long)arg1;
@property(readonly, nonatomic) NSString *wl_idForDevice;
@property(readonly, nonatomic) NSDate *wl_systemUptime;
@property(readonly, nonatomic) NSString *wl_machineModelSimpleName;
@property(readonly, nonatomic) NSString *wl_machineModelName;
@property(readonly, nonatomic) NSString *wl_machineModel;
@property(readonly, nonatomic) _Bool wl_canMakePhoneCalls;
@property(readonly, nonatomic) _Bool wl_isJailbroken;
@property(readonly, nonatomic) _Bool wl_isSimulator;
@property(readonly, nonatomic) _Bool wl_isPad;
@end

