//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIFont.h>

@interface UIFont (WLAdd)
+ (id)wl_dataFromCGFont:(struct CGFont *)arg1;
+ (id)wl_dataFromFont:(id)arg1;
+ (_Bool)wl_unloadFontFromData:(id)arg1;
+ (id)wl_loadFontFromData:(id)arg1;
+ (void)wl_unloadFontFromPath:(id)arg1;
+ (_Bool)wl_loadFontFromPath:(id)arg1;
+ (id)wl_fontWithCGFont:(struct CGFont *)arg1 size:(double)arg2;
+ (id)wl_fontWithCTFont:(struct __CTFont *)arg1;
- (struct CGFont *)CGFontRef;
- (const struct __CTFont *)CTFontRef;
- (id)wl_fontWithNormal;
- (id)wl_fontWithBoldItalic;
- (id)wl_fontWithItalic;
- (id)wl_fontWithBold;
@property(readonly, nonatomic) double wl_fontWeight;
@property(readonly, nonatomic) _Bool wl_isColorGlyphs;
@property(readonly, nonatomic) _Bool wl_isMonoSpace;
@property(readonly, nonatomic) _Bool wl_isItalic;
@property(readonly, nonatomic) _Bool wl_isBold;
@end

