//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

@interface UINavigationController (WLAdd)
- (void)removeSubVCWithRange:(struct _NSRange)arg1;
- (void)wl_removeSubviewControllerMiddle;
- (void)wl_removeSubviewControllerMiddleWithRange:(struct _NSRange)arg1;
- (void)wl_removeLastSecondSubviewControoler;
- (void)wl_removeSubviewControllerWithRange:(struct _NSRange)arg1;
- (void)wl_removeSubviewControllerWithIndex:(long long)arg1;
@end

