//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@interface UIScrollView (WLAdd)
- (void)wl_scrollToRightAnimated:(_Bool)arg1;
- (void)wl_scrollToLeftAnimated:(_Bool)arg1;
- (void)wl_scrollToBottomAnimated:(_Bool)arg1;
- (void)wl_scrollToTopAnimated:(_Bool)arg1;
- (void)wl_scrollToRight;
- (void)wl_scrollToLeft;
- (void)wl_scrollToBottom;
- (void)wl_scrollToTop;
- (id)wl_snapshotImage;
@end

