//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableView.h>

@interface UITableView (WLAdd)
- (void)wl_ReloadVisibleCellsWithRowAnimation:(long long)arg1;
- (void)wl_clearSelectedRowsAnimated:(_Bool)arg1;
- (void)wl_reloadSection:(unsigned long long)arg1 withRowAnimation:(long long)arg2;
- (void)wl_deleteSection:(unsigned long long)arg1 withRowAnimation:(long long)arg2;
- (void)wl_insertSection:(unsigned long long)arg1 withRowAnimation:(long long)arg2;
- (void)wl_deleteRowAtIndexPath:(id)arg1 withRowAnimation:(long long)arg2;
- (void)wl_reloadRowAtIndexPath:(id)arg1 withRowAnimation:(long long)arg2;
- (void)wl_insertRowAtIndexPath:(id)arg1 withRowAnimation:(long long)arg2;
- (void)wl_deleteRow:(unsigned long long)arg1 inSection:(unsigned long long)arg2 withRowAnimation:(long long)arg3;
- (void)wl_reloadRow:(unsigned long long)arg1 inSection:(unsigned long long)arg2 withRowAnimation:(long long)arg3;
- (void)wl_insertRow:(unsigned long long)arg1 inSection:(unsigned long long)arg2 withRowAnimation:(long long)arg3;
- (void)wl_scrollToRow:(unsigned long long)arg1 inSection:(unsigned long long)arg2 atScrollPosition:(long long)arg3 animated:(_Bool)arg4;
- (void)wl_updateWithBlock:(CDUnknownBlockType)arg1;
@end

