//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSDate;

@interface UIViewController (WLAdd)
+ (id)findTopViewController:(id)arg1;
+ (id)getCurrentViewCtrl;
+ (id)currentRootViewController;
+ (void)adean_ViewControllerHook;
+ (void)load;
- (id)wl_rootPresentingViewController;
- (void)wl_dismissToRootViewControllerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showViewControl:(id)arg1 sender:(id)arg2;
- (void)back;
- (id)wl_createCustomBtnWithImage:(id)arg1 title:(id)arg2 target:(id)arg3 action:(SEL)arg4;
- (id)wl_setNavRightButtonWithTitle:(id)arg1 image:(id)arg2 target:(id)arg3 action:(SEL)arg4;
- (id)wl_setRightItemWithTitle:(id)arg1 image:(id)arg2 target:(id)arg3 action:(SEL)arg4;
- (id)wl_setNavLeftButtonWithTitle:(id)arg1 image:(id)arg2 target:(id)arg3 action:(SEL)arg4;
- (id)wl_setLeftItemWithTitle:(id)arg1 image:(id)arg2 target:(id)arg3 action:(SEL)arg4;
@property(retain, nonatomic) NSDate *wl_endTime;
@property(retain, nonatomic) NSDate *wl_beginTime;
- (void)adean_viewDidLoad;
- (void)adean_viewDidDisappear:(_Bool)arg1;
- (void)adean_viewDidAppear:(_Bool)arg1;
@end

