//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (WLImagePicker)
- (void)showAlertViewWithTitle:(id)arg1;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)choosePictureimageBlock:(CDUnknownBlockType)arg1 successBlock:(CDUnknownBlockType)arg2 imagePickerFailedBlock:(CDUnknownBlockType)arg3;
- (void)choosePictureTitle:(id)arg1 actionButtonTitles:(id)arg2 imageBlock:(CDUnknownBlockType)arg3 successBlock:(CDUnknownBlockType)arg4 imagePickerFailedBlock:(CDUnknownBlockType)arg5;
@property(copy, nonatomic) CDUnknownBlockType failedBlock; // @dynamic failedBlock;
@property(copy, nonatomic) CDUnknownBlockType succesBlock; // @dynamic succesBlock;
@property(copy, nonatomic) CDUnknownBlockType imageBlock; // @dynamic imageBlock;
@property(nonatomic, getter=isEditingPhoto) _Bool editingPhoto;
@end

