//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (WLRoundedCorner)
+ (void)load;
- (void)wl_setWLRadius:(struct WLRadius)arg1 withBorderColor:(id)arg2 borderWidth:(double)arg3 backgroundColor:(id)arg4 backgroundImage:(id)arg5 contentMode:(long long)arg6 size:(struct CGSize)arg7;
- (void)wl_setWLRadius:(struct WLRadius)arg1 withBorderColor:(id)arg2 borderWidth:(double)arg3 backgroundColor:(id)arg4 backgroundImage:(id)arg5 contentMode:(long long)arg6;
- (void)wl_setCornerRadius:(double)arg1 withBorderColor:(id)arg2 borderWidth:(double)arg3 backgroundColor:(id)arg4 backgroundImage:(id)arg5 contentMode:(long long)arg6;
- (void)wl_setWLRadius:(struct WLRadius)arg1 withImage:(id)arg2 contentMode:(long long)arg3;
- (void)wl_setCornerRadius:(double)arg1 withImage:(id)arg2 contentMode:(long long)arg3;
- (void)wl_setWLRadius:(struct WLRadius)arg1 withImage:(id)arg2;
- (void)wl_setCornerRadius:(double)arg1 withImage:(id)arg2;
- (void)wl_setWLRadius:(struct WLRadius)arg1 withBackgroundColor:(id)arg2;
- (void)wl_setCornerRadius:(double)arg1 withBackgroundColor:(id)arg2;
- (void)wl_setWLRadius:(struct WLRadius)arg1 withBorderColor:(id)arg2 borderWidth:(double)arg3;
- (void)wl_setCornerRadius:(double)arg1 withBorderColor:(id)arg2 borderWidth:(double)arg3;
- (void)wl_cancelOperation;
- (void)wl_setOperation:(id)arg1;
- (id)wl_getOperation;
@end

