//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class IFriendModel, QMUIFillButton, QMUILabel, UIImageView;

@interface UserItemCollectionViewCell : UICollectionViewCell
{
    UIImageView *_logoImageView;
    QMUILabel *_titleLabel;
    IFriendModel *_friendModel;
    QMUIFillButton *_deleteBtn;
}

@property(retain, nonatomic) QMUIFillButton *deleteBtn; // @synthesize deleteBtn=_deleteBtn;
@property(retain, nonatomic) IFriendModel *friendModel; // @synthesize friendModel=_friendModel;
@property(retain, nonatomic) QMUILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
- (void).cxx_destruct;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1;

@end

