//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseModelClient.h"

@interface UserModelClient : BaseModelClient
{
}

+ (id)getSignRecordInfoWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getSigninInfoWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)signinWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)delBankCardListWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)addBankCardListWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getAliAccountListWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getBankCardListWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getLuckDrawWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getPosterWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)aliAccountDelWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)changeMobileWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getAliAccountDelSmsWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getCommonSmsWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getChangeMobileVcodeWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)setSecretFreeWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getUserSafeIndexWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getSystemCityListWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getRecommoneNextListWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getRecommoneListWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)setInviteCodeWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getUserQrcodeWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)resetPayPwdWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)forgetPayCheckVcodeWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)forgetPayPwdVcodeWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)changePayPwdWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)setPayPwdWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)transferWallentWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)withdrawWallentWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)withdrawInfoWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)aliPayLoginWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)offlineRechargeWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getOfflineInfoWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getRechargeInfoV2WithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getRechargeInfoWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)rechargeWallentWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getWallentWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getUserLogoWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)changeUserLogoWithParams:(id)arg1 image:(id)arg2 Success:(CDUnknownBlockType)arg3 Failed:(CDUnknownBlockType)arg4;
+ (id)changeUserInfoWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)commissionTransferWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;
+ (id)getUserInfoWithParams:(id)arg1 Success:(CDUnknownBlockType)arg2 Failed:(CDUnknownBlockType)arg3;

@end

