//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SLCommonGroupListViewController.h"

@class IFriendDetailInfoModel, NSString, QMUIFillButton, QMUILabel, RETableViewItem, RETableViewManager, UIImageView;

@interface UserInfoViewController : SLCommonGroupListViewController
{
    NSString *_userId;
    RETableViewManager *_manager;
    UIImageView *_logoImageView;
    QMUILabel *_nameLabel;
    UIImageView *_iconImageView;
    QMUILabel *_nickNameLabel;
    QMUILabel *_idLabel;
    QMUIFillButton *_sendBtn;
    QMUIFillButton *_deleteBtn;
    IFriendDetailInfoModel *_userModel;
    RETableViewItem *_nameItem;
}

@property(retain, nonatomic) RETableViewItem *nameItem; // @synthesize nameItem=_nameItem;
@property(retain, nonatomic) IFriendDetailInfoModel *userModel; // @synthesize userModel=_userModel;
@property(retain, nonatomic) QMUIFillButton *deleteBtn; // @synthesize deleteBtn=_deleteBtn;
@property(retain, nonatomic) QMUIFillButton *sendBtn; // @synthesize sendBtn=_sendBtn;
@property(retain, nonatomic) QMUILabel *idLabel; // @synthesize idLabel=_idLabel;
@property(retain, nonatomic) QMUILabel *nickNameLabel; // @synthesize nickNameLabel=_nickNameLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) QMUILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
@property(retain, nonatomic) RETableViewManager *manager; // @synthesize manager=_manager;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (void)deleteFriend;
- (void)deleteBtnClicked:(id)arg1;
- (void)sendBtn:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)addTableViewCell;
- (void)addTableHeaderInfo;
- (void)updateUI;
- (void)loadData;
- (void)viewDidLoad;
- (void)initSubviews;
- (id)title;

@end

