//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QMUIKit/QMUICommonViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class IWallentModel, NSMutableArray, NSString, QMUILabel, UITableView;

@interface WallentViewController : QMUICommonViewController <UITableViewDataSource, UITableViewDelegate>
{
    QMUILabel *_momeyLabel;
    QMUILabel *_balanceMomeyLabel;
    long long _selectType;
    long long _page;
    IWallentModel *_wallentModel;
    NSMutableArray *_datasource;
    UITableView *_tableView;
    QMUILabel *_noteLabel;
}

@property(retain, nonatomic) QMUILabel *noteLabel; // @synthesize noteLabel=_noteLabel;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSMutableArray *datasource; // @synthesize datasource=_datasource;
@property(retain, nonatomic) IWallentModel *wallentModel; // @synthesize wallentModel=_wallentModel;
@property(nonatomic) long long page; // @synthesize page=_page;
@property(nonatomic) long long selectType; // @synthesize selectType=_selectType;
@property(retain, nonatomic) QMUILabel *balanceMomeyLabel; // @synthesize balanceMomeyLabel=_balanceMomeyLabel;
@property(retain, nonatomic) QMUILabel *momeyLabel; // @synthesize momeyLabel=_momeyLabel;
- (void).cxx_destruct;
- (void)segmentedControlChangedValue:(id)arg1;
- (void)beginPullUpRefreshingNew;
- (void)beginPullDownRefreshingNew;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)titleViewTintColor;
- (id)navigationBarTintColor;
- (id)navigationBarShadowImage;
- (id)navigationBarBackgroundImage;
- (_Bool)shouldSetStatusBarStyleLight;
- (void)reloadUI;
- (void)loadData;
- (void)addHeaderView;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)initSubviews;
- (id)title;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

