//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QDCommonViewController.h"

@class ICardModel, IWallentInfoModel, LWLoginTextFieldView, NSString, QMUIFillButton, QMUILabel, QMUIModalPresentationViewController, QMUITextField, RETableViewManager, UISegmentedControl;

@interface WithdrawViewController : QDCommonViewController
{
    RETableViewManager *_manager;
    UISegmentedControl *_segmentedControl;
    LWLoginTextFieldView *_moenyTxtView;
    QMUILabel *_momeyLabel;
    LWLoginTextFieldView *_typeTxtView;
    LWLoginTextFieldView *_typeCardTxtView;
    QMUILabel *_aboutLabel;
    QMUIFillButton *_withdrawBtn;
    QMUITextField *_pwdTextField;
    QMUIModalPresentationViewController *_payModalViewController;
    IWallentInfoModel *_wallentInfoModel;
    NSString *_payPwd;
    long long _selectType;
    ICardModel *_selectCardModel;
    ICardModel *_selectAlipayModel;
}

@property(retain, nonatomic) ICardModel *selectAlipayModel; // @synthesize selectAlipayModel=_selectAlipayModel;
@property(retain, nonatomic) ICardModel *selectCardModel; // @synthesize selectCardModel=_selectCardModel;
@property(nonatomic) long long selectType; // @synthesize selectType=_selectType;
@property(retain, nonatomic) NSString *payPwd; // @synthesize payPwd=_payPwd;
@property(retain, nonatomic) IWallentInfoModel *wallentInfoModel; // @synthesize wallentInfoModel=_wallentInfoModel;
@property(retain, nonatomic) QMUIModalPresentationViewController *payModalViewController; // @synthesize payModalViewController=_payModalViewController;
@property(retain, nonatomic) QMUITextField *pwdTextField; // @synthesize pwdTextField=_pwdTextField;
@property(retain, nonatomic) QMUIFillButton *withdrawBtn; // @synthesize withdrawBtn=_withdrawBtn;
@property(retain, nonatomic) QMUILabel *aboutLabel; // @synthesize aboutLabel=_aboutLabel;
@property(retain, nonatomic) LWLoginTextFieldView *typeCardTxtView; // @synthesize typeCardTxtView=_typeCardTxtView;
@property(retain, nonatomic) LWLoginTextFieldView *typeTxtView; // @synthesize typeTxtView=_typeTxtView;
@property(retain, nonatomic) QMUILabel *momeyLabel; // @synthesize momeyLabel=_momeyLabel;
@property(retain, nonatomic) LWLoginTextFieldView *moenyTxtView; // @synthesize moenyTxtView=_moenyTxtView;
@property(retain, nonatomic) UISegmentedControl *segmentedControl; // @synthesize segmentedControl=_segmentedControl;
@property(retain, nonatomic) RETableViewManager *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (void)uploadMomeyLabel:(id)arg1;
- (void)controlChange:(id)arg1;
- (void)cancelBtnClicked:(id)arg1;
- (void)reloadData;
- (void)withdrawData:(id)arg1;
- (void)alipayUserId:(id)arg1;
- (void)payTypeSelect;
- (void)payBtnClicked:(id)arg1;
- (void)handelPayPassword;
- (void)inputPayPwd:(id)arg1;
- (void)withdrawBtnClicked:(id)arg1;
- (void)addViewConstraints;
- (void)updateSelectAlipayType;
- (void)updateSelectCardType;
- (void)checkSelectStatus:(long long)arg1;
- (void)addViews;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)shouldHideKeyboardWhenTouchInView:(id)arg1;
- (void)updateUi;
- (void)wainMessageAlert;
- (void)loadData;
- (void)initSubviews;
- (id)title;

@end

