//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface WLActionSheet : UIView
{
    long long _actionIndex;
    CDUnknownBlockType _actionSheetBlock;
    UIView *_backgroundView;
    UIView *_actionSheetView;
}

+ (void)showActionSheetWithTitle:(id)arg1 cancelButtonTitle:(id)arg2 destructiveButtonTitle:(id)arg3 otherButtonTitles:(id)arg4 handler:(CDUnknownBlockType)arg5;
+ (id)actionSheetWithTitle:(id)arg1 cancelButtonTitle:(id)arg2 destructiveButtonTitle:(id)arg3 otherButtonTitles:(id)arg4 handler:(CDUnknownBlockType)arg5;
@property(retain, nonatomic) UIView *actionSheetView; // @synthesize actionSheetView=_actionSheetView;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(copy, nonatomic) CDUnknownBlockType actionSheetBlock; // @synthesize actionSheetBlock=_actionSheetBlock;
@property(nonatomic) long long actionIndex; // @synthesize actionIndex=_actionIndex;
- (void).cxx_destruct;
- (void)dealloc;
- (id)imageWithColor:(id)arg1;
- (void)buttonClicked:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)dismiss;
- (void)show;
- (id)initWithTitle:(id)arg1 cancelButtonTitle:(id)arg2 destructiveButtonTitle:(id)arg3 otherButtonTitles:(id)arg4 handler:(CDUnknownBlockType)arg5;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

