//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, PHAsset;

@interface WLAsset : NSObject
{
    NSDictionary *_phAssetInfo;
    float imageSize;
    NSString *_assetIdentityHash;
    long long _assetType;
    PHAsset *_phAsset;
    long long _downloadStatus;
    double _downloadProgress;
    long long _requestID;
}

@property(nonatomic) long long requestID; // @synthesize requestID=_requestID;
@property(nonatomic) double downloadProgress; // @synthesize downloadProgress=_downloadProgress;
@property(readonly, nonatomic) long long downloadStatus; // @synthesize downloadStatus=_downloadStatus;
@property(retain, nonatomic) PHAsset *phAsset; // @synthesize phAsset=_phAsset;
@property(nonatomic) long long assetType; // @synthesize assetType=_assetType;
- (void).cxx_destruct;
- (long long)assetSize;
- (void)updateDownloadStatusWithDownloadResult:(_Bool)arg1;
- (int)requestImageDataWithCompletion:(CDUnknownBlockType)arg1 withProgressHandler:(CDUnknownBlockType)arg2;
- (void)requestPhAssetInfo;
- (id)assetIdentity;
- (long long)imageOrientation;
- (int)requestLivePhotoWithCompletion:(CDUnknownBlockType)arg1 withProgressHandler:(CDUnknownBlockType)arg2;
- (int)requestOriginImageWithCompletion:(CDUnknownBlockType)arg1 withProgressHandler:(CDUnknownBlockType)arg2;
- (int)requestPreviewImageWithCompletion:(CDUnknownBlockType)arg1 withProgressHandler:(CDUnknownBlockType)arg2;
- (int)requestThumbnailImageWithSize:(struct CGSize)arg1 completion:(CDUnknownBlockType)arg2;
- (id)previewImage;
- (id)thumbnailWithSize:(struct CGSize)arg1;
- (id)originImage;
- (id)initWithPHAsset:(id)arg1;

@end

