//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class PHCachingImageManager;

@interface WLAssetsManager : NSObject
{
    PHCachingImageManager *_phCachingImageManager;
}

+ (void)requestAuthorization:(CDUnknownBlockType)arg1;
+ (long long)authorizationStatus;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)phCachingImageManager;
- (void)saveVideoWithVideoPathURL:(id)arg1 albumAssetsGroup:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)saveImageWithImageRef:(struct CGImage *)arg1 albumAssetsGroup:(id)arg2 orientation:(long long)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)enumerateAllAlbumsWithAlbumContentType:(long long)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)enumerateAllAlbumsWithAlbumContentType:(long long)arg1 showEmptyAlbum:(_Bool)arg2 showSmartAlbumIfSupported:(_Bool)arg3 usingBlock:(CDUnknownBlockType)arg4;

@end

