//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel;

@interface WLAssetsGroupCell : UITableViewCell
{
    UIImageView *_photoView;
    UILabel *_photoName;
    UILabel *_photoNumbar;
}

@property(nonatomic) __weak UILabel *photoNumbar; // @synthesize photoNumbar=_photoNumbar;
@property(nonatomic) __weak UILabel *photoName; // @synthesize photoName=_photoName;
@property(nonatomic) __weak UIImageView *photoView; // @synthesize photoView=_photoView;
- (void).cxx_destruct;
- (void)setup;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

