//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WLRequestDelegate-Protocol.h"

@class NSArray, NSString;
@protocol WLBatchRequestInfoDelegate;

@interface WLBatchRequest : NSObject <WLRequestDelegate>
{
    NSArray *_requestArray;
    long long _queueType;
    id <WLBatchRequestInfoDelegate> _delegate;
    CDUnknownBlockType _successCompletionBlock;
    CDUnknownBlockType _failureCompletionBlock;
    long long _finishedCount;
}

@property(nonatomic) long long finishedCount; // @synthesize finishedCount=_finishedCount;
@property(copy, nonatomic) CDUnknownBlockType failureCompletionBlock; // @synthesize failureCompletionBlock=_failureCompletionBlock;
@property(copy, nonatomic) CDUnknownBlockType successCompletionBlock; // @synthesize successCompletionBlock=_successCompletionBlock;
@property(nonatomic) __weak id <WLBatchRequestInfoDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) long long queueType; // @synthesize queueType=_queueType;
@property(readonly, nonatomic) NSArray *requestArray; // @synthesize requestArray=_requestArray;
- (void).cxx_destruct;
- (void)cancelAllRequest;
- (void)clearRequest;
- (void)requestFailed:(id)arg1;
- (void)requestFinished:(id)arg1;
- (void)clearCompletionBlock;
- (void)setCompletionBlockWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)startWithCompletionBlockWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)stop;
- (void)start;
- (id)initWithRequestArray:(id)arg1 queueType:(long long)arg2;
- (id)initWithRequestArray:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

