//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCConversationViewController.h"

#import "RCMessageCellDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "WLPhotoViewControllerDelegate-Protocol.h"

@class NSString, RCConversationModel;

@interface WLChatBaseViewController : RCConversationViewController <UIImagePickerControllerDelegate, RCMessageCellDelegate, WLPhotoViewControllerDelegate>
{
    RCConversationModel *_conversation;
}

@property(retain, nonatomic) RCConversationModel *conversation; // @synthesize conversation=_conversation;
- (void).cxx_destruct;
- (void)clickSheetCamera;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)pluginBoardView:(id)arg1 clickedItemWithTag:(long long)arg2;
- (void)onCancelRecordEvent;
- (void)onEndRecordEvent;
- (void)onBeginRecordEvent;
- (void)didTapPhoneNumberInMessageCell:(id)arg1 model:(id)arg2;
- (void)didTapUrlInMessageCell:(id)arg1 model:(id)arg2;
- (void)willDisplayMessageCell:(id)arg1 atIndexPath:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)viewDidLoad;
- (id)initWithConversationType:(unsigned long long)arg1 targetId:(id)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

