//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString, UIColor, UIFont, UIImage;

@interface WLEmptyAssistantConfiger : NSObject <NSCopying>
{
    _Bool _buttonAllowTouch;
    _Bool _blankdAllowTouch;
    _Bool _isFirstLoading;
    UIImage *_emptyImage;
    NSString *_emptyTitle;
    UIFont *_emptyTitleFont;
    UIColor *_emptyTitleColor;
    NSString *_emptySubtitle;
    UIFont *_emptySubtitleFont;
    UIColor *_emptySubtitleColor;
    UIFont *_emptyBtntitleFont;
    UIColor *_emptyBtntitleColor;
    NSString *_emptyBtnImage;
    CDUnknownBlockType _shouldDisplay;
}

@property(copy, nonatomic) CDUnknownBlockType shouldDisplay; // @synthesize shouldDisplay=_shouldDisplay;
@property(nonatomic) _Bool isFirstLoading; // @synthesize isFirstLoading=_isFirstLoading;
@property(nonatomic) _Bool blankdAllowTouch; // @synthesize blankdAllowTouch=_blankdAllowTouch;
@property(nonatomic) _Bool buttonAllowTouch; // @synthesize buttonAllowTouch=_buttonAllowTouch;
@property(retain, nonatomic) NSString *emptyBtnImage; // @synthesize emptyBtnImage=_emptyBtnImage;
@property(retain, nonatomic) UIColor *emptyBtntitleColor; // @synthesize emptyBtntitleColor=_emptyBtntitleColor;
@property(retain, nonatomic) UIFont *emptyBtntitleFont; // @synthesize emptyBtntitleFont=_emptyBtntitleFont;
@property(retain, nonatomic) UIColor *emptySubtitleColor; // @synthesize emptySubtitleColor=_emptySubtitleColor;
@property(retain, nonatomic) UIFont *emptySubtitleFont; // @synthesize emptySubtitleFont=_emptySubtitleFont;
@property(copy, nonatomic) NSString *emptySubtitle; // @synthesize emptySubtitle=_emptySubtitle;
@property(retain, nonatomic) UIColor *emptyTitleColor; // @synthesize emptyTitleColor=_emptyTitleColor;
@property(retain, nonatomic) UIFont *emptyTitleFont; // @synthesize emptyTitleFont=_emptyTitleFont;
@property(copy, nonatomic) NSString *emptyTitle; // @synthesize emptyTitle=_emptyTitle;
@property(retain, nonatomic) UIImage *emptyImage; // @synthesize emptyImage=_emptyImage;
- (void).cxx_destruct;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

