//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WLHUDView : NSObject
{
}

+ (void)hiddenHud;
+ (id)showHUDWithStr:(id)arg1 dim:(_Bool)arg2;
+ (void)showCustomHUD:(id)arg1 imageview:(id)arg2 time:(double)arg3;
+ (void)showCustomHUD:(id)arg1 imageview:(id)arg2;
+ (void)showErrorHUD:(id)arg1 Duration:(double)arg2;
+ (void)showNetWorkError;
+ (void)showErrorHUD:(id)arg1;
+ (void)showSuccessHUD:(id)arg1;
+ (void)showAttentionHUD:(id)arg1;
+ (void)showOnlyTextHUD:(id)arg1;
+ (id)window;

@end

