//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel, UIProgressView;

@interface WLHubProgressView : UIView
{
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    UIProgressView *_progressView;
}

@property(nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)updateProgress:(double)arg1;
- (void)updateSueccess;
- (void)initUIDataShowWithDetailInfo:(id)arg1;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1;

@end

