//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIButton, UITextField;

@interface WLLoginTextField : UIView
{
    NSString *_areaCode;
    UITextField *_textField;
    CDUnknownBlockType _areaChangedBlock;
    long long _textFieldType;
    UIButton *_areaCodeButton;
    UIButton *_plaintextButton;
}

@property(retain, nonatomic) UIButton *plaintextButton; // @synthesize plaintextButton=_plaintextButton;
@property(retain, nonatomic) UIButton *areaCodeButton; // @synthesize areaCodeButton=_areaCodeButton;
@property(nonatomic) long long textFieldType; // @synthesize textFieldType=_textFieldType;
@property(copy, nonatomic) CDUnknownBlockType areaChangedBlock; // @synthesize areaChangedBlock=_areaChangedBlock;
@property(retain, nonatomic) UITextField *textField; // @synthesize textField=_textField;
@property(copy, nonatomic) NSString *areaCode; // @synthesize areaCode=_areaCode;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *phone;
- (void)showPhoneNumberSaved;
- (void)passwordTextFieldPlaintext;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithTextFieldType:(long long)arg1;

@end

