//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary;

@protocol WLNetwokingProcessDelegate <NSObject>
- (_Bool)processResponseWithError:(id)arg1 errorType:(unsigned long long)arg2;
- (id)processResponseWithRequest:(id)arg1 ignoreDecryptAES256:(_Bool)arg2;
- (NSDictionary *)urlArgumentsInfos;
- (NSDictionary *)httpHeaderInfos;
@end

