//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WLNetwokingProcessDelegate-Protocol.h"

@class NSString;

@interface WLNetWorkingProcessFilter : NSObject <WLNetwokingProcessDelegate>
{
}

+ (void)checkErrorWithRequest:(id)arg1 customMsg:(id)arg2;
- (_Bool)processResponseWithError:(id)arg1 errorType:(unsigned long long)arg2;
- (id)processResponseWithRequest:(id)arg1 ignoreDecryptAES256:(_Bool)arg2;
- (id)httpHeaderInfos;
- (id)urlArgumentsInfos;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

