//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AFHTTPRequestSerializer, AFHTTPResponseSerializer, AFHTTPSessionManager;

@interface WLNetworkManager : NSObject
{
    AFHTTPRequestSerializer *_requestSerializer;
    AFHTTPResponseSerializer *_responseSerializer;
    double _timeOutInterval;
    AFHTTPSessionManager *_manager;
}

+ (_Bool)extractIdentity:(struct __SecIdentity **)arg1 andTrust:(struct __SecTrust **)arg2 fromPKCS12Data:(id)arg3;
@property(retain, nonatomic) AFHTTPSessionManager *manager; // @synthesize manager=_manager;
@property(nonatomic) double timeOutInterval; // @synthesize timeOutInterval=_timeOutInterval;
@property(retain, nonatomic) AFHTTPResponseSerializer *responseSerializer; // @synthesize responseSerializer=_responseSerializer;
@property(retain, nonatomic) AFHTTPRequestSerializer *requestSerializer; // @synthesize requestSerializer=_requestSerializer;
- (void).cxx_destruct;
- (void)loadHttpsConfig;
- (id)customSecurityPolicy;
- (id)wl_updateFileWithUrlString:(id)arg1 parameters:(id)arg2 image:(id)arg3 SuccessBlock:(CDUnknownBlockType)arg4 FailureBlock:(CDUnknownBlockType)arg5 DownLoadProgress:(CDUnknownBlockType)arg6;
- (id)wl_downLoadFileWithUrlString:(id)arg1 parameters:(id)arg2 SavaPath:(id)arg3 SuccessBlock:(CDUnknownBlockType)arg4 FailureBlock:(CDUnknownBlockType)arg5 DownLoadProgress:(CDUnknownBlockType)arg6;
- (id)wl_requestWithType:(unsigned long long)arg1 UrlString:(id)arg2 Parameters:(id)arg3 SuccessBlock:(CDUnknownBlockType)arg4 FailureBlock:(CDUnknownBlockType)arg5;

@end

