//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AFSecurityPolicy, NSDictionary, NSString;
@protocol WLNetwokingProcessDelegate;

@interface WLNetwokingConfig : NSObject
{
    _Bool _isNetWorkConnect;
    id <WLNetwokingProcessDelegate> _processRule;
    AFSecurityPolicy *_securityPolicy;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool isNetWorkConnect; // @synthesize isNetWorkConnect=_isNetWorkConnect;
@property(retain, nonatomic) AFSecurityPolicy *securityPolicy; // @synthesize securityPolicy=_securityPolicy;
@property(retain, nonatomic) id <WLNetwokingProcessDelegate> processRule; // @synthesize processRule=_processRule;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *urlArguments;
@property(readonly, nonatomic) NSString *appVersion;
@property(readonly, nonatomic) _Bool isReachableViaWiFi;
@property(readonly, nonatomic) _Bool openHttpsSSL;
@property(readonly, nonatomic) _Bool isReachable;
- (void)cancelAllRequests;
- (void)checkReachableStatus;
- (id)init;

@end

