//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class NSString, UIButton, UIImageView, UILabel, WLMessageTextView;

@interface WLNormalInputAlertView : UIView <UIGestureRecognizerDelegate, UITextViewDelegate>
{
    CDUnknownBlockType _cancelBtnClickedBlock;
    CDUnknownBlockType _okBtnClickedBlock;
    double _InputViewHeight;
    double _maxInputLimit;
    UIImageView *_bgImageView;
    UIView *_contentView;
    WLMessageTextView *_textView;
    UIButton *_cancelBtn;
    UIButton *_sendBtn;
    UILabel *_titleLabel;
    UILabel *_detailTitleLabel;
    NSString *_title;
    NSString *_msg;
    NSString *_placeHolderStr;
    NSString *_cancelButtonTitle;
    NSString *_otherButtonTitle;
}

@property(retain, nonatomic) NSString *otherButtonTitle; // @synthesize otherButtonTitle=_otherButtonTitle;
@property(retain, nonatomic) NSString *cancelButtonTitle; // @synthesize cancelButtonTitle=_cancelButtonTitle;
@property(retain, nonatomic) NSString *placeHolderStr; // @synthesize placeHolderStr=_placeHolderStr;
@property(retain, nonatomic) NSString *msg; // @synthesize msg=_msg;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) UILabel *detailTitleLabel; // @synthesize detailTitleLabel=_detailTitleLabel;
@property(nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) UIButton *sendBtn; // @synthesize sendBtn=_sendBtn;
@property(nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(nonatomic) WLMessageTextView *textView; // @synthesize textView=_textView;
@property(nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(nonatomic) double maxInputLimit; // @synthesize maxInputLimit=_maxInputLimit;
@property(nonatomic) double InputViewHeight; // @synthesize InputViewHeight=_InputViewHeight;
@property(copy, nonatomic) CDUnknownBlockType okBtnClickedBlock; // @synthesize okBtnClickedBlock=_okBtnClickedBlock;
@property(copy, nonatomic) CDUnknownBlockType cancelBtnClickedBlock; // @synthesize cancelBtnClickedBlock=_cancelBtnClickedBlock;
- (void).cxx_destruct;
- (void)fadeOut;
- (void)fadeIn;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)textViewEditChanged:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)dismiss;
- (void)show;
- (void)sendBtnClicked:(id)arg1;
- (void)cancelBtnClicked:(id)arg1;
- (double)getContentHeight;
- (void)setup;
- (void)layoutSubviews;
- (id)initWithTitle:(id)arg1 message:(id)arg2 placeHolderStr:(id)arg3 cancelButtonTitle:(id)arg4 otherButtonTitle:(id)arg5;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

