//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIAlertController.h>

@interface WLPackAlertController : UIAlertController
{
}

+ (id)alertWithTitle:(id)arg1 message:(id)arg2 alertStyle:(long long)arg3 cancelColor:(id)arg4 cancelText:(id)arg5 destructiveText:(id)arg6 cancelHandler:(CDUnknownBlockType)arg7 destructiveHandler:(CDUnknownBlockType)arg8;
+ (id)alertWithTitle:(id)arg1 message:(id)arg2 alertStyle:(long long)arg3 text1:(id)arg4 text2:(id)arg5 text3:(id)arg6 handler1:(CDUnknownBlockType)arg7 handler2:(CDUnknownBlockType)arg8 handler3:(CDUnknownBlockType)arg9;
+ (id)alertWithTitle:(id)arg1 message:(id)arg2 alertStyle:(long long)arg3 text1:(id)arg4 text2:(id)arg5 handler1:(CDUnknownBlockType)arg6 handler2:(CDUnknownBlockType)arg7;
+ (id)alertWithTitle:(id)arg1 message:(id)arg2 alertStyle:(long long)arg3 color1:(id)arg4 color2:(id)arg5 text1:(id)arg6 text2:(id)arg7 handler1:(CDUnknownBlockType)arg8 handler2:(CDUnknownBlockType)arg9;
+ (id)alertWithTitle:(id)arg1 message:(id)arg2 alertStyle:(long long)arg3 cancelText:(id)arg4 text1:(id)arg5 cancelHandler:(CDUnknownBlockType)arg6 handler1:(CDUnknownBlockType)arg7;
+ (id)alertWithTitle:(id)arg1 message:(id)arg2 alertStyle:(long long)arg3 cancelColor:(id)arg4 color1:(id)arg5 cancelText:(id)arg6 text1:(id)arg7 cancelHandler:(CDUnknownBlockType)arg8 handler1:(CDUnknownBlockType)arg9;
+ (id)alertWithTitle:(id)arg1 message:(id)arg2 alertStyle:(long long)arg3 actionStyle:(long long)arg4 text1:(id)arg5 handler1:(CDUnknownBlockType)arg6;
- (void)showWithPresentingViewController:(id)arg1;
- (void)show;

@end

