//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary, NSObject, NSString, WLPersistanceTable;
@protocol WLPersistanceRecordProtocol, WLPersistanceTableProtocol;

@protocol WLPersistanceRecordProtocol <NSObject>
- (NSObject<WLPersistanceRecordProtocol> *)mergeRecord:(NSObject<WLPersistanceRecordProtocol> *)arg1 shouldOverride:(_Bool)arg2;
- (_Bool)setPersistanceValue:(id)arg1 forKey:(NSString *)arg2;
- (void)objectRepresentationWithDictionary:(NSDictionary *)arg1;
- (NSDictionary *)dictionaryRepresentationWithTable:(WLPersistanceTable<WLPersistanceTableProtocol> *)arg1;

@optional
- (NSArray *)availableKeyList;
@end

