//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, UIImage, YYAnimatedImageView;

@interface WLPhoto3DTouchViewController : UIViewController
{
    UIImage *_image;
    NSString *_imageUrlString;
    YYAnimatedImageView *_imageView;
}

@property(retain, nonatomic) YYAnimatedImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) NSString *imageUrlString; // @synthesize imageUrlString=_imageUrlString;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (id)previewActionItems;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

