//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIPageViewControllerDataSource-Protocol.h"
#import "UIPageViewControllerDelegate-Protocol.h"
#import "WLPhotoPreviewItemControllerDelegate-Protocol.h"

@class NSMutableArray, NSString, UIPageViewController, WLNavbarView, WLPhotoBottomView;
@protocol WLPhotoPreviewControllerDelegate;

@interface WLPhotoPreviewController : UIViewController <UIPageViewControllerDelegate, UIPageViewControllerDataSource, WLPhotoPreviewItemControllerDelegate>
{
    _Bool _isShowNavBar;
    id <WLPhotoPreviewControllerDelegate> _delegate;
    long long _currentImageIndex;
    long long _maximumSelectImageCount;
    long long _minimumSelectImageCount;
    NSMutableArray *_imagesAssetArray;
    NSMutableArray *_selectedImageAssetArray;
    UIPageViewController *_pageVC;
    WLNavbarView *_navBarView;
    WLPhotoBottomView *_bottomView;
}

@property(nonatomic) _Bool isShowNavBar; // @synthesize isShowNavBar=_isShowNavBar;
@property(retain, nonatomic) WLPhotoBottomView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) WLNavbarView *navBarView; // @synthesize navBarView=_navBarView;
@property(nonatomic) __weak UIPageViewController *pageVC; // @synthesize pageVC=_pageVC;
@property(retain, nonatomic) NSMutableArray *selectedImageAssetArray; // @synthesize selectedImageAssetArray=_selectedImageAssetArray;
@property(retain, nonatomic) NSMutableArray *imagesAssetArray; // @synthesize imagesAssetArray=_imagesAssetArray;
@property(nonatomic) long long minimumSelectImageCount; // @synthesize minimumSelectImageCount=_minimumSelectImageCount;
@property(nonatomic) long long maximumSelectImageCount; // @synthesize maximumSelectImageCount=_maximumSelectImageCount;
@property(nonatomic) long long currentImageIndex; // @synthesize currentImageIndex=_currentImageIndex;
@property(nonatomic) __weak id <WLPhotoPreviewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)backItemClick;
- (void)navBarTitleIndex:(long long)arg1;
- (void)handleCheckDoenButtonClick;
- (id)newPhotoPreviewItemControllerWithIndex:(long long)arg1;
- (void)updateImageCountAndCheckLimited;
- (void)handleCheckBoxButtonClick;
- (void)singleTouchInPhotoPreviewItemControllerZoomingImageView:(id)arg1;
- (void)pageViewController:(id)arg1 didFinishAnimating:(_Bool)arg2 previousViewControllers:(id)arg3 transitionCompleted:(_Bool)arg4;
- (id)pageViewController:(id)arg1 viewControllerAfterViewController:(id)arg2;
- (id)pageViewController:(id)arg1 viewControllerBeforeViewController:(id)arg2;
- (void)didSelectItemAtIndex:(long long)arg1;
- (void)viewDidLoad;
- (id)init;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)prefersHomeIndicatorAutoHidden;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

