//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, UIImage;

@interface WLRequestCriteria : NSObject
{
    _Bool _shouldCache;
    _Bool _ignoreUnifiedResponseProcess;
    _Bool _ignoreUnifiedErrorProcess;
    _Bool _removesKeysWithNullValues;
    _Bool _ignoreDecryptAES256Value;
    _Bool _ignoreHttpHeader;
    NSString *_apiMethodName;
    NSDictionary *_requestParams;
    NSString *_fileFolderName;
    UIImage *_updateImage;
    long long _cacheTimeInSeconds;
    double _requestTimeoutInterval;
    unsigned long long _requestMethodType;
    long long _requestSerializerType;
    long long _reponseSerializerType;
    unsigned long long _requestCoverType;
    NSDictionary *_httpHeader;
}

@property(retain, nonatomic) NSDictionary *httpHeader; // @synthesize httpHeader=_httpHeader;
@property(nonatomic) _Bool ignoreHttpHeader; // @synthesize ignoreHttpHeader=_ignoreHttpHeader;
@property(nonatomic) _Bool ignoreDecryptAES256Value; // @synthesize ignoreDecryptAES256Value=_ignoreDecryptAES256Value;
@property(nonatomic) unsigned long long requestCoverType; // @synthesize requestCoverType=_requestCoverType;
@property(nonatomic) _Bool removesKeysWithNullValues; // @synthesize removesKeysWithNullValues=_removesKeysWithNullValues;
@property(nonatomic) long long reponseSerializerType; // @synthesize reponseSerializerType=_reponseSerializerType;
@property(nonatomic) long long requestSerializerType; // @synthesize requestSerializerType=_requestSerializerType;
@property(nonatomic) unsigned long long requestMethodType; // @synthesize requestMethodType=_requestMethodType;
@property(nonatomic) _Bool ignoreUnifiedErrorProcess; // @synthesize ignoreUnifiedErrorProcess=_ignoreUnifiedErrorProcess;
@property(nonatomic) _Bool ignoreUnifiedResponseProcess; // @synthesize ignoreUnifiedResponseProcess=_ignoreUnifiedResponseProcess;
@property(nonatomic) double requestTimeoutInterval; // @synthesize requestTimeoutInterval=_requestTimeoutInterval;
@property(nonatomic) long long cacheTimeInSeconds; // @synthesize cacheTimeInSeconds=_cacheTimeInSeconds;
@property(nonatomic) _Bool shouldCache; // @synthesize shouldCache=_shouldCache;
@property(retain, nonatomic) UIImage *updateImage; // @synthesize updateImage=_updateImage;
@property(copy, nonatomic) NSString *fileFolderName; // @synthesize fileFolderName=_fileFolderName;
@property(copy, nonatomic) NSDictionary *requestParams; // @synthesize requestParams=_requestParams;
@property(copy, nonatomic) NSString *apiMethodName; // @synthesize apiMethodName=_apiMethodName;
- (void).cxx_destruct;
- (id)init;

@end

