//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, WLNetworkManager;

@interface WLRequestManager : NSObject
{
    WLNetworkManager *_netWorkManager;
    NSMutableDictionary *_requestsRecord;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *requestsRecord; // @synthesize requestsRecord=_requestsRecord;
@property(retain, nonatomic) WLNetworkManager *netWorkManager; // @synthesize netWorkManager=_netWorkManager;
- (void).cxx_destruct;
- (void)removeOperation:(id)arg1;
- (void)addOperation:(id)arg1;
- (id)requestHashKey:(id)arg1;
- (void)requestFaieldWithRequest:(id)arg1;
- (void)requestSuccessWithRequest:(id)arg1;
- (void)handleRequestResult:(id)arg1 responseObject:(id)arg2;
- (void)wl_addRequst:(id)arg1;
- (void)wl_cancelRequest:(id)arg1;
- (void)cancelAllRequests;
- (void)cancelRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addRequest:(id)arg1;
- (id)init;

@end

