//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AFHTTPRequestSerializer, AFHTTPResponseSerializer, NSDictionary, NSError, NSString, NSURLSessionTask, UIImage, WLNetwokingConfig, WLRequestCriteria;
@protocol WLRequestAPIDelegate, WLRequestDelegate;

@interface WLRequest : NSObject
{
    _Bool _isIgnoreResponseError;
    id _responseJSONObject;
    NSError *_error;
    NSURLSessionTask *_requestDataTask;
    unsigned long long _errorType;
    WLRequestCriteria *_requestCriteria;
    id <WLRequestDelegate> _delegate;
    id <WLRequestAPIDelegate> _childApi;
    CDUnknownBlockType _successCompletionBlock;
    CDUnknownBlockType _failureCompletionBlock;
    CDUnknownBlockType _progress;
    WLNetwokingConfig *_config;
    AFHTTPRequestSerializer *_requestSerializer;
    AFHTTPResponseSerializer *_responseSerializer;
}

@property(retain, nonatomic) AFHTTPResponseSerializer *responseSerializer; // @synthesize responseSerializer=_responseSerializer;
@property(retain, nonatomic) AFHTTPRequestSerializer *requestSerializer; // @synthesize requestSerializer=_requestSerializer;
@property(retain, nonatomic) WLNetwokingConfig *config; // @synthesize config=_config;
@property(copy, nonatomic) CDUnknownBlockType progress; // @synthesize progress=_progress;
@property(copy, nonatomic) CDUnknownBlockType failureCompletionBlock; // @synthesize failureCompletionBlock=_failureCompletionBlock;
@property(copy, nonatomic) CDUnknownBlockType successCompletionBlock; // @synthesize successCompletionBlock=_successCompletionBlock;
@property(nonatomic) __weak id <WLRequestAPIDelegate> childApi; // @synthesize childApi=_childApi;
@property(nonatomic) __weak id <WLRequestDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WLRequestCriteria *requestCriteria; // @synthesize requestCriteria=_requestCriteria;
@property(nonatomic) unsigned long long errorType; // @synthesize errorType=_errorType;
@property(retain, nonatomic) NSURLSessionTask *requestDataTask; // @synthesize requestDataTask=_requestDataTask;
@property(nonatomic) _Bool isIgnoreResponseError; // @synthesize isIgnoreResponseError=_isIgnoreResponseError;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) id responseJSONObject; // @synthesize responseJSONObject=_responseJSONObject;
- (void).cxx_destruct;
- (unsigned long long)requestCoverTypeInfo;
@property(readonly, nonatomic) unsigned long long requestMethodType;
@property(readonly, nonatomic) _Bool ignoreDecryptAES256Value;
@property(readonly, nonatomic) _Bool ignoreUnifiedErrorProcess;
@property(readonly, nonatomic) _Bool ignoreUnifiedResponse;
@property(readonly, nonatomic) double timeOutInterval;
@property(readonly, nonatomic) NSDictionary *requestParamInfos;
@property(readonly, nonatomic) UIImage *updateImage;
@property(readonly, copy, nonatomic) NSString *downfileFolderName;
@property(readonly, copy, nonatomic) NSString *apiMethodName;
@property(readonly, nonatomic) _Bool isReachable;
@property(readonly, nonatomic) NSDictionary *responseHeaders;
@property(readonly, nonatomic) long long responseStatusCode;
- (_Bool)statusCodeValidator;
- (_Bool)ignoreUnifiedResponseProcess;
- (void)requestResponseJsonObjectFilter;
- (void)requestFailedFilter;
- (void)clearCompletionBlock;
- (void)startWithCompletionBlockWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2 progress:(CDUnknownBlockType)arg3;
- (void)startWithCompletionBlockWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)stop;
- (void)start;
- (id)initWithApiMethodName:(id)arg1 requestParams:(id)arg2;
- (id)initWithRequestCriteria:(id)arg1;
- (id)init;
- (id)cacheTimeKey;
- (id)cacheFileKey;
- (void)saveCacheTimeForData;
- (long long)cacheTimeAgo;
- (id)localCacheTime;
- (id)buildRequestUrl;
- (void)saveDataInfoToCache:(id)arg1;
@property(readonly, copy, nonatomic) NSString *urlString;
- (unsigned long long)paramsStringHash;
- (unsigned long long)urlStringHash;
@property(readonly, nonatomic) long long cacheTime;
@property(readonly, nonatomic) _Bool isCacheTimeValidator;
@property(readonly, nonatomic) id cacheObject;
@property(readonly, nonatomic) _Bool hasCached;
@property(readonly, nonatomic) _Bool isNeedCache;

@end

