//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "RCIMGroupInfoDataSource-Protocol.h"
#import "RCIMGroupMemberDataSource-Protocol.h"
#import "RCIMUserInfoDataSource-Protocol.h"

@class NSString;

@interface WLRongCloudDataSource : NSObject <RCIMUserInfoDataSource, RCIMGroupInfoDataSource, RCIMGroupMemberDataSource>
{
}

+ (id)shareInstance;
- (void)refreshLogUserInfoCache:(id)arg1;
- (void)getAllMembersOfGroup:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)getUserInfoWithUserId:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getGroupInfoWithGroupId:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getLocalGroupInfoWithGroupId:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getLocalUserInfoWithUserId:(id)arg1 completion:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

