//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "DZNEmptyDataSetDelegate-Protocol.h"
#import "DZNEmptyDataSetSource-Protocol.h"

@class NSString, UIScrollView, WLEmptyAssistantConfiger, WLEmptyAssistantDataSet;

@interface WLScrollViewEmptyAssistant : NSObject <DZNEmptyDataSetSource, DZNEmptyDataSetDelegate>
{
    UIScrollView *_emptyContentView;
    unsigned long long _emptyViewType;
    WLEmptyAssistantConfiger *_emptyConfiger;
    WLEmptyAssistantConfiger *_normalemptyConfiger;
    WLEmptyAssistantConfiger *_loadingConfiger;
    WLEmptyAssistantConfiger *_normalLoadingConfiger;
    WLEmptyAssistantConfiger *_netWorkConfiger;
    NSString *_emptyBtnTitle;
    CDUnknownBlockType _emptyBtnActionBlock;
    CDUnknownBlockType _emptyViewActionBlock;
    WLEmptyAssistantDataSet *_dataSet;
}

+ (id)emptyWithContentView:(id)arg1 dataSetBlock:(CDUnknownBlockType)arg2 configerBlock:(CDUnknownBlockType)arg3 emptyBtnTitle:(id)arg4 emptyBtnActionBlock:(CDUnknownBlockType)arg5 emptyTapViewActionBlock:(CDUnknownBlockType)arg6;
+ (id)emptyWithContentView:(id)arg1 configerBlock:(CDUnknownBlockType)arg2 emptyBtnTitle:(id)arg3 emptyBtnActionBlock:(CDUnknownBlockType)arg4 emptyTapViewActionBlock:(CDUnknownBlockType)arg5;
+ (id)emptyWithContentView:(id)arg1 configerBlock:(CDUnknownBlockType)arg2 emptyTapViewActionBlock:(CDUnknownBlockType)arg3;
+ (id)emptyWithContentView:(id)arg1 dataSetBlock:(CDUnknownBlockType)arg2 configerBlock:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) WLEmptyAssistantDataSet *dataSet; // @synthesize dataSet=_dataSet;
@property(copy, nonatomic) CDUnknownBlockType emptyViewActionBlock; // @synthesize emptyViewActionBlock=_emptyViewActionBlock;
@property(copy, nonatomic) CDUnknownBlockType emptyBtnActionBlock; // @synthesize emptyBtnActionBlock=_emptyBtnActionBlock;
@property(copy, nonatomic) NSString *emptyBtnTitle; // @synthesize emptyBtnTitle=_emptyBtnTitle;
@property(retain, nonatomic) WLEmptyAssistantConfiger *netWorkConfiger; // @synthesize netWorkConfiger=_netWorkConfiger;
@property(retain, nonatomic) WLEmptyAssistantConfiger *normalLoadingConfiger; // @synthesize normalLoadingConfiger=_normalLoadingConfiger;
@property(retain, nonatomic) WLEmptyAssistantConfiger *loadingConfiger; // @synthesize loadingConfiger=_loadingConfiger;
@property(retain, nonatomic) WLEmptyAssistantConfiger *normalemptyConfiger; // @synthesize normalemptyConfiger=_normalemptyConfiger;
@property(retain, nonatomic) WLEmptyAssistantConfiger *emptyConfiger; // @synthesize emptyConfiger=_emptyConfiger;
@property(nonatomic) unsigned long long emptyViewType; // @synthesize emptyViewType=_emptyViewType;
- (void).cxx_destruct;
- (void)emptyDataSetWillDisappear:(id)arg1;
- (void)emptyDataSet:(id)arg1 didTapView:(id)arg2;
- (void)emptyDataSet:(id)arg1 didTapButton:(id)arg2;
- (_Bool)emptyDataSetShouldAllowTouch:(id)arg1;
- (_Bool)emptyDataSetShouldAnimateImageView:(id)arg1;
- (id)placeholderIndexPath:(id)arg1;
- (double)spaceHeightForEmptyDataSet:(id)arg1;
- (double)verticalOffsetForEmptyDataSet:(id)arg1;
- (_Bool)emptyDataSetShouldDisplay:(id)arg1;
- (_Bool)emptyDataSetShouldAllowScroll:(id)arg1;
- (id)backgroundColorForEmptyDataSet:(id)arg1;
- (id)buttonBackgroundImageForEmptyDataSet:(id)arg1 forState:(unsigned long long)arg2;
- (id)buttonTitleForEmptyDataSet:(id)arg1 forState:(unsigned long long)arg2;
- (id)imageAnimationForEmptyDataSet:(id)arg1;
- (id)imageTintColorForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (id)descriptionForEmptyDataSet:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (void)accordingToLogical;
- (void)setConfigerWithEmptyViewType:(unsigned long long)arg1 Block:(CDUnknownBlockType)arg2;
- (id)initWithContentView:(id)arg1 configer:(id)arg2 dataSet:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

