//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WLServiceInfo : NSObject
{
    _Bool _favorableGuidanceBoole;
    _Bool _isTest;
    NSString *_serviceBaseUrl;
    NSString *_h5ServiceBaseUrl;
    NSString *_ossBucket;
    NSString *_ossFileBucket;
    NSString *_rongCloudAppKey;
    NSString *_uMengAppKey;
    NSString *_QYSDKAppKey;
    NSString *_QYSDKAppName;
    long long _QYWalletTemplateId;
    long long _QYInvestTemplateId;
    long long _QYLoginTemplateId;
    long long _QYDefaultGroupId;
    long long _QYWalletGroupId;
    long long _QYInvestGroupId;
    long long _QYLoginGroupId;
    NSString *_magicWindowAppKey;
    NSString *_weChatAppId;
    NSString *_weChatAppSecret;
    NSString *_alipayAppScheme;
    NSString *_appStoreID;
    NSString *_BMKKey;
}

+ (id)sharedServiceInfo;
@property(copy, nonatomic) NSString *BMKKey; // @synthesize BMKKey=_BMKKey;
@property(copy, nonatomic) NSString *appStoreID; // @synthesize appStoreID=_appStoreID;
@property(copy, nonatomic) NSString *alipayAppScheme; // @synthesize alipayAppScheme=_alipayAppScheme;
@property(copy, nonatomic) NSString *weChatAppSecret; // @synthesize weChatAppSecret=_weChatAppSecret;
@property(copy, nonatomic) NSString *weChatAppId; // @synthesize weChatAppId=_weChatAppId;
@property(copy, nonatomic) NSString *magicWindowAppKey; // @synthesize magicWindowAppKey=_magicWindowAppKey;
@property(nonatomic) long long QYLoginGroupId; // @synthesize QYLoginGroupId=_QYLoginGroupId;
@property(nonatomic) long long QYInvestGroupId; // @synthesize QYInvestGroupId=_QYInvestGroupId;
@property(nonatomic) long long QYWalletGroupId; // @synthesize QYWalletGroupId=_QYWalletGroupId;
@property(nonatomic) long long QYDefaultGroupId; // @synthesize QYDefaultGroupId=_QYDefaultGroupId;
@property(nonatomic) long long QYLoginTemplateId; // @synthesize QYLoginTemplateId=_QYLoginTemplateId;
@property(nonatomic) long long QYInvestTemplateId; // @synthesize QYInvestTemplateId=_QYInvestTemplateId;
@property(nonatomic) long long QYWalletTemplateId; // @synthesize QYWalletTemplateId=_QYWalletTemplateId;
@property(copy, nonatomic) NSString *QYSDKAppName; // @synthesize QYSDKAppName=_QYSDKAppName;
@property(copy, nonatomic) NSString *QYSDKAppKey; // @synthesize QYSDKAppKey=_QYSDKAppKey;
@property(copy, nonatomic) NSString *uMengAppKey; // @synthesize uMengAppKey=_uMengAppKey;
@property(copy, nonatomic) NSString *rongCloudAppKey; // @synthesize rongCloudAppKey=_rongCloudAppKey;
@property(copy, nonatomic) NSString *ossFileBucket; // @synthesize ossFileBucket=_ossFileBucket;
@property(copy, nonatomic) NSString *ossBucket; // @synthesize ossBucket=_ossBucket;
@property(copy, nonatomic) NSString *h5ServiceBaseUrl; // @synthesize h5ServiceBaseUrl=_h5ServiceBaseUrl;
@property(copy, nonatomic) NSString *serviceBaseUrl; // @synthesize serviceBaseUrl=_serviceBaseUrl;
@property(nonatomic) _Bool isTest; // @synthesize isTest=_isTest;
@property(nonatomic) _Bool favorableGuidanceBoole; // @synthesize favorableGuidanceBoole=_favorableGuidanceBoole;
- (void).cxx_destruct;
- (void)popUpFavorableGuidance;

@end

