//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WLSystemManager : NSObject
{
}

+ (_Bool)wl_filesCopy:(id)arg1 TargetName:(id)arg2;
+ (_Bool)wl_filesMove:(id)arg1 TargetName:(id)arg2;
+ (_Bool)wl_fileDelete:(id)arg1;
+ (_Bool)wl_fileExistByPath:(id)arg1;
+ (_Bool)wl_getFileAttributes:(id)arg1 TargetSize:(long long)arg2;
+ (long long)wl_fileSizeAtPath:(id)arg1;
+ (void)wl_cleanCache;
+ (void)wl_setCache:(id)arg1 forKey:(id)arg2;
+ (id)wl_cacheForKey:(id)arg1;
+ (id)wl_filePathForRelativePath:(id)arg1;
+ (id)wl_userResourcePath;
+ (id)wl_navResourcePath;
+ (id)wl_saveImage:(id)arg1 ToFolder:(id)arg2 WithName:(id)arg3;
+ (id)wl_imageWithPath:(id)arg1 isCache:(_Bool)arg2 inCach:(_Bool)arg3;
+ (id)wl_imageWithPath:(id)arg1 isCache:(_Bool)arg2;
+ (id)wl_imageWithPath:(id)arg1;
+ (id)wl_imageWithCachePath:(id)arg1;
+ (id)wl_filePathForCachesPath:(id)arg1;
+ (void)init3DTouchActionShow:(_Bool)arg1;
+ (_Bool)isVersionfirst;

@end

