//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIScrollViewDelegate-Protocol.h"

@class NSString, UIImage, UIImageView, UIScrollView;
@protocol WLZoomImageViewDelegate;

@interface WLZoomImageView : UIView <UIScrollViewDelegate>
{
    _Bool _allowCrop;
    id <WLZoomImageViewDelegate> _delegate;
    double _maximumZoomScale;
    UIImage *_image;
    UIImageView *_imageView;
    UIScrollView *_scrollView;
    UIView *_imageContainerView;
    struct CGRect _cropRect;
}

@property(retain, nonatomic) UIView *imageContainerView; // @synthesize imageContainerView=_imageContainerView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) struct CGRect cropRect; // @synthesize cropRect=_cropRect;
@property(nonatomic) _Bool allowCrop; // @synthesize allowCrop=_allowCrop;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) double maximumZoomScale; // @synthesize maximumZoomScale=_maximumZoomScale;
@property(nonatomic) __weak id <WLZoomImageViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)refreshImageContainerViewCenter;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(double)arg3;
- (void)scrollViewDidZoom:(id)arg1;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)handleLongPressGesture:(id)arg1;
- (void)handleDoubleTapGestureWithPoint:(id)arg1;
- (void)handleSingleTapGestureWithPoint:(id)arg1;
- (void)refreshScrollViewContentSize;
- (void)resizeSubviews;
- (void)recoverSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

