//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

#import "UIPickerViewDataSource-Protocol.h"
#import "UIPickerViewDelegate-Protocol.h"

@class NSArray, NSDictionary, NSString, UIPickerView, UIView, YJToolBar;

@interface YJLocationPicker : UIButton <UIPickerViewDataSource, UIPickerViewDelegate>
{
    CDUnknownBlockType _selectedLocation;
    NSDictionary *_pickerDic;
    NSArray *_provinceArray;
    NSArray *_cityArray;
    NSArray *_selectedArray;
    UIPickerView *_pickerView;
    YJToolBar *_toolBar;
    UIView *_lineView;
    UIView *_lineView2;
    long long _selectRow1;
    long long _selectRow2;
}

@property(nonatomic) long long selectRow2; // @synthesize selectRow2=_selectRow2;
@property(nonatomic) long long selectRow1; // @synthesize selectRow1=_selectRow1;
@property(retain, nonatomic) UIView *lineView2; // @synthesize lineView2=_lineView2;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) YJToolBar *toolBar; // @synthesize toolBar=_toolBar;
@property(retain, nonatomic) UIPickerView *pickerView; // @synthesize pickerView=_pickerView;
@property(retain, nonatomic) NSArray *selectedArray; // @synthesize selectedArray=_selectedArray;
@property(retain, nonatomic) NSArray *cityArray; // @synthesize cityArray=_cityArray;
@property(retain, nonatomic) NSArray *provinceArray; // @synthesize provinceArray=_provinceArray;
@property(retain, nonatomic) NSDictionary *pickerDic; // @synthesize pickerDic=_pickerDic;
@property(copy, nonatomic) CDUnknownBlockType selectedLocation; // @synthesize selectedLocation=_selectedLocation;
- (void).cxx_destruct;
- (id)toolbar;
- (void)remove;
- (void)show;
- (void)reloadata;
- (void)confirmAction;
- (void)cancelAction;
- (id)pickerView:(id)arg1 viewForRow:(long long)arg2 forComponent:(long long)arg3 reusingView:(id)arg4;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (void)loadData;
- (void)setupUI;
- (id)init;
- (id)initWithProvince:(id)arg1 cityDict:(id)arg2 SlectedLocation:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

